select PERSON_PARENT,PERSON_PARENT as PERSON_PARENT1,PERSON_NUMBER,PERSON_FULLNAME,PERSON_JOBDESC,PERSON_CITY,PERSON_POSTALCODE,PERSON_COUNTRY,PERSON_REGION,PERSON_STREET,PERSON_EMAILCUSTOMERINVOICE,PERSON_EMAILCONFIRMATIONORDER,PERSON_EMAILDELIVERYSLIP,PERSON_EMAILDUNNING,PERSON_EMAILTRACKING,INSERTDATE from erp_temp_crm_contatti 
----------------------TOTAL TIME------------------------
time of import : 315 s  | 5 m 15 s   
----------------------TOTAL TIME------------------------
