<?php
include_once('../../config.inc.php');
chdir($root_directory);
require_once('include/utils/utils.php');
include_once('vtlib/Vtiger/Module.php');
$Vtiger_Utils_Log = true;
global $adb, $table_prefix;
session_start();

// Turn on debugging level
$Vtiger_Utils_Log = true;
include_once('vtlib/Vtiger/Menu.php');
include_once('vtlib/Vtiger/Module.php');

// INIZIO temp_country_iso danzi.tn@20131206 procedura cambio codici nazione
$temp_country_iso = array(
	array( // row #0
		'id' => 4,
		'iso3' => 'AFG',
		'iso2' => 'AF',
		'english' => 'Afghanistan',
		'german' => 'Afghanistan',
		'spanish' => 'Afganistán',
		'french' => 'Afghanistan',
		'italian' => 'Afghanistan',
		'portuguese' => 'Afeganistão',
		'version' => NULL,
	),
	array( // row #1
		'id' => 8,
		'iso3' => 'ALB',
		'iso2' => 'AL',
		'english' => 'Albania',
		'german' => 'Albanien',
		'spanish' => 'Albania',
		'french' => 'Albanie',
		'italian' => 'Albania',
		'portuguese' => 'Albânia',
		'version' => NULL,
	),
	array( // row #2
		'id' => 10,
		'iso3' => 'ATA',
		'iso2' => 'AQ',
		'english' => 'Antarctica',
		'german' => 'Antarktis',
		'spanish' => 'Antártida',
		'french' => 'Antarctique',
		'italian' => 'Antartide',
		'portuguese' => 'Antárctida',
		'version' => NULL,
	),
	array( // row #3
		'id' => 12,
		'iso3' => 'DZA',
		'iso2' => 'DZ',
		'english' => 'Algeria',
		'german' => 'Algerien',
		'spanish' => 'Argelia',
		'french' => 'Algérie',
		'italian' => 'Algeria',
		'portuguese' => 'Argélia',
		'version' => NULL,
	),
	array( // row #4
		'id' => 16,
		'iso3' => 'ASM',
		'iso2' => 'AS',
		'english' => 'American Samoa',
		'german' => 'Amerikanisch-Samoa',
		'spanish' => 'Samoa Americana',
		'french' => 'Samoa américaines',
		'italian' => 'Samoa Americane',
		'portuguese' => 'Samoa Americana',
		'version' => NULL,
	),
	array( // row #5
		'id' => 20,
		'iso3' => 'AND',
		'iso2' => 'AD',
		'english' => 'Andorra',
		'german' => 'Andorra',
		'spanish' => 'Andorra',
		'french' => 'Andorre',
		'italian' => 'Andorra',
		'portuguese' => 'Andorra',
		'version' => NULL,
	),
	array( // row #6
		'id' => 24,
		'iso3' => 'AGO',
		'iso2' => 'AO',
		'english' => 'Angola',
		'german' => 'Angola',
		'spanish' => 'Angola',
		'french' => 'Angola',
		'italian' => 'Angola',
		'portuguese' => 'Angola',
		'version' => NULL,
	),
	array( // row #7
		'id' => 28,
		'iso3' => 'ATG',
		'iso2' => 'AG',
		'english' => 'Antigua and Barbuda',
		'german' => 'Antigua und Barbuda',
		'spanish' => 'Antigua y Barbuda',
		'french' => 'Antigua-et-Barbuda',
		'italian' => 'Antigua e Barbuda',
		'portuguese' => 'Antigua e Barbuda',
		'version' => NULL,
	),
	array( // row #8
		'id' => 31,
		'iso3' => 'AZE',
		'iso2' => 'AZ',
		'english' => 'Azerbaijan',
		'german' => 'Aserbaidschan',
		'spanish' => 'Azerbaiyán',
		'french' => 'Azerbaïdjan',
		'italian' => 'Azerbaijan',
		'portuguese' => 'Azerbeijão',
		'version' => NULL,
	),
	array( // row #9
		'id' => 32,
		'iso3' => 'ARG',
		'iso2' => 'AR',
		'english' => 'Argentina',
		'german' => 'Argentinien',
		'spanish' => 'Argentina',
		'french' => 'Argentine',
		'italian' => 'Argentina',
		'portuguese' => 'Argentina',
		'version' => NULL,
	),
	array( // row #10
		'id' => 36,
		'iso3' => 'AUS',
		'iso2' => 'AU',
		'english' => 'Australia',
		'german' => 'Australien',
		'spanish' => 'Australia',
		'french' => 'Australie',
		'italian' => 'Australia',
		'portuguese' => 'Austrália',
		'version' => NULL,
	),
	array( // row #11
		'id' => 40,
		'iso3' => 'AUT',
		'iso2' => 'AT',
		'english' => 'Austria',
		'german' => 'Österreich',
		'spanish' => 'Austria',
		'french' => 'Autriche',
		'italian' => 'Austria',
		'portuguese' => 'Áustria',
		'version' => NULL,
	),
	array( // row #12
		'id' => 44,
		'iso3' => 'BHS',
		'iso2' => 'BS',
		'english' => 'Bahamas',
		'german' => 'Bahamas',
		'spanish' => 'Bahamas',
		'french' => 'Bahamas',
		'italian' => 'Bahamas',
		'portuguese' => 'Bahamas',
		'version' => NULL,
	),
	array( // row #13
		'id' => 48,
		'iso3' => 'BHR',
		'iso2' => 'BH',
		'english' => 'Bahrain',
		'german' => 'Bahrain',
		'spanish' => 'Bahréin',
		'french' => 'Bahreïn',
		'italian' => 'Bahrain',
		'portuguese' => 'Bahrain',
		'version' => NULL,
	),
	array( // row #14
		'id' => 50,
		'iso3' => 'BGD',
		'iso2' => 'BD',
		'english' => 'Bangladesh',
		'german' => 'Bangladesch',
		'spanish' => 'Bangladesh',
		'french' => 'Bangladesh',
		'italian' => 'Bangladesh',
		'portuguese' => 'Bangladesh',
		'version' => NULL,
	),
	array( // row #15
		'id' => 51,
		'iso3' => 'ARM',
		'iso2' => 'AM',
		'english' => 'Armenia',
		'german' => 'Armenien',
		'spanish' => 'Armenia',
		'french' => 'Arménie',
		'italian' => 'Armenia',
		'portuguese' => 'Arménia',
		'version' => NULL,
	),
	array( // row #16
		'id' => 52,
		'iso3' => 'BRB',
		'iso2' => 'BB',
		'english' => 'Barbados',
		'german' => 'Barbados',
		'spanish' => 'Barbados',
		'french' => 'Barbade',
		'italian' => 'Barbados',
		'portuguese' => 'Barbados',
		'version' => NULL,
	),
	array( // row #17
		'id' => 56,
		'iso3' => 'BEL',
		'iso2' => 'BE',
		'english' => 'Belgium',
		'german' => 'Belgien',
		'spanish' => 'Bélgica',
		'french' => 'Belgique',
		'italian' => 'Belgio',
		'portuguese' => 'Bélgica',
		'version' => NULL,
	),
	array( // row #18
		'id' => 60,
		'iso3' => 'BMU',
		'iso2' => 'BM',
		'english' => 'Bermuda',
		'german' => 'Bermuda',
		'spanish' => 'Bermudas',
		'french' => 'Bermudes',
		'italian' => 'Bermuda',
		'portuguese' => 'Bermuda',
		'version' => NULL,
	),
	array( // row #19
		'id' => 64,
		'iso3' => 'BTN',
		'iso2' => 'BT',
		'english' => 'Bhutan',
		'german' => 'Bhutan',
		'spanish' => 'Bután',
		'french' => 'Bhoutan',
		'italian' => 'Bhutan',
		'portuguese' => 'Butão',
		'version' => NULL,
	),
	array( // row #20
		'id' => 68,
		'iso3' => 'BOL',
		'iso2' => 'BO',
		'english' => 'Bolivia',
		'german' => 'Bolivien',
		'spanish' => 'Bolivia',
		'french' => 'Bolivie',
		'italian' => 'Bolivia',
		'portuguese' => 'Bolívia',
		'version' => NULL,
	),
	array( // row #21
		'id' => 70,
		'iso3' => 'BIH',
		'iso2' => 'BA',
		'english' => 'Bosnia and Herzegovina',
		'german' => 'Bosnien und Herzegowina',
		'spanish' => 'Bosnia y Herzegovina',
		'french' => 'Bosnie-Herzégovine',
		'italian' => 'Bosnia-Erzegovina',
		'portuguese' => 'Bósnia-Herzegovina',
		'version' => NULL,
	),
	array( // row #22
		'id' => 72,
		'iso3' => 'BWA',
		'iso2' => 'BW',
		'english' => 'Botswana',
		'german' => 'Botswana',
		'spanish' => 'Botsuana',
		'french' => 'Botswana',
		'italian' => 'Botswana',
		'portuguese' => 'Botswana',
		'version' => NULL,
	),
	array( // row #23
		'id' => 74,
		'iso3' => 'BVT',
		'iso2' => 'BV',
		'english' => 'Bouvet Island',
		'german' => 'Bouvetinsel',
		'spanish' => 'Isla Bouvet',
		'french' => 'Île Bouvet',
		'italian' => 'Isola Bouvet',
		'portuguese' => 'Ilha Bouvet',
		'version' => NULL,
	),
	array( // row #24
		'id' => 76,
		'iso3' => 'BRA',
		'iso2' => 'BR',
		'english' => 'Brazil',
		'german' => 'Brasilien',
		'spanish' => 'Brasil',
		'french' => 'Brésil',
		'italian' => 'Brasile',
		'portuguese' => 'Brasil',
		'version' => NULL,
	),
	array( // row #25
		'id' => 84,
		'iso3' => 'BLZ',
		'iso2' => 'BZ',
		'english' => 'Belize',
		'german' => 'Belize',
		'spanish' => 'Belice',
		'french' => 'Belize',
		'italian' => 'Belize',
		'portuguese' => 'Belize',
		'version' => NULL,
	),
	array( // row #26
		'id' => 86,
		'iso3' => 'IOT',
		'iso2' => 'IO',
		'english' => 'British Indian Ocean Territory',
		'german' => 'Britisches Territorium im Indischen Ozean',
		'spanish' => 'Territorio Británico del Océano Índico',
		'french' => 'Territoire britannique de l\'océan Indien',
		'italian' => 'Territorio Britannico dell\'Oceano Indiano',
		'portuguese' => 'Território Britânico do Oceano Índico',
		'version' => NULL,
	),
	array( // row #27
		'id' => 90,
		'iso3' => 'SLB',
		'iso2' => 'SB',
		'english' => 'Solomon Islands',
		'german' => 'Salomonen',
		'spanish' => 'Islas Salomón',
		'french' => 'Îles Salomon',
		'italian' => 'Isole Solomon',
		'portuguese' => 'Ilhas Salomão',
		'version' => NULL,
	),
	array( // row #28
		'id' => 92,
		'iso3' => 'VGB',
		'iso2' => 'VG',
		'english' => 'Virgin Islands, British',
		'german' => 'Britische Jungferninseln',
		'spanish' => 'Islas Vírgenes Británicas',
		'french' => 'Îles Vierges britanniques',
		'italian' => 'Territori Britannici dell\'Oceano Indiano',
		'portuguese' => 'Ilhas Virgens Britânicas',
		'version' => NULL,
	),
	array( // row #29
		'id' => 96,
		'iso3' => 'BRN',
		'iso2' => 'BN',
		'english' => 'Brunei Darussalam',
		'german' => 'Brunei Darussalam',
		'spanish' => 'Brunéi',
		'french' => 'Brunei',
		'italian' => 'Brunei Darussalam',
		'portuguese' => 'Brunei',
		'version' => NULL,
	),
	array( // row #30
		'id' => 100,
		'iso3' => 'BGR',
		'iso2' => 'BG',
		'english' => 'Bulgaria',
		'german' => 'Bulgarien',
		'spanish' => 'Bulgaria',
		'french' => 'Bulgarie',
		'italian' => 'Bulgaria',
		'portuguese' => 'Bulgária',
		'version' => NULL,
	),
	array( // row #31
		'id' => 104,
		'iso3' => 'MMR',
		'iso2' => 'MM',
		'english' => 'Myanmar',
		'german' => 'Myanmar (Burma)',
		'spanish' => 'Myanmar',
		'french' => 'Birmanie',
		'italian' => 'Myanmar',
		'portuguese' => 'Myanmar (antiga \'\'Birmânia\'\')',
		'version' => NULL,
	),
	array( // row #32
		'id' => 108,
		'iso3' => 'BDI',
		'iso2' => 'BI',
		'english' => 'Burundi',
		'german' => 'Burundi',
		'spanish' => 'Burundi',
		'french' => 'Burundi',
		'italian' => 'Burundi',
		'portuguese' => 'Burundi',
		'version' => NULL,
	),
	array( // row #33
		'id' => 112,
		'iso3' => 'BLR',
		'iso2' => 'BY',
		'english' => 'Belarus',
		'german' => 'Belarus (Weißrussland)',
		'spanish' => 'Bielorrusia',
		'french' => 'Biélorussie',
		'italian' => 'Bielorussia',
		'portuguese' => 'Bielo-Rússia',
		'version' => NULL,
	),
	array( // row #34
		'id' => 116,
		'iso3' => 'KHM',
		'iso2' => 'KH',
		'english' => 'Cambodia',
		'german' => 'Kambodscha',
		'spanish' => 'Camboya',
		'french' => 'Cambodge',
		'italian' => 'Cambogia',
		'portuguese' => 'Cambodja',
		'version' => NULL,
	),
	array( // row #35
		'id' => 120,
		'iso3' => 'CMR',
		'iso2' => 'CM',
		'english' => 'Cameroon',
		'german' => 'Kamerun',
		'spanish' => 'Camerún',
		'french' => 'Cameroun',
		'italian' => 'Camerun',
		'portuguese' => 'Camarões',
		'version' => NULL,
	),
	array( // row #36
		'id' => 124,
		'iso3' => 'CAN',
		'iso2' => 'CA',
		'english' => 'Canada',
		'german' => 'Kanada',
		'spanish' => 'Canadá',
		'french' => 'Canada',
		'italian' => 'Canada',
		'portuguese' => 'Canadá',
		'version' => NULL,
	),
	array( // row #37
		'id' => 132,
		'iso3' => 'CPV',
		'iso2' => 'CV',
		'english' => 'Cape Verde',
		'german' => 'Kap Verde',
		'spanish' => 'Cabo Verde',
		'french' => 'Cap-Vert',
		'italian' => 'Capo Verde',
		'portuguese' => 'Cabo Verde',
		'version' => NULL,
	),
	array( // row #38
		'id' => 136,
		'iso3' => 'CYM',
		'iso2' => 'KY',
		'english' => 'Cayman Islands',
		'german' => 'Kaimaninseln',
		'spanish' => 'Islas Caimán',
		'french' => 'Îles Caïmanes',
		'italian' => 'Isole Cayman',
		'portuguese' => 'Ilhas Cayman',
		'version' => NULL,
	),
	array( // row #39
		'id' => 140,
		'iso3' => 'CAF',
		'iso2' => 'CF',
		'english' => 'Central African Republic',
		'german' => 'Zentralafrikanische Republik',
		'spanish' => 'República Centroafricana',
		'french' => 'Centrafrique',
		'italian' => 'Repubblica Centroafricana',
		'portuguese' => 'República Centro-africana',
		'version' => NULL,
	),
	array( // row #40
		'id' => 144,
		'iso3' => 'LKA',
		'iso2' => 'LK',
		'english' => 'Sri Lanka',
		'german' => 'Sri Lanka',
		'spanish' => 'Sri Lanka',
		'french' => 'Sri Lanka',
		'italian' => 'Sri Lanka',
		'portuguese' => 'Sri Lanka',
		'version' => NULL,
	),
	array( // row #41
		'id' => 148,
		'iso3' => 'TCD',
		'iso2' => 'TD',
		'english' => 'Chad',
		'german' => 'Tschad',
		'spanish' => 'Chad',
		'french' => 'Tchad',
		'italian' => 'Ciad',
		'portuguese' => 'Chade',
		'version' => NULL,
	),
	array( // row #42
		'id' => 152,
		'iso3' => 'CHL',
		'iso2' => 'CL',
		'english' => 'Chile',
		'german' => 'Chile',
		'spanish' => 'Chile',
		'french' => 'Chili',
		'italian' => 'Cile',
		'portuguese' => 'Chile',
		'version' => NULL,
	),
	array( // row #43
		'id' => 156,
		'iso3' => 'CHN',
		'iso2' => 'CN',
		'english' => 'China',
		'german' => 'China, Volksrepublik',
		'spanish' => 'China',
		'french' => 'Chine',
		'italian' => 'Cina',
		'portuguese' => 'China',
		'version' => NULL,
	),
	array( // row #44
		'id' => 158,
		'iso3' => 'TWN',
		'iso2' => 'TW',
		'english' => 'Taiwan, Province of China',
		'german' => 'Republik China (Taiwan)',
		'spanish' => 'Taiwán',
		'french' => 'Taïwan / (République de Chine)',
		'italian' => 'Taiwan',
		'portuguese' => 'Taiwan',
		'version' => NULL,
	),
	array( // row #45
		'id' => 162,
		'iso3' => 'CXR',
		'iso2' => 'CX',
		'english' => 'Christmas Island',
		'german' => 'Weihnachtsinsel',
		'spanish' => 'Isla de Navidad',
		'french' => 'Île Christmas',
		'italian' => 'Isola di Natale',
		'portuguese' => 'Ilha Christmas',
		'version' => NULL,
	),
	array( // row #46
		'id' => 166,
		'iso3' => 'CCK',
		'iso2' => 'CC',
		'english' => 'Cocos (Keeling) Islands',
		'german' => 'Kokosinseln',
		'spanish' => 'Islas Cocos',
		'french' => 'Îles Cocos',
		'italian' => 'Isole Cocos',
		'portuguese' => 'Ilhas Cocos',
		'version' => NULL,
	),
	array( // row #47
		'id' => 170,
		'iso3' => 'COL',
		'iso2' => 'CO',
		'english' => 'Colombia',
		'german' => 'Kolumbien',
		'spanish' => 'Colombia',
		'french' => 'Colombie',
		'italian' => 'Colombia',
		'portuguese' => 'Colômbia',
		'version' => NULL,
	),
	array( // row #48
		'id' => 174,
		'iso3' => 'COM',
		'iso2' => 'KM',
		'english' => 'Comoros',
		'german' => 'Komoren',
		'spanish' => 'Comoras',
		'french' => 'Comores',
		'italian' => 'Comore',
		'portuguese' => 'Comores',
		'version' => NULL,
	),
	array( // row #49
		'id' => 175,
		'iso3' => 'MYT',
		'iso2' => 'YT',
		'english' => 'Mayotte',
		'german' => 'Mayotte',
		'spanish' => 'Mayotte',
		'french' => 'Mayotte',
		'italian' => 'Mayotte',
		'portuguese' => 'Mayotte',
		'version' => NULL,
	),
	array( // row #50
		'id' => 178,
		'iso3' => 'COG',
		'iso2' => 'CG',
		'english' => 'Congo',
		'german' => 'Republik Kongo',
		'spanish' => 'República del Congo',
		'french' => 'Congo-Brazzaville / (Congo)',
		'italian' => 'Repubblica del Congo',
		'portuguese' => 'República do Congo',
		'version' => NULL,
	),
	array( // row #51
		'id' => 180,
		'iso3' => 'COD',
		'iso2' => 'CD',
		'english' => 'Congo, Democratic Republic of the',
		'german' => 'Zaire (jetzt Demokratische Republik Kongo)',
		'spanish' => 'República Democrática del Congo',
		'french' => 'Congo-Kinshasa / (République démocratique du Congo)',
		'italian' => 'Repubblica Democratica del Congo',
		'portuguese' => 'República Democrática do Congo',
		'version' => NULL,
	),
	array( // row #52
		'id' => 184,
		'iso3' => 'COK',
		'iso2' => 'CK',
		'english' => 'Cook Islands',
		'german' => 'Cookinseln',
		'spanish' => 'Islas Cook',
		'french' => 'Îles Cook',
		'italian' => 'Isole Cook',
		'portuguese' => 'Ilhas Cook',
		'version' => NULL,
	),
	array( // row #53
		'id' => 188,
		'iso3' => 'CRI',
		'iso2' => 'CR',
		'english' => 'Costa Rica',
		'german' => 'Costa Rica',
		'spanish' => 'Costa Rica',
		'french' => 'Costa Rica',
		'italian' => 'Costa Rica',
		'portuguese' => 'Costa Rica',
		'version' => NULL,
	),
	array( // row #54
		'id' => 191,
		'iso3' => 'HRV',
		'iso2' => 'HR',
		'english' => 'Croatia',
		'german' => 'Kroatien',
		'spanish' => 'Croacia',
		'french' => 'Croatie',
		'italian' => 'Croazia',
		'portuguese' => 'Croácia',
		'version' => NULL,
	),
	array( // row #55
		'id' => 192,
		'iso3' => 'CUB',
		'iso2' => 'CU',
		'english' => 'Cuba',
		'german' => 'Kuba',
		'spanish' => 'Cuba',
		'french' => 'Cuba',
		'italian' => 'Cuba',
		'portuguese' => 'Cuba',
		'version' => NULL,
	),
	array( // row #56
		'id' => 196,
		'iso3' => 'CYP',
		'iso2' => 'CY',
		'english' => 'Cyprus',
		'german' => 'Zypern',
		'spanish' => 'Chipre',
		'french' => 'Chypre (pays)||CHYPRE',
		'italian' => 'Cipro',
		'portuguese' => 'Chipre',
		'version' => NULL,
	),
	array( // row #57
		'id' => 203,
		'iso3' => 'CZE',
		'iso2' => 'CZ',
		'english' => 'Czech Republic',
		'german' => 'Tschechische Republik',
		'spanish' => 'República Checa',
		'french' => 'République tchèque',
		'italian' => 'Repubblica Ceca',
		'portuguese' => 'República Checa',
		'version' => NULL,
	),
	array( // row #58
		'id' => 204,
		'iso3' => 'BEN',
		'iso2' => 'BJ',
		'english' => 'Benin',
		'german' => 'Benin',
		'spanish' => 'Benín',
		'french' => 'Bénin',
		'italian' => 'Benin',
		'portuguese' => 'Benin',
		'version' => NULL,
	),
	array( // row #59
		'id' => 208,
		'iso3' => 'DNK',
		'iso2' => 'DK',
		'english' => 'Denmark',
		'german' => 'Dänemark',
		'spanish' => 'Dinamarca',
		'french' => 'Danemark',
		'italian' => 'Danimarca',
		'portuguese' => 'Dinamarca',
		'version' => NULL,
	),
	array( // row #60
		'id' => 212,
		'iso3' => 'DMA',
		'iso2' => 'DM',
		'english' => 'Dominica',
		'german' => 'Dominica',
		'spanish' => 'Dominica',
		'french' => 'Dominique',
		'italian' => 'Dominica',
		'portuguese' => 'Dominica',
		'version' => NULL,
	),
	array( // row #61
		'id' => 214,
		'iso3' => 'DOM',
		'iso2' => 'DO',
		'english' => 'Dominican Republic',
		'german' => 'Dominikanische Republik',
		'spanish' => 'República Dominicana',
		'french' => 'République dominicaine',
		'italian' => 'Repubblica Dominicana',
		'portuguese' => 'República Dominicana',
		'version' => NULL,
	),
	array( // row #62
		'id' => 218,
		'iso3' => 'ECU',
		'iso2' => 'EC',
		'english' => 'Ecuador',
		'german' => 'Ecuador',
		'spanish' => 'Ecuador',
		'french' => 'Équateur',
		'italian' => 'Ecuador',
		'portuguese' => 'Equador',
		'version' => NULL,
	),
	array( // row #63
		'id' => 222,
		'iso3' => 'SLV',
		'iso2' => 'SV',
		'english' => 'El Salvador',
		'german' => 'El Salvador',
		'spanish' => 'El Salvador',
		'french' => 'Salvador',
		'italian' => 'El Salvador',
		'portuguese' => 'El Salvador',
		'version' => NULL,
	),
	array( // row #64
		'id' => 226,
		'iso3' => 'GNQ',
		'iso2' => 'GQ',
		'english' => 'Equatorial Guinea',
		'german' => 'Äquatorialguinea',
		'spanish' => 'Guinea Ecuatorial',
		'french' => 'Guinée équatoriale',
		'italian' => 'Guinea Equatoriale',
		'portuguese' => 'Guiné Equatorial',
		'version' => NULL,
	),
	array( // row #65
		'id' => 231,
		'iso3' => 'ETH',
		'iso2' => 'ET',
		'english' => 'Ethiopia',
		'german' => 'Äthiopien',
		'spanish' => 'Etiopía',
		'french' => 'Éthiopie',
		'italian' => 'Etiopia',
		'portuguese' => 'Etiópia',
		'version' => NULL,
	),
	array( // row #66
		'id' => 232,
		'iso3' => 'ERI',
		'iso2' => 'ER',
		'english' => 'Eritrea',
		'german' => 'Eritrea',
		'spanish' => 'Eritrea',
		'french' => 'Érythrée',
		'italian' => 'Eritrea',
		'portuguese' => 'Eritreia',
		'version' => NULL,
	),
	array( // row #67
		'id' => 233,
		'iso3' => 'EST',
		'iso2' => 'EE',
		'english' => 'Estonia',
		'german' => 'Estland',
		'spanish' => 'Estonia',
		'french' => 'Estonie',
		'italian' => 'Estonia',
		'portuguese' => 'Estónia',
		'version' => NULL,
	),
	array( // row #68
		'id' => 234,
		'iso3' => 'FRO',
		'iso2' => 'FO',
		'english' => 'Faroe Islands',
		'german' => 'Färöer',
		'spanish' => 'Islas Feroe',
		'french' => 'Îles Féroé',
		'italian' => 'Isole Faroe',
		'portuguese' => 'Ilhas Faroe',
		'version' => NULL,
	),
	array( // row #69
		'id' => 238,
		'iso3' => 'FLK',
		'iso2' => 'FK',
		'english' => 'Falkland Islands (Malvinas)',
		'german' => 'Falklandinseln',
		'spanish' => 'Islas Malvinas',
		'french' => 'Îles Malouines',
		'italian' => 'Isole Falkland',
		'portuguese' => 'Ilhas Malvinas',
		'version' => NULL,
	),
	array( // row #70
		'id' => 239,
		'iso3' => 'SGS',
		'iso2' => 'GS',
		'english' => 'South Georgia and the South Sandwich Islands',
		'german' => 'Südgeorgien und die Südlichen Sandwichinseln',
		'spanish' => 'Islas Georgias del Sur y Sandwich del Sur',
		'french' => 'Géorgie du Sud et les îles Sandwich du Sud',
		'italian' => 'Sud Georgia e Isole Sandwich',
		'portuguese' => 'Ilhas Geórgia do Sul e Sandwich do Sul',
		'version' => NULL,
	),
	array( // row #71
		'id' => 242,
		'iso3' => 'FJI',
		'iso2' => 'FJ',
		'english' => 'Fiji',
		'german' => 'Fidschi',
		'spanish' => 'Fiyi',
		'french' => 'Fidji',
		'italian' => 'Fiji',
		'portuguese' => 'Fiji',
		'version' => NULL,
	),
	array( // row #72
		'id' => 246,
		'iso3' => 'FIN',
		'iso2' => 'FI',
		'english' => 'Finland',
		'german' => 'Finnland',
		'spanish' => 'Finlandia',
		'french' => 'Finlande',
		'italian' => 'Finlandia',
		'portuguese' => 'Finlândia',
		'version' => NULL,
	),
	array( // row #73
		'id' => 248,
		'iso3' => 'ALA',
		'iso2' => 'AX',
		'english' => 'Åland Islands',
		'german' => 'Åland',
		'spanish' => 'Åland',
		'french' => 'Åland',
		'italian' => 'Åland',
		'portuguese' => 'Åland',
		'version' => NULL,
	),
	array( // row #74
		'id' => 250,
		'iso3' => 'FRA',
		'iso2' => 'FR',
		'english' => 'France',
		'german' => 'Frankreich',
		'spanish' => 'Francia',
		'french' => 'France',
		'italian' => 'Francia',
		'portuguese' => 'França',
		'version' => NULL,
	),
	array( // row #75
		'id' => 254,
		'iso3' => 'GUF',
		'iso2' => 'GF',
		'english' => 'French Guiana',
		'german' => 'Französisch-Guayana',
		'spanish' => 'Guayana Francesa',
		'french' => 'Guyane',
		'italian' => 'Guyana Francese',
		'portuguese' => 'Guiana Francesa',
		'version' => NULL,
	),
	array( // row #76
		'id' => 258,
		'iso3' => 'PYF',
		'iso2' => 'PF',
		'english' => 'French Polynesia',
		'german' => 'Französisch-Polynesien',
		'spanish' => 'Polinesia Francesa',
		'french' => 'Polynésie française',
		'italian' => 'Polinesia Francese',
		'portuguese' => 'Polinésia Francesa',
		'version' => NULL,
	),
	array( // row #77
		'id' => 260,
		'iso3' => 'ATF',
		'iso2' => 'TF',
		'english' => 'French Southern Territories',
		'german' => 'Französische Süd- und Antarktisgebiete',
		'spanish' => 'Territorios Australes Franceses',
		'french' => 'Terres australes et antarctiques françaises',
		'italian' => 'Territori Francesi del Sud',
		'portuguese' => 'Terras Austrais e Antárticas Francesas (\'\'TAAF\'\')',
		'version' => NULL,
	),
	array( // row #78
		'id' => 262,
		'iso3' => 'DJI',
		'iso2' => 'DJ',
		'english' => 'Djibouti',
		'german' => 'Dschibuti',
		'spanish' => 'Yibuti',
		'french' => 'Djibouti',
		'italian' => 'Gibuti',
		'portuguese' => 'Djibouti',
		'version' => NULL,
	),
	array( // row #79
		'id' => 266,
		'iso3' => 'GAB',
		'iso2' => 'GA',
		'english' => 'Gabon',
		'german' => 'Gabun',
		'spanish' => 'Gabón',
		'french' => 'Gabon',
		'italian' => 'Gabon',
		'portuguese' => 'Gabão',
		'version' => NULL,
	),
	array( // row #80
		'id' => 268,
		'iso3' => 'GEO',
		'iso2' => 'GE',
		'english' => 'Georgia',
		'german' => 'Georgien',
		'spanish' => 'Georgia',
		'french' => 'Géorgie (pays)',
		'italian' => 'Georgia',
		'portuguese' => 'Geórgia',
		'version' => NULL,
	),
	array( // row #81
		'id' => 270,
		'iso3' => 'GMB',
		'iso2' => 'GM',
		'english' => 'Gambia',
		'german' => 'Gambia',
		'spanish' => 'Gambia',
		'french' => 'Gambie',
		'italian' => 'Gambia',
		'portuguese' => 'Gâmbia',
		'version' => NULL,
	),
	array( // row #82
		'id' => 275,
		'iso3' => 'PSE',
		'iso2' => 'PS',
		'english' => 'Palestinian Territory, Occupied',
		'german' => 'Palästinensische Autonomiegebiete',
		'spanish' => 'Palestina (ANP)',
		'french' => 'Palestine',
		'italian' => 'Territori Palestinesi Occupati',
		'portuguese' => 'Palestina',
		'version' => NULL,
	),
	array( // row #83
		'id' => 276,
		'iso3' => 'DEU',
		'iso2' => 'DE',
		'english' => 'Germany',
		'german' => 'Deutschland',
		'spanish' => 'Alemania',
		'french' => 'Allemagne',
		'italian' => 'Germania',
		'portuguese' => 'Alemanha',
		'version' => NULL,
	),
	array( // row #84
		'id' => 288,
		'iso3' => 'GHA',
		'iso2' => 'GH',
		'english' => 'Ghana',
		'german' => 'Ghana',
		'spanish' => 'Ghana',
		'french' => 'Ghana',
		'italian' => 'Ghana',
		'portuguese' => 'Gana',
		'version' => NULL,
	),
	array( // row #85
		'id' => 292,
		'iso3' => 'GIB',
		'iso2' => 'GI',
		'english' => 'Gibraltar',
		'german' => 'Gibraltar',
		'spanish' => 'Gibraltar',
		'french' => 'Gibraltar',
		'italian' => 'Gibilterra',
		'portuguese' => 'Gibraltar',
		'version' => NULL,
	),
	array( // row #86
		'id' => 296,
		'iso3' => 'KIR',
		'iso2' => 'KI',
		'english' => 'Kiribati',
		'german' => 'Kiribati',
		'spanish' => 'Kiribati',
		'french' => 'Kiribati',
		'italian' => 'Kiribati',
		'portuguese' => 'Kiribati',
		'version' => NULL,
	),
	array( // row #87
		'id' => 300,
		'iso3' => 'GRC',
		'iso2' => 'GR',
		'english' => 'Greece',
		'german' => 'Griechenland',
		'spanish' => 'Grecia',
		'french' => 'Grèce',
		'italian' => 'Grecia',
		'portuguese' => 'Grécia ',
		'version' => NULL,
	),
	array( // row #88
		'id' => 304,
		'iso3' => 'GRL',
		'iso2' => 'GL',
		'english' => 'Greenland',
		'german' => 'Grönland',
		'spanish' => 'Groenlandia',
		'french' => 'Groenland',
		'italian' => 'Groenlandia',
		'portuguese' => 'Gronelândia',
		'version' => NULL,
	),
	array( // row #89
		'id' => 308,
		'iso3' => 'GRD',
		'iso2' => 'GD',
		'english' => 'Grenada',
		'german' => 'Grenada',
		'spanish' => 'Granada',
		'french' => 'Grenade (pays)||GRENADE',
		'italian' => 'Grenada',
		'portuguese' => 'Grenada',
		'version' => NULL,
	),
	array( // row #90
		'id' => 312,
		'iso3' => 'GLP',
		'iso2' => 'GP',
		'english' => 'Guadeloupe[1]',
		'german' => 'Guadeloupe',
		'spanish' => 'Guadalupe',
		'french' => 'Guadeloupe',
		'italian' => 'Guadalupa',
		'portuguese' => 'Guadeloupe',
		'version' => NULL,
	),
	array( // row #91
		'id' => 316,
		'iso3' => 'GUM',
		'iso2' => 'GU',
		'english' => 'Guam',
		'german' => 'Guam',
		'spanish' => 'Guam',
		'french' => 'Guam',
		'italian' => 'Guam',
		'portuguese' => 'Guam',
		'version' => NULL,
	),
	array( // row #92
		'id' => 320,
		'iso3' => 'GTM',
		'iso2' => 'GT',
		'english' => 'Guatemala',
		'german' => 'Guatemala',
		'spanish' => 'Guatemala',
		'french' => 'Guatemala',
		'italian' => 'Guatemala',
		'portuguese' => 'Guatemala',
		'version' => NULL,
	),
	array( // row #93
		'id' => 324,
		'iso3' => 'GIN',
		'iso2' => 'GN',
		'english' => 'Guinea',
		'german' => 'Guinea',
		'spanish' => 'Guinea',
		'french' => 'Guinée',
		'italian' => 'Guinea',
		'portuguese' => 'Guiné-Conacri',
		'version' => NULL,
	),
	array( // row #94
		'id' => 328,
		'iso3' => 'GUY',
		'iso2' => 'GY',
		'english' => 'Guyana',
		'german' => 'Guyana',
		'spanish' => 'Guyana',
		'french' => 'Guyana',
		'italian' => 'Guyana',
		'portuguese' => 'Guiana',
		'version' => NULL,
	),
	array( // row #95
		'id' => 332,
		'iso3' => 'HTI',
		'iso2' => 'HT',
		'english' => 'Haiti',
		'german' => 'Haiti',
		'spanish' => 'Haití',
		'french' => 'Haïti',
		'italian' => 'Haiti',
		'portuguese' => 'Haiti',
		'version' => NULL,
	),
	array( // row #96
		'id' => 334,
		'iso3' => 'HMD',
		'iso2' => 'HM',
		'english' => 'Heard Island and McDonald Islands',
		'german' => 'Heard- und McDonald-Inseln',
		'spanish' => 'Islas Heard y McDonald',
		'french' => 'Île Heard et îles McDonald',
		'italian' => 'Isole Heard e McDonald',
		'portuguese' => 'Ilha Heard e Ilhas McDonald',
		'version' => NULL,
	),
	array( // row #97
		'id' => 336,
		'iso3' => 'VAT',
		'iso2' => 'VA',
		'english' => 'Holy See (Vatican City State)',
		'german' => 'Vatikanstadt',
		'spanish' => 'Ciudad del Vaticano',
		'french' => 'Vatican / (Saint-Siège)',
		'italian' => 'Città del Vaticano',
		'portuguese' => 'Vaticano',
		'version' => NULL,
	),
	array( // row #98
		'id' => 340,
		'iso3' => 'HND',
		'iso2' => 'HN',
		'english' => 'Honduras',
		'german' => 'Honduras',
		'spanish' => 'Honduras',
		'french' => 'Honduras',
		'italian' => 'Honduras',
		'portuguese' => 'Honduras',
		'version' => NULL,
	),
	array( // row #99
		'id' => 344,
		'iso3' => 'HKG',
		'iso2' => 'HK',
		'english' => 'Hong Kong',
		'german' => 'Hongkong',
		'spanish' => 'Hong Kong',
		'french' => 'Hong Kong',
		'italian' => 'Hong Kong',
		'portuguese' => 'Hong Kong',
		'version' => NULL,
	),
	array( // row #100
		'id' => 348,
		'iso3' => 'HUN',
		'iso2' => 'HU',
		'english' => 'Hungary',
		'german' => 'Ungarn',
		'spanish' => 'Hungría',
		'french' => 'Hongrie',
		'italian' => 'Ungheria',
		'portuguese' => 'Hungria',
		'version' => NULL,
	),
	array( // row #101
		'id' => 352,
		'iso3' => 'ISL',
		'iso2' => 'IS',
		'english' => 'Iceland',
		'german' => 'Island',
		'spanish' => 'Islandia',
		'french' => 'Islande',
		'italian' => 'Islanda',
		'portuguese' => 'Islândia',
		'version' => NULL,
	),
	array( // row #102
		'id' => 356,
		'iso3' => 'IND',
		'iso2' => 'IN',
		'english' => 'India',
		'german' => 'Indien',
		'spanish' => 'India',
		'french' => 'Inde',
		'italian' => 'India',
		'portuguese' => 'Índia',
		'version' => NULL,
	),
	array( // row #103
		'id' => 360,
		'iso3' => 'IDN',
		'iso2' => 'ID',
		'english' => 'Indonesia',
		'german' => 'Indonesien',
		'spanish' => 'Indonesia',
		'french' => 'Indonésie',
		'italian' => 'Indonesia',
		'portuguese' => 'Indonésia',
		'version' => NULL,
	),
	array( // row #104
		'id' => 364,
		'iso3' => 'IRN',
		'iso2' => 'IR',
		'english' => 'Iran, Islamic Republic of',
		'german' => 'Iran',
		'spanish' => 'Irán',
		'french' => 'Iran',
		'italian' => 'Iran',
		'portuguese' => 'Irão',
		'version' => NULL,
	),
	array( // row #105
		'id' => 368,
		'iso3' => 'IRQ',
		'iso2' => 'IQ',
		'english' => 'Iraq',
		'german' => 'Irak',
		'spanish' => 'Iraq',
		'french' => 'Irak',
		'italian' => 'Iraq',
		'portuguese' => 'Iraque',
		'version' => NULL,
	),
	array( // row #106
		'id' => 372,
		'iso3' => 'IRL',
		'iso2' => 'IE',
		'english' => 'Ireland',
		'german' => 'Irland',
		'spanish' => 'Irlanda',
		'french' => 'Irlande (pays)||IRLANDE',
		'italian' => 'Eire',
		'portuguese' => 'Irlanda',
		'version' => NULL,
	),
	array( // row #107
		'id' => 376,
		'iso3' => 'ISR',
		'iso2' => 'IL',
		'english' => 'Israel',
		'german' => 'Israel',
		'spanish' => 'Israel',
		'french' => 'Israël',
		'italian' => 'Israele',
		'portuguese' => 'Israel',
		'version' => NULL,
	),
	array( // row #108
		'id' => 380,
		'iso3' => 'ITA',
		'iso2' => 'IT',
		'english' => 'Italy',
		'german' => 'Italien',
		'spanish' => 'Italia',
		'french' => 'Italie',
		'italian' => 'Italia',
		'portuguese' => 'Itália',
		'version' => NULL,
	),
	array( // row #109
		'id' => 384,
		'iso3' => 'CIV',
		'iso2' => 'CI',
		'english' => 'Côte d\'Ivoire',
		'german' => 'Elfenbeinküste',
		'spanish' => 'Costa de Marfil',
		'french' => 'Côte d\'Ivoire ',
		'italian' => 'Costa d\'Avorio',
		'portuguese' => 'Costa do Marfim',
		'version' => NULL,
	),
	array( // row #110
		'id' => 388,
		'iso3' => 'JAM',
		'iso2' => 'JM',
		'english' => 'Jamaica',
		'german' => 'Jamaika',
		'spanish' => 'Jamaica',
		'french' => 'JJamaïque',
		'italian' => 'Giamaica',
		'portuguese' => 'Jamaica',
		'version' => NULL,
	),
	array( // row #111
		'id' => 392,
		'iso3' => 'JPN',
		'iso2' => 'JP',
		'english' => 'Japan',
		'german' => 'Japan',
		'spanish' => 'Japón',
		'french' => 'Japon',
		'italian' => 'Giappone',
		'portuguese' => 'Japão',
		'version' => NULL,
	),
	array( // row #112
		'id' => 398,
		'iso3' => 'KAZ',
		'iso2' => 'KZ',
		'english' => 'Kazakhstan',
		'german' => 'Kasachstan',
		'spanish' => 'Kazajistán',
		'french' => 'Kazakhstan',
		'italian' => 'Kazakistan',
		'portuguese' => 'Cazaquistão',
		'version' => NULL,
	),
	array( // row #113
		'id' => 400,
		'iso3' => 'JOR',
		'iso2' => 'JO',
		'english' => 'Jordan',
		'german' => 'Jordanien',
		'spanish' => 'Jordania',
		'french' => 'Jordanie',
		'italian' => 'Giordania',
		'portuguese' => 'Jordânia',
		'version' => NULL,
	),
	array( // row #114
		'id' => 404,
		'iso3' => 'KEN',
		'iso2' => 'KE',
		'english' => 'Kenya',
		'german' => 'Kenia',
		'spanish' => 'Kenia',
		'french' => 'Kenya',
		'italian' => 'Kenya',
		'portuguese' => 'Quénia',
		'version' => NULL,
	),
	array( // row #115
		'id' => 408,
		'iso3' => 'PRK',
		'iso2' => 'KP',
		'english' => 'Korea, Democratic People\'s Republic of',
		'german' => 'Nordkorea',
		'spanish' => 'Corea del Norte',
		'french' => 'Corée du Nord',
		'italian' => 'Corea del Nord',
		'portuguese' => 'Coreia do Norte',
		'version' => NULL,
	),
	array( // row #116
		'id' => 410,
		'iso3' => 'KOR',
		'iso2' => 'KR',
		'english' => 'Korea, Republic of',
		'german' => 'Südkorea',
		'spanish' => 'Corea del Sur',
		'french' => 'Corée du Sud',
		'italian' => 'Corea del Sud',
		'portuguese' => 'Coreia do Sul',
		'version' => NULL,
	),
	array( // row #117
		'id' => 414,
		'iso3' => 'KWT',
		'iso2' => 'KW',
		'english' => 'Kuwait',
		'german' => 'Kuwait',
		'spanish' => 'Kuwait',
		'french' => 'Koweït',
		'italian' => 'Kuwait',
		'portuguese' => 'Kuwait',
		'version' => NULL,
	),
	array( // row #118
		'id' => 417,
		'iso3' => 'KGZ',
		'iso2' => 'KG',
		'english' => 'Kyrgyzstan',
		'german' => 'Kirgisistan',
		'spanish' => 'Kirguistán',
		'french' => 'Kirghizistan',
		'italian' => 'Kirghizistan',
		'portuguese' => 'Quirguistão',
		'version' => NULL,
	),
	array( // row #119
		'id' => 418,
		'iso3' => 'LAO',
		'iso2' => 'LA',
		'english' => 'Lao People\'s Democratic Republic',
		'german' => 'Laos',
		'spanish' => 'Laos',
		'french' => 'Laos',
		'italian' => 'Laos',
		'portuguese' => 'Laos',
		'version' => NULL,
	),
	array( // row #120
		'id' => 422,
		'iso3' => 'LBN',
		'iso2' => 'LB',
		'english' => 'Lebanon',
		'german' => 'Libanon',
		'spanish' => 'Líbano',
		'french' => 'Liban',
		'italian' => 'Libano',
		'portuguese' => 'Líbano',
		'version' => NULL,
	),
	array( // row #121
		'id' => 426,
		'iso3' => 'LSO',
		'iso2' => 'LS',
		'english' => 'Lesotho',
		'german' => 'Lesotho',
		'spanish' => 'Lesoto',
		'french' => 'Lesotho',
		'italian' => 'Lesotho',
		'portuguese' => 'Lesoto',
		'version' => NULL,
	),
	array( // row #122
		'id' => 428,
		'iso3' => 'LVA',
		'iso2' => 'LV',
		'english' => 'Latvia',
		'german' => 'Lettland',
		'spanish' => 'Letonia',
		'french' => 'Lettonie',
		'italian' => 'Lettonia',
		'portuguese' => 'Letónia',
		'version' => NULL,
	),
	array( // row #123
		'id' => 430,
		'iso3' => 'LBR',
		'iso2' => 'LR',
		'english' => 'Liberia',
		'german' => 'Liberia',
		'spanish' => 'Liberia',
		'french' => 'Libéria',
		'italian' => 'Liberia',
		'portuguese' => 'Libéria',
		'version' => NULL,
	),
	array( // row #124
		'id' => 434,
		'iso3' => 'LBY',
		'iso2' => 'LY',
		'english' => 'Libyan Arab Jamahiriya',
		'german' => 'Libyen',
		'spanish' => 'Libia',
		'french' => 'Libye',
		'italian' => 'Libia',
		'portuguese' => 'Líbia',
		'version' => NULL,
	),
	array( // row #125
		'id' => 438,
		'iso3' => 'LIE',
		'iso2' => 'LI',
		'english' => 'Liechtenstein',
		'german' => 'Liechtenstein',
		'spanish' => 'Liechtenstein',
		'french' => 'Liechtenstein',
		'italian' => 'Liechtenstein',
		'portuguese' => 'Liechtenstein',
		'version' => NULL,
	),
	array( // row #126
		'id' => 440,
		'iso3' => 'LTU',
		'iso2' => 'LT',
		'english' => 'Lithuania',
		'german' => 'Litauen',
		'spanish' => 'Lituania',
		'french' => 'Lituanie',
		'italian' => 'Lituania',
		'portuguese' => 'Lituânia',
		'version' => NULL,
	),
	array( // row #127
		'id' => 442,
		'iso3' => 'LUX',
		'iso2' => 'LU',
		'english' => 'Luxembourg',
		'german' => 'Luxemburg',
		'spanish' => 'Luxemburgo',
		'french' => 'Luxembourg (pays)',
		'italian' => 'Lussemburgo',
		'portuguese' => 'Luxemburgo',
		'version' => NULL,
	),
	array( // row #128
		'id' => 446,
		'iso3' => 'MAC',
		'iso2' => 'MO',
		'english' => 'Macao',
		'german' => 'Macao',
		'spanish' => 'Macao',
		'french' => 'Macao',
		'italian' => 'Macao',
		'portuguese' => 'Macau',
		'version' => NULL,
	),
	array( // row #129
		'id' => 450,
		'iso3' => 'MDG',
		'iso2' => 'MG',
		'english' => 'Madagascar',
		'german' => 'Madagaskar',
		'spanish' => 'Madagascar',
		'french' => 'Madagascar',
		'italian' => 'Madagascar',
		'portuguese' => 'Madagáscar',
		'version' => NULL,
	),
	array( // row #130
		'id' => 454,
		'iso3' => 'MWI',
		'iso2' => 'MW',
		'english' => 'Malawi',
		'german' => 'Malawi',
		'spanish' => 'Malawi',
		'french' => 'Malawi',
		'italian' => 'Malawi',
		'portuguese' => 'Malawi',
		'version' => NULL,
	),
	array( // row #131
		'id' => 458,
		'iso3' => 'MYS',
		'iso2' => 'MY',
		'english' => 'Malaysia',
		'german' => 'Malaysia',
		'spanish' => 'Malasia',
		'french' => 'Malaisie',
		'italian' => 'Malesia',
		'portuguese' => 'Malásia',
		'version' => NULL,
	),
	array( // row #132
		'id' => 462,
		'iso3' => 'MDV',
		'iso2' => 'MV',
		'english' => 'Maldives',
		'german' => 'Malediven',
		'spanish' => 'Maldivas',
		'french' => 'Maldives',
		'italian' => 'Maldive',
		'portuguese' => 'Maldivas',
		'version' => NULL,
	),
	array( // row #133
		'id' => 466,
		'iso3' => 'MLI',
		'iso2' => 'ML',
		'english' => 'Mali',
		'german' => 'Mali',
		'spanish' => 'Malí',
		'french' => 'Mali',
		'italian' => 'Mali',
		'portuguese' => 'Mali',
		'version' => NULL,
	),
	array( // row #134
		'id' => 470,
		'iso3' => 'MLT',
		'iso2' => 'MT',
		'english' => 'Malta',
		'german' => 'Malta',
		'spanish' => 'Malta',
		'french' => 'Malte',
		'italian' => 'Malta',
		'portuguese' => 'Malta',
		'version' => NULL,
	),
	array( // row #135
		'id' => 474,
		'iso3' => 'MTQ',
		'iso2' => 'MQ',
		'english' => 'Martinique',
		'german' => 'Martinique',
		'spanish' => 'Martinica',
		'french' => 'Martinique',
		'italian' => 'Martinica',
		'portuguese' => 'Martinica',
		'version' => NULL,
	),
	array( // row #136
		'id' => 478,
		'iso3' => 'MRT',
		'iso2' => 'MR',
		'english' => 'Mauritania',
		'german' => 'Mauretanien',
		'spanish' => 'Mauritania',
		'french' => 'Mauritanie',
		'italian' => 'Mauritania',
		'portuguese' => 'Mauritânia',
		'version' => NULL,
	),
	array( // row #137
		'id' => 480,
		'iso3' => 'MUS',
		'iso2' => 'MU',
		'english' => 'Mauritius',
		'german' => 'Mauritius',
		'spanish' => 'Mauricio',
		'french' => 'Maurice (pays)',
		'italian' => 'Mauritius',
		'portuguese' => 'Maurícia',
		'version' => NULL,
	),
	array( // row #138
		'id' => 484,
		'iso3' => 'MEX',
		'iso2' => 'MX',
		'english' => 'Mexico',
		'german' => 'Mexiko',
		'spanish' => 'México',
		'french' => 'Mexique',
		'italian' => 'Messico',
		'portuguese' => 'México',
		'version' => NULL,
	),
	array( // row #139
		'id' => 492,
		'iso3' => 'MCO',
		'iso2' => 'MC',
		'english' => 'Monaco',
		'german' => 'Monaco',
		'spanish' => 'Mónaco',
		'french' => 'Monaco',
		'italian' => 'Monaco',
		'portuguese' => 'Mónaco',
		'version' => NULL,
	),
	array( // row #140
		'id' => 496,
		'iso3' => 'MNG',
		'iso2' => 'MN',
		'english' => 'Mongolia',
		'german' => 'Mongolei',
		'spanish' => 'Mongolia',
		'french' => 'Mongolie',
		'italian' => 'Mongolia',
		'portuguese' => 'Mongólia',
		'version' => NULL,
	),
	array( // row #141
		'id' => 498,
		'iso3' => 'MDA',
		'iso2' => 'MD',
		'english' => 'Moldova, Republic of',
		'german' => 'Moldawien',
		'spanish' => 'Moldavia',
		'french' => 'Moldavie',
		'italian' => 'Moldavia',
		'portuguese' => 'Moldávia',
		'version' => NULL,
	),
	array( // row #142
		'id' => 499,
		'iso3' => 'MNE',
		'iso2' => 'ME',
		'english' => 'Montenegro',
		'german' => 'Montenegro',
		'spanish' => 'Montenegro',
		'french' => 'Monténégro',
		'italian' => 'Montenegro',
		'portuguese' => 'Montenegro',
		'version' => NULL,
	),
	array( // row #143
		'id' => 500,
		'iso3' => 'MSR',
		'iso2' => 'MS',
		'english' => 'Montserrat',
		'german' => 'Montserrat',
		'spanish' => 'Montserrat',
		'french' => 'Montserrat',
		'italian' => 'Montserrat',
		'portuguese' => 'Montserrat',
		'version' => NULL,
	),
	array( // row #144
		'id' => 504,
		'iso3' => 'MAR',
		'iso2' => 'MA',
		'english' => 'Morocco',
		'german' => 'Marokko',
		'spanish' => 'Marruecos',
		'french' => 'Maroc',
		'italian' => 'Marocco',
		'portuguese' => 'Marrocos',
		'version' => NULL,
	),
	array( // row #145
		'id' => 508,
		'iso3' => 'MOZ',
		'iso2' => 'MZ',
		'english' => 'Mozambique',
		'german' => 'Mosambik',
		'spanish' => 'Mozambique',
		'french' => 'Mozambique',
		'italian' => 'Mozambico',
		'portuguese' => 'Moçambique',
		'version' => NULL,
	),
	array( // row #146
		'id' => 512,
		'iso3' => 'OMN',
		'iso2' => 'OM',
		'english' => 'Oman',
		'german' => 'Oman',
		'spanish' => 'Omán',
		'french' => 'Oman',
		'italian' => 'Oman',
		'portuguese' => 'Oman',
		'version' => NULL,
	),
	array( // row #147
		'id' => 516,
		'iso3' => 'NAM',
		'iso2' => 'NA',
		'english' => 'Namibia',
		'german' => 'Namibia',
		'spanish' => 'Namibia',
		'french' => 'Namibie',
		'italian' => 'Namibia',
		'portuguese' => 'Namíbia',
		'version' => NULL,
	),
	array( // row #148
		'id' => 520,
		'iso3' => 'NRU',
		'iso2' => 'NR',
		'english' => 'Nauru',
		'german' => 'Nauru',
		'spanish' => 'Nauru',
		'french' => 'Nauru',
		'italian' => 'Nauru',
		'portuguese' => 'Nauru',
		'version' => NULL,
	),
	array( // row #149
		'id' => 524,
		'iso3' => 'NPL',
		'iso2' => 'NP',
		'english' => 'Nepal',
		'german' => 'Nepal',
		'spanish' => 'Nepal',
		'french' => 'Népal',
		'italian' => 'Nepal',
		'portuguese' => 'Nepal',
		'version' => NULL,
	),
	array( // row #150
		'id' => 528,
		'iso3' => 'NLD',
		'iso2' => 'NL',
		'english' => 'Netherlands',
		'german' => 'Niederlande',
		'spanish' => 'Países Bajos',
		'french' => 'Pays-Bas',
		'italian' => 'Paesi Bassi',
		'portuguese' => 'Países Baixos (\'\'Holanda\'\')',
		'version' => NULL,
	),
	array( // row #151
		'id' => 530,
		'iso3' => 'ANT',
		'iso2' => 'AN',
		'english' => 'Netherlands Antilles',
		'german' => 'Niederländische Antillen',
		'spanish' => 'Antillas Neerlandesas',
		'french' => 'Antilles néerlandaises',
		'italian' => 'Antille Olandesi',
		'portuguese' => 'Antilhas Holandesas',
		'version' => NULL,
	),
	array( // row #152
		'id' => 533,
		'iso3' => 'ABW',
		'iso2' => 'AW',
		'english' => 'Aruba',
		'german' => 'Aruba',
		'spanish' => 'Aruba',
		'french' => 'Aruba',
		'italian' => 'Aruba',
		'portuguese' => 'Aruba',
		'version' => NULL,
	),
	array( // row #153
		'id' => 540,
		'iso3' => 'NCL',
		'iso2' => 'NC',
		'english' => 'New Caledonia',
		'german' => 'Neukaledonien',
		'spanish' => 'Nueva Caledonia',
		'french' => 'Nouvelle-Calédonie',
		'italian' => 'Nuova Caledonia',
		'portuguese' => 'Nova Caledónia',
		'version' => NULL,
	),
	array( // row #154
		'id' => 548,
		'iso3' => 'VUT',
		'iso2' => 'VU',
		'english' => 'Vanuatu',
		'german' => 'Vanuatu',
		'spanish' => 'Vanuatu',
		'french' => 'Vanuatu',
		'italian' => 'Vanuatu',
		'portuguese' => 'Vanuatu',
		'version' => NULL,
	),
	array( // row #155
		'id' => 554,
		'iso3' => 'NZL',
		'iso2' => 'NZ',
		'english' => 'New Zealand',
		'german' => 'Neuseeland',
		'spanish' => 'Nueva Zelanda',
		'french' => 'Nouvelle-Zélande',
		'italian' => 'Nuova Zelanda',
		'portuguese' => 'Nova Zelândia (\'\'Aotearoa\'\')',
		'version' => NULL,
	),
	array( // row #156
		'id' => 558,
		'iso3' => 'NIC',
		'iso2' => 'NI',
		'english' => 'Nicaragua',
		'german' => 'Nicaragua',
		'spanish' => 'Nicaragua',
		'french' => 'Nicaragua',
		'italian' => 'Nicaragua',
		'portuguese' => 'Nicarágua',
		'version' => NULL,
	),
	array( // row #157
		'id' => 562,
		'iso3' => 'NER',
		'iso2' => 'NE',
		'english' => 'Niger',
		'german' => 'Niger',
		'spanish' => 'Níger',
		'french' => 'Niger',
		'italian' => 'Niger',
		'portuguese' => 'Níger',
		'version' => NULL,
	),
	array( // row #158
		'id' => 566,
		'iso3' => 'NGA',
		'iso2' => 'NG',
		'english' => 'Nigeria',
		'german' => 'Nigeria',
		'spanish' => 'Nigeria',
		'french' => 'Nigeria',
		'italian' => 'Nigeria',
		'portuguese' => 'Nigéria',
		'version' => NULL,
	),
	array( // row #159
		'id' => 570,
		'iso3' => 'NIU',
		'iso2' => 'NU',
		'english' => 'Niue',
		'german' => 'Niue',
		'spanish' => 'Niue',
		'french' => 'Niué',
		'italian' => 'Niue',
		'portuguese' => 'Niue',
		'version' => NULL,
	),
	array( // row #160
		'id' => 574,
		'iso3' => 'NFK',
		'iso2' => 'NF',
		'english' => 'Norfolk Island',
		'german' => 'Norfolkinsel',
		'spanish' => 'Norfolk',
		'french' => 'Norfolk',
		'italian' => 'Isola Norfolk',
		'portuguese' => 'Ilha Norfolk',
		'version' => NULL,
	),
	array( // row #161
		'id' => 578,
		'iso3' => 'NOR',
		'iso2' => 'NO',
		'english' => 'Norway',
		'german' => 'Norwegen',
		'spanish' => 'Noruega',
		'french' => 'Norvège',
		'italian' => 'Norvegia',
		'portuguese' => 'Noruega',
		'version' => NULL,
	),
	array( // row #162
		'id' => 580,
		'iso3' => 'MNP',
		'iso2' => 'MP',
		'english' => 'Northern Mariana Islands',
		'german' => 'Nördliche Marianen',
		'spanish' => 'Islas Marianas del Norte',
		'french' => 'Îles Mariannes du Nord',
		'italian' => 'Isole Marianne Settentrionali',
		'portuguese' => 'Marianas Setentrionais',
		'version' => NULL,
	),
	array( // row #163
		'id' => 581,
		'iso3' => 'UMI',
		'iso2' => 'UM',
		'english' => 'United States Minor Outlying Islands',
		'german' => 'United States Minor Outlying Islands',
		'spanish' => 'Islas ultramarinas de Estados Unidos',
		'french' => 'Îles mineures éloignées des États-Unis',
		'italian' => 'Isole Minori degli Stati Uniti d\'America',
		'portuguese' => 'Ilhas Menores Distantes dos Estados Unidos',
		'version' => NULL,
	),
	array( // row #164
		'id' => 583,
		'iso3' => 'FSM',
		'iso2' => 'FM',
		'english' => 'Micronesia, Federated States of',
		'german' => 'Mikronesien',
		'spanish' => 'Micronesia',
		'french' => 'Micronésie (pays)',
		'italian' => 'Stati Federati della Micronesia',
		'portuguese' => 'Estados Federados da Micronésia',
		'version' => NULL,
	),
	array( // row #165
		'id' => 584,
		'iso3' => 'MHL',
		'iso2' => 'MH',
		'english' => 'Marshall Islands',
		'german' => 'Marshallinseln',
		'spanish' => 'Islas Marshall',
		'french' => 'Marshall (pays)',
		'italian' => 'Isole Marshall',
		'portuguese' => 'Ilhas Marshall',
		'version' => NULL,
	),
	array( // row #166
		'id' => 585,
		'iso3' => 'PLW',
		'iso2' => 'PW',
		'english' => 'Palau',
		'german' => 'Palau',
		'spanish' => 'Palaos',
		'french' => 'Palaos',
		'italian' => 'Palau',
		'portuguese' => 'Palau',
		'version' => NULL,
	),
	array( // row #167
		'id' => 586,
		'iso3' => 'PAK',
		'iso2' => 'PK',
		'english' => 'Pakistan',
		'german' => 'Pakistan',
		'spanish' => 'Pakistán',
		'french' => 'Pakistan',
		'italian' => 'Pakistan',
		'portuguese' => 'Paquistão',
		'version' => NULL,
	),
	array( // row #168
		'id' => 591,
		'iso3' => 'PAN',
		'iso2' => 'PA',
		'english' => 'Panama',
		'german' => 'Panama',
		'spanish' => 'Panamá',
		'french' => 'Panamá',
		'italian' => 'Panamá',
		'portuguese' => 'Panamá',
		'version' => NULL,
	),
	array( // row #169
		'id' => 598,
		'iso3' => 'PNG',
		'iso2' => 'PG',
		'english' => 'Papua New Guinea',
		'german' => 'Papua-Neuguinea',
		'spanish' => 'Papúa Nueva Guinea',
		'french' => 'Papouasie-Nouvelle-Guinée',
		'italian' => 'Papua Nuova Guinea',
		'portuguese' => 'Papua-Nova Guiné',
		'version' => NULL,
	),
	array( // row #170
		'id' => 600,
		'iso3' => 'PRY',
		'iso2' => 'PY',
		'english' => 'Paraguay',
		'german' => 'Paraguay',
		'spanish' => 'Paraguay',
		'french' => 'Paraguay',
		'italian' => 'Paraguay',
		'portuguese' => 'Paraguai',
		'version' => NULL,
	),
	array( // row #171
		'id' => 604,
		'iso3' => 'PER',
		'iso2' => 'PE',
		'english' => 'Peru',
		'german' => 'Peru',
		'spanish' => 'Perú',
		'french' => 'Pérou',
		'italian' => 'Perù',
		'portuguese' => 'Peru',
		'version' => NULL,
	),
	array( // row #172
		'id' => 608,
		'iso3' => 'PHL',
		'iso2' => 'PH',
		'english' => 'Philippines',
		'german' => 'Philippinen',
		'spanish' => 'Filipinas',
		'french' => 'Philippines',
		'italian' => 'Filippine',
		'portuguese' => 'Filipinas',
		'version' => NULL,
	),
	array( // row #173
		'id' => 612,
		'iso3' => 'PCN',
		'iso2' => 'PN',
		'english' => 'Pitcairn',
		'german' => 'Pitcairninseln',
		'spanish' => 'Islas Pitcairn',
		'french' => 'Pitcairn',
		'italian' => 'Pitcairn',
		'portuguese' => 'Pitcairn',
		'version' => NULL,
	),
	array( // row #174
		'id' => 616,
		'iso3' => 'POL',
		'iso2' => 'PL',
		'english' => 'Poland',
		'german' => 'Polen',
		'spanish' => 'Polonia',
		'french' => 'Pologne',
		'italian' => 'Polonia',
		'portuguese' => 'Polónia',
		'version' => NULL,
	),
	array( // row #175
		'id' => 620,
		'iso3' => 'PRT',
		'iso2' => 'PT',
		'english' => 'Portugal',
		'german' => 'Portugal',
		'spanish' => 'Portugal',
		'french' => 'Portugal',
		'italian' => 'Portogallo',
		'portuguese' => 'Portugal',
		'version' => NULL,
	),
	array( // row #176
		'id' => 624,
		'iso3' => 'GNB',
		'iso2' => 'GW',
		'english' => 'Guinea-Bissau',
		'german' => 'Guinea-Bissau',
		'spanish' => 'Guinea-Bissau',
		'french' => 'Guinée-Bissau',
		'italian' => 'Guinea-Bissau',
		'portuguese' => 'Guiné-Bissau',
		'version' => NULL,
	),
	array( // row #177
		'id' => 626,
		'iso3' => 'TLS',
		'iso2' => 'TL',
		'english' => 'Timor-Leste',
		'german' => 'Osttimor',
		'spanish' => 'Timor Oriental',
		'french' => 'Timor oriental',
		'italian' => 'Timor Est',
		'portuguese' => 'Timor-Leste',
		'version' => NULL,
	),
	array( // row #178
		'id' => 630,
		'iso3' => 'PRI',
		'iso2' => 'PR',
		'english' => 'Puerto Rico',
		'german' => 'Puerto Rico',
		'spanish' => 'Puerto Rico',
		'french' => 'Porto Rico',
		'italian' => 'Porto Rico',
		'portuguese' => 'Porto Rico',
		'version' => NULL,
	),
	array( // row #179
		'id' => 634,
		'iso3' => 'QAT',
		'iso2' => 'QA',
		'english' => 'Qatar',
		'german' => 'Katar',
		'spanish' => 'Qatar',
		'french' => 'Qatar',
		'italian' => 'Qatar',
		'portuguese' => 'Qatar',
		'version' => NULL,
	),
	array( // row #180
		'id' => 638,
		'iso3' => 'REU',
		'iso2' => 'RE',
		'english' => 'Réunion',
		'german' => 'Reunion',
		'spanish' => 'Reunión',
		'french' => 'La Réunion',
		'italian' => 'Reunion',
		'portuguese' => 'Reunião',
		'version' => NULL,
	),
	array( // row #181
		'id' => 642,
		'iso3' => 'ROU',
		'iso2' => 'RO',
		'english' => 'Romania',
		'german' => 'Rumänien',
		'spanish' => 'Rumania',
		'french' => 'Roumanie',
		'italian' => 'Romania',
		'portuguese' => 'Roménia',
		'version' => NULL,
	),
	array( // row #182
		'id' => 643,
		'iso3' => 'RUS',
		'iso2' => 'RU',
		'english' => 'Russian Federation',
		'german' => 'Russische Föderation',
		'spanish' => 'Federación Rusa',
		'french' => 'Fédération de Russie',
		'italian' => 'Federazione Russa',
		'portuguese' => 'Federação da Rússia',
		'version' => NULL,
	),
	array( // row #183
		'id' => 646,
		'iso3' => 'RWA',
		'iso2' => 'RW',
		'english' => 'Rwanda',
		'german' => 'Ruanda',
		'spanish' => 'Ruanda',
		'french' => 'Rwanda',
		'italian' => 'Ruanda',
		'portuguese' => 'Ruanda',
		'version' => NULL,
	),
	array( // row #184
		'id' => 654,
		'iso3' => 'SHN',
		'iso2' => 'SH',
		'english' => 'Saint Helena',
		'german' => 'St. Helena',
		'spanish' => 'Santa Helena',
		'french' => 'Sainte-Hélène (territoire)',
		'italian' => 'Sant\'Elena',
		'portuguese' => 'Santa Helena',
		'version' => NULL,
	),
	array( // row #185
		'id' => 659,
		'iso3' => 'KNA',
		'iso2' => 'KN',
		'english' => 'Saint Kitts and Nevis',
		'german' => 'St. Kitts und Nevis',
		'spanish' => 'San Cristóbal y Nieves',
		'french' => 'Saint-Christophe-et-Niévès',
		'italian' => 'Saint Kitts e Nevis',
		'portuguese' => 'São Cristóvão e Névis',
		'version' => NULL,
	),
	array( // row #186
		'id' => 660,
		'iso3' => 'AIA',
		'iso2' => 'AI',
		'english' => 'Anguilla',
		'german' => 'Anguilla',
		'spanish' => 'Anguila',
		'french' => 'Anguilla',
		'italian' => 'Anguilla',
		'portuguese' => 'Anguilla',
		'version' => NULL,
	),
	array( // row #187
		'id' => 662,
		'iso3' => 'LCA',
		'iso2' => 'LC',
		'english' => 'Saint Lucia',
		'german' => 'St. Lucia',
		'spanish' => 'Santa Lucía',
		'french' => 'Sainte-Lucie',
		'italian' => 'Santa Lucia',
		'portuguese' => 'Santa Lúcia',
		'version' => NULL,
	),
	array( // row #188
		'id' => 666,
		'iso3' => 'SPM',
		'iso2' => 'PM',
		'english' => 'Saint Pierre and Miquelon',
		'german' => 'Saint-Pierre und Miquelon',
		'spanish' => 'San Pedro y Miquelón',
		'french' => 'Saint-Pierre-et-Miquelon',
		'italian' => 'Saint Pierre e Miquelon',
		'portuguese' => 'Saint Pierre et Miquelon',
		'version' => NULL,
	),
	array( // row #189
		'id' => 670,
		'iso3' => 'VCT',
		'iso2' => 'VC',
		'english' => 'Saint Vincent and the Grenadines',
		'german' => 'St. Vincent und die Grenadinen',
		'spanish' => 'San Vicente y las Granadinas',
		'french' => 'Saint-Vincent-et-les Grenadines',
		'italian' => 'Saint Vincent e Grenadine',
		'portuguese' => 'São Vicente e Granadinas',
		'version' => NULL,
	),
	array( // row #190
		'id' => 674,
		'iso3' => 'SMR',
		'iso2' => 'SM',
		'english' => 'San Marino',
		'german' => 'San Marino',
		'spanish' => 'San Marino',
		'french' => 'Saint-Marin',
		'italian' => 'San Marino',
		'portuguese' => 'San Marino',
		'version' => NULL,
	),
	array( // row #191
		'id' => 678,
		'iso3' => 'STP',
		'iso2' => 'ST',
		'english' => 'Sao Tome and Principe',
		'german' => 'São Tomé und Príncipe',
		'spanish' => 'Santo Tomé y Príncipe',
		'french' => 'São Tomé-et-Principe',
		'italian' => 'Sao Tome e Principe',
		'portuguese' => 'São Tomé e Príncipe',
		'version' => NULL,
	),
	array( // row #192
		'id' => 682,
		'iso3' => 'SAU',
		'iso2' => 'SA',
		'english' => 'Saudi Arabia',
		'german' => 'Saudi-Arabien',
		'spanish' => 'Arabia Saudita',
		'french' => 'Arabie saoudite',
		'italian' => 'Arabia Saudita',
		'portuguese' => 'Arábia Saudita',
		'version' => NULL,
	),
	array( // row #193
		'id' => 686,
		'iso3' => 'SEN',
		'iso2' => 'SN',
		'english' => 'Senegal',
		'german' => 'Senegal',
		'spanish' => 'Senegal',
		'french' => 'Sénégal',
		'italian' => 'Senegal',
		'portuguese' => 'Senegal',
		'version' => NULL,
	),
	array( // row #194
		'id' => 688,
		'iso3' => 'SRB',
		'iso2' => 'RS',
		'english' => 'Serbia',
		'german' => 'Serbien',
		'spanish' => 'Serbia',
		'french' => 'Serbie',
		'italian' => 'Serbia[1]',
		'portuguese' => 'Sérvia',
		'version' => NULL,
	),
	array( // row #195
		'id' => 690,
		'iso3' => 'SYC',
		'iso2' => 'SC',
		'english' => 'Seychelles',
		'german' => 'Seychellen',
		'spanish' => 'Seychelles',
		'french' => 'Seychelles',
		'italian' => 'Seychelles',
		'portuguese' => 'Seychelles',
		'version' => NULL,
	),
	array( // row #196
		'id' => 694,
		'iso3' => 'SLE',
		'iso2' => 'SL',
		'english' => 'Sierra Leone',
		'german' => 'Sierra Leone',
		'spanish' => 'Sierra Leona',
		'french' => 'Sierra Leone',
		'italian' => 'Sierra Leone',
		'portuguese' => 'Serra Leoa',
		'version' => NULL,
	),
	array( // row #197
		'id' => 702,
		'iso3' => 'SGP',
		'iso2' => 'SG',
		'english' => 'Singapore',
		'german' => 'Singapur',
		'spanish' => 'Singapur',
		'french' => 'Singapour',
		'italian' => 'Singapore',
		'portuguese' => 'Singapura',
		'version' => NULL,
	),
	array( // row #198
		'id' => 703,
		'iso3' => 'SVK',
		'iso2' => 'SK',
		'english' => 'Slovakia',
		'german' => 'Slowakei',
		'spanish' => 'Eslovaquia',
		'french' => 'Slovaquie',
		'italian' => 'Slovacchia',
		'portuguese' => 'Eslováquia',
		'version' => NULL,
	),
	array( // row #199
		'id' => 704,
		'iso3' => 'VNM',
		'iso2' => 'VN',
		'english' => 'Viet Nam',
		'german' => 'Vietnam',
		'spanish' => 'Vietnam',
		'french' => 'Viêt Nam',
		'italian' => 'Vietnam',
		'portuguese' => 'Vietname',
		'version' => NULL,
	),
	array( // row #200
		'id' => 705,
		'iso3' => 'SVN',
		'iso2' => 'SI',
		'english' => 'Slovenia',
		'german' => 'Slowenien',
		'spanish' => 'Eslovenia',
		'french' => 'Slovénie',
		'italian' => 'Slovenia',
		'portuguese' => 'Eslovénia',
		'version' => NULL,
	),
	array( // row #201
		'id' => 706,
		'iso3' => 'SOM',
		'iso2' => 'SO',
		'english' => 'Somalia',
		'german' => 'Somalia',
		'spanish' => 'Somalia',
		'french' => 'Somalie',
		'italian' => 'Somalia',
		'portuguese' => 'Somália',
		'version' => NULL,
	),
	array( // row #202
		'id' => 710,
		'iso3' => 'ZAF',
		'iso2' => 'ZA',
		'english' => 'South Africa',
		'german' => 'Südafrika',
		'spanish' => 'Sudáfrica',
		'french' => 'Afrique du Sud',
		'italian' => 'Sudafrica',
		'portuguese' => 'África do Sul',
		'version' => NULL,
	),
	array( // row #203
		'id' => 716,
		'iso3' => 'ZWE',
		'iso2' => 'ZW',
		'english' => 'Zimbabwe',
		'german' => 'Simbabwe',
		'spanish' => 'Zimbabue',
		'french' => 'Zimbabwe',
		'italian' => 'Zimbabwe',
		'portuguese' => 'Zimbabwe',
		'version' => NULL,
	),
	array( // row #204
		'id' => 724,
		'iso3' => 'ESP',
		'iso2' => 'ES',
		'english' => 'Spain',
		'german' => 'Spanien',
		'spanish' => 'España(Ceuta y Melilla)',
		'french' => 'Espagne',
		'italian' => 'Spagna',
		'portuguese' => 'Espanha',
		'version' => NULL,
	),
	array( // row #205
		'id' => 732,
		'iso3' => 'ESH',
		'iso2' => 'EH',
		'english' => 'Western Sahara',
		'german' => 'Westsahara',
		'spanish' => 'Sahara Occidental',
		'french' => 'Sahara occidental',
		'italian' => 'Sahara Occidentale',
		'portuguese' => 'Saara Ocidental',
		'version' => NULL,
	),
	array( // row #206
		'id' => 736,
		'iso3' => 'SDN',
		'iso2' => 'SD',
		'english' => 'Sudan',
		'german' => 'Sudan',
		'spanish' => 'Sudán',
		'french' => 'Soudan',
		'italian' => 'Sudan',
		'portuguese' => 'Sudão',
		'version' => NULL,
	),
	array( // row #207
		'id' => 740,
		'iso3' => 'SUR',
		'iso2' => 'SR',
		'english' => 'Suriname',
		'german' => 'Suriname',
		'spanish' => 'Surinam',
		'french' => 'Suriname',
		'italian' => 'Suriname',
		'portuguese' => 'Suriname',
		'version' => NULL,
	),
	array( // row #208
		'id' => 744,
		'iso3' => 'SJM',
		'iso2' => 'SJ',
		'english' => 'Svalbard and Jan Mayen',
		'german' => 'Svalbard und Jan Mayen',
		'spanish' => 'Svalbard y Jan Mayen',
		'french' => 'Svalbard et île Jan Mayen',
		'italian' => 'Svalbard e Jan Mayen',
		'portuguese' => 'Svalbard e Jan Mayen',
		'version' => NULL,
	),
	array( // row #209
		'id' => 748,
		'iso3' => 'SWZ',
		'iso2' => 'SZ',
		'english' => 'Swaziland',
		'german' => 'Swasiland',
		'spanish' => 'Suazilandia',
		'french' => 'Swaziland',
		'italian' => 'Swaziland',
		'portuguese' => 'Suazilândia',
		'version' => NULL,
	),
	array( // row #210
		'id' => 752,
		'iso3' => 'SWE',
		'iso2' => 'SE',
		'english' => 'Sweden',
		'german' => 'Schweden',
		'spanish' => 'Suecia',
		'french' => 'Suède',
		'italian' => 'Svezia',
		'portuguese' => 'Suécia',
		'version' => NULL,
	),
	array( // row #211
		'id' => 756,
		'iso3' => 'CHE',
		'iso2' => 'CH',
		'english' => 'Switzerland',
		'german' => 'Schweiz',
		'spanish' => 'Suiza',
		'french' => 'Suisse',
		'italian' => 'Svizzera',
		'portuguese' => 'Suíça',
		'version' => NULL,
	),
	array( // row #212
		'id' => 760,
		'iso3' => 'SYR',
		'iso2' => 'SY',
		'english' => 'Syrian Arab Republic',
		'german' => 'Syrien',
		'spanish' => 'Siria',
		'french' => 'Syrie',
		'italian' => 'Siria',
		'portuguese' => 'Síria',
		'version' => NULL,
	),
	array( // row #213
		'id' => 762,
		'iso3' => 'TJK',
		'iso2' => 'TJ',
		'english' => 'Tajikistan',
		'german' => 'Tadschikistan',
		'spanish' => 'Tayikistán',
		'french' => 'Tadjikistan',
		'italian' => 'Tagikistan',
		'portuguese' => 'Tajiquistão',
		'version' => NULL,
	),
	array( // row #214
		'id' => 764,
		'iso3' => 'THA',
		'iso2' => 'TH',
		'english' => 'Thailand',
		'german' => 'Thailand',
		'spanish' => 'Tailandia',
		'french' => 'Thaïlande',
		'italian' => 'Thailandia',
		'portuguese' => 'Tailândia',
		'version' => NULL,
	),
	array( // row #215
		'id' => 768,
		'iso3' => 'TGO',
		'iso2' => 'TG',
		'english' => 'Togo',
		'german' => 'Togo',
		'spanish' => 'Togo',
		'french' => 'Togo',
		'italian' => 'Togo',
		'portuguese' => 'Togo',
		'version' => NULL,
	),
	array( // row #216
		'id' => 772,
		'iso3' => 'TKL',
		'iso2' => 'TK',
		'english' => 'Tokelau',
		'german' => 'Tokelau',
		'spanish' => 'Tokelau',
		'french' => 'Tokelau',
		'italian' => 'Tokelau',
		'portuguese' => 'Toquelau',
		'version' => NULL,
	),
	array( // row #217
		'id' => 776,
		'iso3' => 'TON',
		'iso2' => 'TO',
		'english' => 'Tonga',
		'german' => 'Tonga',
		'spanish' => 'Tonga',
		'french' => 'Tonga',
		'italian' => 'Tonga',
		'portuguese' => 'Tonga',
		'version' => NULL,
	),
	array( // row #218
		'id' => 780,
		'iso3' => 'TTO',
		'iso2' => 'TT',
		'english' => 'Trinidad and Tobago',
		'german' => 'Trinidad und Tobago',
		'spanish' => 'Trinidad y Tobago',
		'french' => 'Trinité-et-Tobago',
		'italian' => 'Trinidad e Tobago',
		'portuguese' => 'Trindade e Tobago',
		'version' => NULL,
	),
	array( // row #219
		'id' => 784,
		'iso3' => 'ARE',
		'iso2' => 'AE',
		'english' => 'United Arab Emirates',
		'german' => 'Vereinigte Arabische Emirate',
		'spanish' => 'Emiratos Árabes Unidos',
		'french' => 'Émirats arabes unis',
		'italian' => 'Emirati Arabi Uniti',
		'portuguese' => 'Emiratos Árabes Unidos',
		'version' => NULL,
	),
	array( // row #220
		'id' => 788,
		'iso3' => 'TUN',
		'iso2' => 'TN',
		'english' => 'Tunisia',
		'german' => 'Tunesien',
		'spanish' => 'Túnez',
		'french' => 'Tunisie',
		'italian' => 'Tunisia',
		'portuguese' => 'Tunísia',
		'version' => NULL,
	),
	array( // row #221
		'id' => 792,
		'iso3' => 'TUR',
		'iso2' => 'TR',
		'english' => 'Turkey',
		'german' => 'Türkei',
		'spanish' => 'Turquía',
		'french' => 'Turquie',
		'italian' => 'Turchia',
		'portuguese' => 'Turquia',
		'version' => NULL,
	),
	array( // row #222
		'id' => 795,
		'iso3' => 'TKM',
		'iso2' => 'TM',
		'english' => 'Turkmenistan',
		'german' => 'Turkmenistan',
		'spanish' => 'Turkmenistán',
		'french' => 'Turkménistan',
		'italian' => 'Turkmenistan',
		'portuguese' => 'Turquemenistão',
		'version' => NULL,
	),
	array( // row #223
		'id' => 796,
		'iso3' => 'TCA',
		'iso2' => 'TC',
		'english' => 'Turks and Caicos Islands',
		'german' => 'Turks- und Caicosinseln',
		'spanish' => 'Islas Turcas y Caicos',
		'french' => 'Îles Turques et Caïques',
		'italian' => 'Isole Turks e Caicos',
		'portuguese' => 'Turks e Caicos',
		'version' => NULL,
	),
	array( // row #224
		'id' => 798,
		'iso3' => 'TUV',
		'iso2' => 'TV',
		'english' => 'Tuvalu',
		'german' => 'Tuvalu',
		'spanish' => 'Tuvalu',
		'french' => 'Tuvalu',
		'italian' => 'Tuvalu',
		'portuguese' => 'Tuvalu',
		'version' => NULL,
	),
	array( // row #225
		'id' => 800,
		'iso3' => 'UGA',
		'iso2' => 'UG',
		'english' => 'Uganda',
		'german' => 'Uganda',
		'spanish' => 'Uganda',
		'french' => 'Ouganda',
		'italian' => 'Uganda',
		'portuguese' => 'Uganda',
		'version' => NULL,
	),
	array( // row #226
		'id' => 804,
		'iso3' => 'UKR',
		'iso2' => 'UA',
		'english' => 'Ukraine',
		'german' => 'Ukraine',
		'spanish' => 'Ucrania',
		'french' => 'Ukraine',
		'italian' => 'Ucraina',
		'portuguese' => 'Ucrânia',
		'version' => NULL,
	),
	array( // row #227
		'id' => 807,
		'iso3' => 'MKD',
		'iso2' => 'MK',
		'english' => 'Macedonia, the former Yugoslav Republic of',
		'german' => 'Mazedonien',
		'spanish' => 'ARY Macedonia',
		'french' => 'Macédoine (pays)',
		'italian' => 'Macedonia',
		'portuguese' => 'República da Macedónia',
		'version' => NULL,
	),
	array( // row #228
		'id' => 818,
		'iso3' => 'EGY',
		'iso2' => 'EG',
		'english' => 'Egypt',
		'german' => 'Ägypten',
		'spanish' => 'Egipto',
		'french' => 'Égypte',
		'italian' => 'Egitto',
		'portuguese' => 'Egipto',
		'version' => NULL,
	),
	array( // row #229
		'id' => 826,
		'iso3' => 'GBR',
		'iso2' => 'GB',
		'english' => 'United Kingdom',
		'german' => 'Vereinigtes Königreich Großbritannien und Nordirland',
		'spanish' => 'Reino Unido',
		'french' => 'Royaume-Uni',
		'italian' => 'Regno Unito',
		'portuguese' => 'Reino Unido',
		'version' => NULL,
	),
	array( // row #230
		'id' => 831,
		'iso3' => 'GGY',
		'iso2' => 'GG',
		'english' => 'Guernsey',
		'german' => 'Guernsey (Kanalinsel)',
		'spanish' => 'Guernsey',
		'french' => 'Guernesey',
		'italian' => 'Guernsey',
		'portuguese' => 'Guernsey',
		'version' => NULL,
	),
	array( // row #231
		'id' => 832,
		'iso3' => 'JEY',
		'iso2' => 'JE',
		'english' => 'Jersey',
		'german' => 'Jersey (Kanalinsel)',
		'spanish' => 'Jersey',
		'french' => 'Jersey',
		'italian' => 'Jersey',
		'portuguese' => 'Jersey',
		'version' => NULL,
	),
	array( // row #232
		'id' => 833,
		'iso3' => 'IMN',
		'iso2' => 'IM',
		'english' => 'Isle of Man',
		'german' => 'Insel Man',
		'spanish' => 'Isla de Man',
		'french' => 'Île de Man',
		'italian' => 'Isola di Man',
		'portuguese' => 'Ilha de Man',
		'version' => NULL,
	),
	array( // row #233
		'id' => 834,
		'iso3' => 'TZA',
		'iso2' => 'TZ',
		'english' => 'Tanzania, United Republic of',
		'german' => 'Tansania',
		'spanish' => 'Tanzania',
		'french' => 'Tanzanie',
		'italian' => 'Tanzania',
		'portuguese' => 'Tanzânia',
		'version' => NULL,
	),
	array( // row #234
		'id' => 840,
		'iso3' => 'USA',
		'iso2' => 'US',
		'english' => 'United States',
		'german' => 'Vereinigte Staaten von Amerika',
		'spanish' => 'Estados Unidos',
		'french' => 'États-Unis',
		'italian' => 'Stati Uniti d\'America',
		'portuguese' => 'Estados Unidos da América',
		'version' => NULL,
	),
	array( // row #235
		'id' => 850,
		'iso3' => 'VIR',
		'iso2' => 'VI',
		'english' => 'Virgin Islands, U.S.',
		'german' => 'Amerikanische Jungferninseln',
		'spanish' => 'Islas Vírgenes Estadounidenses',
		'french' => 'Îles Vierges américaines',
		'italian' => 'Isole Vergini Americane',
		'portuguese' => 'Ilhas Virgens Americanas',
		'version' => NULL,
	),
	array( // row #236
		'id' => 854,
		'iso3' => 'BFA',
		'iso2' => 'BF',
		'english' => 'Burkina Faso',
		'german' => 'Burkina Faso',
		'spanish' => 'Burkina Faso',
		'french' => 'Burkina Faso',
		'italian' => 'Burkina Faso',
		'portuguese' => 'Burkina Faso',
		'version' => NULL,
	),
	array( // row #237
		'id' => 858,
		'iso3' => 'URY',
		'iso2' => 'UY',
		'english' => 'Uruguay',
		'german' => 'Uruguay',
		'spanish' => 'Uruguay',
		'french' => 'Uruguay',
		'italian' => 'Uruguay',
		'portuguese' => 'Uruguai',
		'version' => NULL,
	),
	array( // row #238
		'id' => 860,
		'iso3' => 'UZB',
		'iso2' => 'UZ',
		'english' => 'Uzbekistan',
		'german' => 'Usbekistan',
		'spanish' => 'Uzbekistán',
		'french' => 'Ouzbékistan',
		'italian' => 'Uzbekistan',
		'portuguese' => 'Usbequistão',
		'version' => NULL,
	),
	array( // row #239
		'id' => 862,
		'iso3' => 'VEN',
		'iso2' => 'VE',
		'english' => 'Venezuela',
		'german' => 'Venezuela',
		'spanish' => 'Venezuela',
		'french' => 'Venezuela',
		'italian' => 'Venezuela',
		'portuguese' => 'Venezuela',
		'version' => NULL,
	),
	array( // row #240
		'id' => 876,
		'iso3' => 'WLF',
		'iso2' => 'WF',
		'english' => 'Wallis and Futuna',
		'german' => 'Wallis und Futuna',
		'spanish' => 'Wallis y Futuna',
		'french' => 'Wallis-et-Futuna',
		'italian' => 'Wallis e Futuna',
		'portuguese' => 'Wallis e Futuna',
		'version' => NULL,
	),
	array( // row #241
		'id' => 882,
		'iso3' => 'WSM',
		'iso2' => 'WS',
		'english' => 'Samoa',
		'german' => 'Samoa',
		'spanish' => 'Samoa',
		'french' => 'Samoa',
		'italian' => 'Samoa',
		'portuguese' => 'Samoa (Samoa Ocidental)',
		'version' => NULL,
	),
	array( // row #242
		'id' => 887,
		'iso3' => 'YEM',
		'iso2' => 'YE',
		'english' => 'Yemen',
		'german' => 'Jemen',
		'spanish' => 'Yemen',
		'french' => 'Yémen',
		'italian' => 'Yemen',
		'portuguese' => 'Iémen',
		'version' => NULL,
	),
	array( // row #243
		'id' => 894,
		'iso3' => 'ZMB',
		'iso2' => 'ZM',
		'english' => 'Zambia',
		'german' => 'Sambia',
		'spanish' => 'Zambia',
		'french' => 'Zambie',
		'italian' => 'Zambia',
		'portuguese' => 'Zâmbia',
		'version' => NULL,
	),
	array( // row #243
		'id' => 999,
		'iso3' => 'ZZZ',
		'iso2' => 'ZZ',
		'english' => '--None--',
		'german' => '--Keine--',
		'spanish' => '--Ninguno--',
		'french' => '--Aucun--',
		'italian' => '--Nessuno--',
		'portuguese' => '--Nenhum--',
		'version' => NULL,
	),
);

foreach($temp_country_iso as $item) {
	SDK::setLanguageEntry( 'Marketprices','it_it',$item['iso2'] , $item['italian'] );
	SDK::setLanguageEntry( 'Marketprices','en_us', $item['iso2'] , $item['english']);
	SDK::setLanguageEntry( 'Marketprices','ru_ru', $item['iso2'] , $item['english']);
	SDK::setLanguageEntry( 'Marketprices','de_de', $item['iso2'] , $item['german']);
	SDK::setLanguageEntry( 'Marketprices','es_es', $item['iso2'] , $item['spanish']);
	SDK::setLanguageEntry( 'Marketprices','fr_fr', $item['iso2'] , $item['french']);
	SDK::setLanguageEntry( 'Marketprices','pt_br', $item['iso2'] , $item['portuguese']);
}



?>
