<?php
include_once('../../config.inc.php');
chdir($root_directory);
require_once('include/utils/utils.php');
include_once('vtlib/Vtiger/Module.php');
$Vtiger_Utils_Log = true;
global $adb, $table_prefix,$default_charset;
session_start();
// html_entity_decode($description, ENT_NOQUOTES, $default_charset);
// htmlentities( , ENT_NOQUOTES, $default_charset);
//Turn on debugging level
$Vtiger_Utils_Log = true;
include_once('vtlib/Vtiger/Menu.php');
include_once('vtlib/Vtiger/Module.php');
//danzi.tn@20150429 traduzioni DE
SDK::setLanguageEntry("Accounts","de_de","Customer",htmlentities("Unternehmen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","LBL_ACCOUNT_INFORMATION",htmlentities("Unternehmen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","LBL_LIST_ACCOUNT_NAME",htmlentities("Firmenname", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Account Name",htmlentities("Firmenname", ENT_NOQUOTES, $default_charset)); 
SDK::setLanguageEntry("Accounts","de_de","Account No",htmlentities("Firmen-Nr.", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Modified Time",htmlentities("Änderungsdatum", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Origine Lead",htmlentities("Herkunft des Kontakts", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Progetto",htmlentities("Projekt", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Consenso newsletter",htmlentities("Einwilligung für den Erhalt von Newslettern", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Created Time",htmlentities("Erstellt am", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Lingua Base",htmlentities("Sprache", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","LBL_DESCRIPTION_INFORMATION",htmlentities("Zusatzinformationen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Comprato mag dic 2012",htmlentities("Kauf im Mai/Dez 2012", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Classificazione livello 1",htmlentities("Klassifizierung 1", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Linea",htmlentities("Verkaufslinie", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Attivita Principale",htmlentities("Haupttätigkeit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Frequenza visite",htmlentities("Häufigkeit der Besuche", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Area visite",htmlentities("Zone", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Area di intervento",htmlentities("Tätigkeitsgebiet des Unternehmens", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Faculty",htmlentities("Fakultät", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Attivita Secondaria",htmlentities("Nebentätigkeit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Frequenza proposta",htmlentities("Empfohlene Häufigkeit der Besuche", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Zona visite",htmlentities("Wochentag", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Potenziale &euro;/Anno",htmlentities("Potenzieller Umsatz/Jahr", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","With a Laboratory",htmlentities("Mit Labor", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Classificazione livello 2",htmlentities("Klassifizierung 2", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Centro di taglio",htmlentities("Abbundzentrum/Lohnabbund", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Lavora con enti pubblici",htmlentities("Zusammenarbeit mit Öffentlichen Ämtern", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Numero soci",htmlentities("Anzahl der Gesellschafter", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Numero dipendenti",htmlentities("Anzahl der Mitarbeiter", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","NR Dipendenti",htmlentities("Anzahl der Mitarbeiter", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Assistenza",htmlentities("Beratungsservice", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Dati Semiramis",htmlentities("Daten aus Semiramis", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","agent name",htmlentities("Name des Vertreters", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","agent number",htmlentities("Nummer des Vertreters", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","blocco avvocato",htmlentities("Gesperrt durch Anwalt", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","condizioni prezzo",htmlentities("Preisbedingungen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","condizioni pag",htmlentities("Zahlungsziele", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Nr. Area Manager",htmlentities("Nr des Area Managers", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Nome Area MAnager",htmlentities("Name des Area Managers", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Codice listino",htmlentities("Art der Preisliste", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Divisa listino",htmlentities("Währung", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Note Pagamenti",htmlentities("Notiz zur Zahlung", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Secondo Agente",htmlentities("Zweiter Vertreter", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Codice Ref.Vend.Int.",htmlentities("Kodex der Verkaufsreferentin", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Codice CRM",htmlentities("Kodex CRM", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Descrizione listino",htmlentities("Beschreibung Preisliste", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Dati genrali concorrente",htmlentities("Daten des Mitbewerbers", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Comunicazione",htmlentities("Kommunikation", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Servizi offerti",htmlentities("Angebotene Dienste", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Attivit&agrave;",htmlentities("Aktivitäten", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Attivita",htmlentities("Aktivitäten", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Aggiungi compito",htmlentities("Aufgabe hinzufügen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Aggiungi evento",htmlentities("Event  hinzufügen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Storico Attivit&agrave;",htmlentities("Vergangene Aktivitäten", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Activity History",htmlentities("Vergangene Aktivitäten", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","Activity History",htmlentities("Vergangene Aktivitäten", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Sales Order",htmlentities("Bestellungen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","Sales Order",htmlentities("Bestellungen", ENT_NOQUOTES, $default_charset)); 
SDK::setLanguageEntry("APP_STRINGS","de_de","SINGLE_SalesOrder",htmlentities("Bestellungen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","SalesOrder",htmlentities("Bestellungen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("CustomView","de_de","Sales Order",htmlentities("Bestellungen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("SalesOrder","de_de","SalesOrder",htmlentities("Bestellungen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Aggiungi ordine",htmlentities("Bestellung hinzufügen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Consulenze",htmlentities("Technische Beratung", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Aggiungi Consulenza",htmlentities("Technische Beratung hinzufügen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Potentials",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Invoice","de_de","LBL_POTENTIAL_TITLE",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","LBL_POTENTIAL_TITLE",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","LBL_POTENTIAL_TITLE",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","Potential",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","SINGLE_Potentials",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","Opportunity",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Opportunit&agrave;",htmlentities("Gelegenheit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Aggiungi opportunit&agrave;",htmlentities("Gelegenheit hinzufügen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Accounts","de_de","Inspections",htmlentities("Revisionen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("APP_STRINGS","de_de","Inspections",htmlentities("Revisionen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Consulenza",htmlentities("Technische Beratung", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Consulenza Name",htmlentities("Art der Beratung", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Product category",htmlentities("Produktlinie", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Product category description",htmlentities("Beschreibung der Produktlinie", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","consulenzastatus",htmlentities("Stand", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","numconsulenza",htmlentities("Beratungsnummer", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Parent",htmlentities("Unternehmen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Contact",htmlentities("Kontakt", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","consulenzacountry",htmlentities("Land", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Flag Agente",htmlentities("Beratung durch Handelsvertreter", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Agente Riferimento",htmlentities("zuständiger Außendienstmitarbeiter", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Assigned To",htmlentities("zuständiger Ingenieur", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Warranty Serial No",htmlentities("Garantie Nummer", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Report Visite",htmlentities("Besucherbericht", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Nome Visita",htmlentities("Art des Besuchs", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Azienda",htmlentities("Unternehmen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Attivita Principale",htmlentities("Haupttätigkeit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Attivita Secondaria",htmlentities("Nebentätigkeit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Area di intervento",htmlentities("Tätigkeitsgebiet des Unternehmens", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Nr Visita",htmlentities("Nummer des Besucherberichts", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Data visita",htmlentities("Besuchsdatum", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Linea di Vendita",htmlentities("Verkaufslinie", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Potenziale €/Anno",htmlentities("Potenzieller Umsatz/Jahr", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Potenziale &euro;/Anno",htmlentities("Potenzieller Umsatz/Jahr", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Scopo della visita",htmlentities("Ziel des Besuchs", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Note visita",htmlentities("Notizen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Risultato della Visita",htmlentities("Besuchsergebnis", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Ordine realizzato",htmlentities("Auftrag abgeschlossen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Materiale informativo lasciato",htmlentities("Abgegebenes Informationsmaterial", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Categoria Prodotti presentati",htmlentities("Präsentierte Produktlinien", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Consulenza","de_de","Prodotto specifico",htmlentities("Spezifische Produkte", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Report Visite",htmlentities("Besucherbericht", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Nome Visita",htmlentities("Art des Besuchs", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Azienda",htmlentities("Unternehmen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Attivita Principale",htmlentities("Haupttätigkeit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Attivita Secondaria",htmlentities("Nebentätigkeit", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Area di intervento",htmlentities("Tätigkeitsgebiet des Unternehmens", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Nr Visita",htmlentities("Nummer des Besucherberichts", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Data visita",htmlentities("Besuchsdatum", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Linea di Vendita",htmlentities("Verkaufslinie", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Linea",htmlentities("Verkaufslinie", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Potenziale €/Anno",htmlentities("Potenzieller Umsatz/Jahr", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Potenziale &euro;/Anno",htmlentities("Potenzieller Umsatz/Jahr", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Scopo della visita",htmlentities("Ziel des Besuchs", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Note visita",htmlentities("Notizen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","LBL_RESULT_INFORMATION",htmlentities("Besuchsergebnis", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Ordine realizzato",htmlentities("Auftrag abgeschlossen", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Materiale Informativo lasciato",htmlentities("Abgegebenes Informationsmaterial", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Categoria Prodotti presentati",htmlentities("Präsentierte Produktlinien", ENT_NOQUOTES, $default_charset));
SDK::setLanguageEntry("Visitreport","de_de","Prodotto specifico",htmlentities("Spezifische Produkte", ENT_NOQUOTES, $default_charset));

?>