<?php
include_once('../../config.inc.php');
chdir($root_directory);
require_once('include/utils/utils.php');
include_once('vtlib/Vtiger/Module.php');
$Vtiger_Utils_Log = true;
global $adb, $table_prefix,$default_charset;
session_start();
// html_entity_decode($description, ENT_NOQUOTES, $default_charset);
// htmlentities( , ENT_NOQUOTES, $default_charset);
//Turn on debugging level
$Vtiger_Utils_Log = true;
include_once('vtlib/Vtiger/Menu.php');
include_once('vtlib/Vtiger/Module.php');
//danzi.tn@20150429 traduzioni DE
SDK::setLanguageEntry("Accounts","de_de","Customer","Unternehmen");


SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FOUND","Trovato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_A","un");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_AN","un");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","is","e`");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","MSG_THE","La");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_MIGRATION_CHECK","Le versioni nel database e nel");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Handler","Responsabile");
SDK::setLanguageEntry("Accounts","ru_ru","XLAM","XLAM");
SDK::setLanguageEntry("Calendar","ru_ru","Children","Successori");
SDK::setLanguageEntry("Visitreport","ru_ru","Flyer Rothoschool","Flyer Rothoschool");
SDK::setLanguageEntry("Visitreport","ru_ru","Catalogo intego","Catalogo intego");
SDK::setLanguageEntry("Visitreport","ru_ru","Catalogo Innotech","Innotech");
SDK::setLanguageEntry("Visitreport","ru_ru","Holztechnic","Holztechnic");
SDK::setLanguageEntry("Visitreport","ru_ru","Catalogo rothofixing","rothofixing 2011/12");
SDK::setLanguageEntry("Visitreport","ru_ru","Guida edifici in legno","Guida edifici in legno");
SDK::setLanguageEntry("Visitreport","ru_ru","Terrazze e Facciate","Terrazze e Facciate");
SDK::setLanguageEntry("Accounts","ru_ru","AccountsHierarchy","Gerarchia aziende");
SDK::setLanguageEntry("Accounts","ru_ru","Categoria","Categoria");
SDK::setLanguageEntry("Accounts","ru_ru","Codice Fiscale","Codice Fiscale");
SDK::setLanguageEntry("Accounts","ru_ru","Frequenza proposta","Frequenza proposta");
SDK::setLanguageEntry("Accounts","ru_ru","Frequenza visite","Frequenza visite");
SDK::setLanguageEntry("Accounts","ru_ru","MC legno tagliato","MC legno tagliato");
SDK::setLanguageEntry("Accounts","ru_ru","Nome Area MAnager","Nome Area Manager");
SDK::setLanguageEntry("Accounts","ru_ru","NR Dipendenti","NR Dipendenti");
SDK::setLanguageEntry("Accounts","ru_ru","Partita IVA","Partita IVA");
SDK::setLanguageEntry("Accounts","ru_ru","Partita IVA CEE","Partita IVA CEE");
SDK::setLanguageEntry("Accounts","ru_ru","Periodicita","Periodicita");
SDK::setLanguageEntry("Accounts","ru_ru","Sottocategoria 1","Sottocategoria 1");
SDK::setLanguageEntry("Accounts","ru_ru","Sottocategoria 2","Sottocategoria 2");
SDK::setLanguageEntry("Accounts","ru_ru","Sottocategoria 3","Sottocategoria 3");
SDK::setLanguageEntry("Accounts","ru_ru","Sottocategoria 4","Sottocategoria 4");
SDK::setLanguageEntry("Accounts","ru_ru","Sottocategoria 5","Sottocategoria 5");
SDK::setLanguageEntry("Accounts","ru_ru","Tematiche","Tematiche");
SDK::setLanguageEntry("Visitreport","ru_ru","MACCHINE","Macchine varie");
SDK::setLanguageEntry("Visitreport","ru_ru","Flyer portapilastri","Flyer portapilastri");
SDK::setLanguageEntry("Visitreport","ru_ru","Listino 04.2013","Listino 04.2013");
SDK::setLanguageEntry("Visitreport","ru_ru","Flyer DUSS legno","Flyer DUSS legno");
SDK::setLanguageEntry("Visitreport","ru_ru","Riepilogativo membrane 2013","Riepilogativo membrane");
SDK::setLanguageEntry("Accounts","ru_ru","TERRAZZE","TERRAZZE E FACCIATE");
SDK::setLanguageEntry("Accounts","ru_ru","SEGHERIA","RIVENDITORE DI LEGNAME / SEGHE");
SDK::setLanguageEntry("Accounts","ru_ru","SPECIALANTICAD","SPECIALIZZATO SISTEMI ANTICADU");
SDK::setLanguageEntry("Accounts","ru_ru","SPECIALLEGNO","SPECIALIZZATO IN LEGNO");
SDK::setLanguageEntry("Accounts","ru_ru","CASE","CASE");
SDK::setLanguageEntry("Accounts","ru_ru","RIVENDITORE MACCHINE LEGNO","Rivenditore macchine");
SDK::setLanguageEntry("Accounts","ru_ru","CONAGR","CONSORZIO AGRARIO");
SDK::setLanguageEntry("Accounts","ru_ru","ELETTROMEC","ELETTROMECCANICHE");
SDK::setLanguageEntry("Accounts","ru_ru","FERRAMSPEC","FERRAMENTA SPECIALIZZATA");
SDK::setLanguageEntry("Accounts","ru_ru","ASSOCIAZIONE","Associazione");
SDK::setLanguageEntry("Accounts","ru_ru","COOPERAT","COOPERATIVE");
SDK::setLanguageEntry("Accounts","ru_ru","PRIVATI","PRIVATI");
SDK::setLanguageEntry("Accounts","ru_ru","GAZEBI","GAZEBI E PERGOLE");
SDK::setLanguageEntry("Contacts","ru_ru","Fattura","Fattura");
SDK::setLanguageEntry("Contacts","ru_ru","Sollecito","Sollecito");
SDK::setLanguageEntry("Contacts","ru_ru","Ordine","Ordine");
SDK::setLanguageEntry("Contacts","ru_ru","DDT","DDT");
SDK::setLanguageEntry("Contacts","ru_ru","Riceve sollecito","Riceve sollecito");
SDK::setLanguageEntry("Contacts","ru_ru","Codice Esterno","Codice Cliente");
SDK::setLanguageEntry("Visitreport","ru_ru","Categoria Prodotti presentati","Categoria Prodotti presentati");
SDK::setLanguageEntry("Visitreport","ru_ru","Materiale Informativo lasciato","Materiale informativo lasciato");
SDK::setLanguageEntry("Visitreport","ru_ru","Ordine realizzato","Ordine realizzato");
SDK::setLanguageEntry("Visitreport","ru_ru","Prodotto specifico","Prodotto specifico");
SDK::setLanguageEntry("Visitreport","ru_ru","Schede tecniche","Schede tecniche");
SDK::setLanguageEntry("Accounts","ru_ru","External Code","Codice Cliente");
SDK::setLanguageEntry("Accounts","ru_ru","Fatturato","Fatturato/cliente/anno");
SDK::setLanguageEntry("Accounts","ru_ru","Immobiliare","IMMOBILIARE");
SDK::setLanguageEntry("Accounts","ru_ru","FALEGNAME","FALEGNAME");
SDK::setLanguageEntry("Accounts","ru_ru","GENERAL CONTRACTOR","GENERAL CONTRACTOR");
SDK::setLanguageEntry("Accounts","ru_ru","COPERTURE","COPERTURE");
SDK::setLanguageEntry("Visitreport","ru_ru","TERRFACC","Terrazze e Facciate");
SDK::setLanguageEntry("Visitreport","ru_ru","Innotech","Catalogo Innotech");
SDK::setLanguageEntry("Visitreport","ru_ru","Listino HT 2014","Listino HT 2014");
SDK::setLanguageEntry("Visitreport","ru_ru","Listino TENAS 2014","Listino TENAS 2014");
SDK::setLanguageEntry("Visitreport","ru_ru","Listino INTEGO 2014","Listino INTEGO 2014");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","€ WOODSTAR 2014","â¬ WOODSTAR 2014");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","€ SCHEPPACH 2014","â¬ SCHEPPACH 2014");
SDK::setLanguageEntry("Accounts","ru_ru","LATTONIERE","LATTONIERE");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_TimeCards","Interventi");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Annual_Revenue","Azienda: Fatturato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_MASS_UPDATE","Mass update");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_MAIL_INVITATION_3","per visitare l'evento");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TCTime","Tempo");
SDK::setLanguageEntry("Accounts","ru_ru","TECNICOCLI","TECNICO CLIENTE");
SDK::setLanguageEntry("Accounts","ru_ru","HideHierarchy","Nascondi gerarchia");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Duplicate","Duplica");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MASSCONVERT_FORM_HEADER","Converti Lead");
SDK::setLanguageEntry("Visitreport","ru_ru","scopovisit","Scopo Visita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ORGANIZATION_VAT","PIVA:");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","EXISTING_RECORD","Record gia' esistente nel sist");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","EXISTING_RECORD","Record gia' esistente nel sist");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Original_data","record originale");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","total net","Totale netto");
SDK::setLanguageEntry("Accounts","ru_ru","Numero progettisti","Numero progettisti");
SDK::setLanguageEntry("Visitreport","ru_ru","LBL_ADD_TASK","Aggiungi Compito");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NOTFOUND_SA","Non e' stata trovata nessuna a");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NOTFOUND_SA","Non e' stata trovata nessuna a");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NOTFOUND_SA","Non e' stata trovata nessuna a");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NOTFOUND_SA","Non e' stata trovata nessuna a");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SAVE_MERGE_FIELDS","Salva Mappatura");
SDK::setLanguageEntry("HelpDesk","ru_ru","Transferred to user","Trasferito a utente");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_HTTP_ERR2","Informazioni su ");
SDK::setLanguageEntry("HelpDesk","ru_ru","Time Elapsed Last Status Chang","Tempo trascorso da ultimo camb");
SDK::setLanguageEntry("Visitreport","ru_ru","TERR","Terrazze facciate pergole ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Last_Name","Utente: Cognome");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_HERE","qui");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","BUDGET_VALUE","Valore del budget");
SDK::setLanguageEntry("Calendar","ru_ru","Download","Download");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","BUDGET_VALUE","Valore del budget");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_LINE_DETAILS","Dettagli Ammontare Opportunita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","equal","uguale a");
SDK::setLanguageEntry("Visitreport","ru_ru","Modified Time","Periodo Modifica");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LNK_CV_DUPLICATE","Duplica");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Run_it","Esegui");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_PLEASE_SELECT_A_ROL","Scegliere un ruolo");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_PLEASE_SELECT_A_ROL","Scegliere un ruolo");
SDK::setLanguageEntry("Visitreport","ru_ru","CATSAFE","Catalogo sistemi anticaduta");
SDK::setLanguageEntry("Visitreport","ru_ru","CATSAFE","Schede tecniche");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_SAVED","Salvato");
SDK::setLanguageEntry("Accounts","ru_ru","Zona visite","Zona visite");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Salutation","Contatto: Formula Saluto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ADD_LINE","Aggiungi Linea di prodotto");
SDK::setLanguageEntry("HelpDesk","ru_ru","Open Tickets","Ticket aperti");
SDK::setLanguageEntry("Visitreport","ru_ru","TASSELLI","Tasselli resine e colle");
SDK::setLanguageEntry("Visitreport","ru_ru","HOLZTEC","Holztechnic");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","New_data","nuovo record");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DELETE_MSG","Sei sicuro di volere eliminare");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DELETE_MSG","Sei sicuro di volere eliminare");
SDK::setLanguageEntry("Accounts","ru_ru","Forza vendita","Forza vendita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Country","Utente: Stato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_EXAMPLE","Esempio");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ALERT_DCLINK_NOUSER","Non sono state impostate le tu");
SDK::setLanguageEntry("Accounts","ru_ru","Nazione","Nazione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Email","Utente: Email");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FAVORITE","Preferito");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_HTTP_ERR5","Nessun sommario disponibile");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FOUND_F","Trovata");
SDK::setLanguageEntry("Visitreport","ru_ru","TAPPI","Tappi rattoppi");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_AMOUNT_TOTAL","Ammontare totale");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CREATEVISTREPORT_BTN","Crea Report Visita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_HOUR","Ora");
SDK::setLanguageEntry("Visitreport","ru_ru","01 MACCH ATTR","01 - Macchine e Attrezzature");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_NewTC","Nuovo Intervento");
SDK::setLanguageEntry("HelpDesk","ru_ru","Rothoblaas Category Descriptio","Descrizione categoria");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","visitreport number","Numero Report Visita");
SDK::setLanguageEntry("Accounts","ru_ru","YES","Si");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Email","Azienda: Email");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Support_Start_Date","Contatto: Data Inizio Supporto");
SDK::setLanguageEntry("Accounts","ru_ru","Bank Details","Coordinate Bancarie");
SDK::setLanguageEntry("Calendar","ru_ru","CalendarHierarchy","Gerarchia Attivita`");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_WORKER","Risorsa");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","PurchaseOrders","Ordine di Acquisto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","singleprice","Prezzo Singolo");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_OR","o");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_OR","o");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Signature","Utente: Firma");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SINGLE_Notes","Documento");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_VISITA","Visita ");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_BYPRODUCT_BTN","Aziende per ordini");
SDK::setLanguageEntry("Accounts","ru_ru","With a Laboratory","Con Laboratorio");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Yahoo_ID","Lead: Yahoo ID");
SDK::setLanguageEntry("Visitreport","ru_ru","FLYSCHOOL","Flyer Rothoschool");
SDK::setLanguageEntry("Visitreport","ru_ru","ACC TETTO","Accessori tetto");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CAL_FILTER","Filtro rapido per");
SDK::setLanguageEntry("Calendar","ru_ru","NO_SUBJECT_SPECIFIED","Non hai specificato nessun ogg");
SDK::setLanguageEntry("HelpDesk","ru_ru","Due Time","Ora chiusura (hh:mm)");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","ProjectPlan","Pianificazioni");
SDK::setLanguageEntry("Visitreport","ru_ru","NASTRI","Nastri e sigillanti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ACC_LISTVIEWBYPRODUCT_EXP","Esporta i dati correnti");
SDK::setLanguageEntry("Accounts","ru_ru","Tel. 2","Tel. 2");
SDK::setLanguageEntry("Accounts","ru_ru","importFile","File di importazione(nome del ");
SDK::setLanguageEntry("HelpDesk","ru_ru","CONVERT_INVOICE","Converti in fattura");
SDK::setLanguageEntry("Visitreport","ru_ru","LBL_DESCRIPTION_INFORMATION","Nota Spese");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Account_Type","Azienda: Tipo Azienda");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_PROD","Codice prodotto");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MAPPEDALERT","Il campo è già stato mappato");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MAPPEDALERT","Il campo � gi� stato mappa");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_DUPLICATE","Si sta tentando di rifare il m");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_DUPLICATE","Si sta tentando di rifare il m");
SDK::setLanguageEntry("Visitreport","ru_ru","spautostr","Spese Autostradali");
SDK::setLanguageEntry("Visitreport","ru_ru","visitreportname","Nome Visita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","date","Data");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FOLDER_CONTENT","Ultimi elementi modificati");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_CF","CF");
SDK::setLanguageEntry("Accounts","ru_ru","Banca di Appoggio","Banca di Appoggio");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_NONE","Nessuno");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","SURE_TO_DELETE_CUSTOM_MAP","Sei sicuro di voler cancellare");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_NONE","Nessuno");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","SURE_TO_DELETE_CUSTOM_MAP","Sei sicuro di voler cancellare");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","CHARACTER","caratteri");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","CHARACTER","caratteri");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ADD_VISITREPORT","Aggiungi Report Visite");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","TimeCard","Interventi");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Timecard","Intervento");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_FAIL","Operazione fallita");
SDK::setLanguageEntry("Accounts","ru_ru","Assistenza","Assistenza");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_FAIL","Operazione fallita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_CASH_DELIVERY","Pagamento in contanti");
SDK::setLanguageEntry("Contacts","ru_ru","importFile","File di importazione (nome del");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Email","Contatto: Email");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_HIDEHIERARCH","Nascondi gerarchia");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_HIDEHIERARCH","Nascondi gerarchia");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","STRUCTURAL_ENGINEERING","Ingegneria Strutturale");
SDK::setLanguageEntry("HelpDesk","ru_ru","Due Date","Data di chiusura");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SINGLE_Visitreport","Report visite");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_MAP_NAME_ALREADY_EXISTS","Esiste già una mappatura con ");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_MAP_NAME_ALREADY_EXISTS","Esiste gi� una mappatura con");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CAL_INTERRUPTED","Interrotto");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CAL_INTERRUPTED","Interrotto");
SDK::setLanguageEntry("Contacts","ru_ru","Todays Birthday","Compleanni di oggi");
SDK::setLanguageEntry("HelpDesk","ru_ru","Transferred to group","Trasferito a gruppo");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FOLDER_NAME","Nome Cartella");
SDK::setLanguageEntry("Visitreport","ru_ru","PROT COLL","Protezione collettiva e access");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_ND","Nessuno");
SDK::setLanguageEntry("Accounts","ru_ru","New This Week","Nuove della settimana");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Notes","Documenti");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","EXISTING_SAVE_CONVERTLEAD","Procedendo il contatto e l'eve");
SDK::setLanguageEntry("HelpDesk","ru_ru","SINGLE_SLA","Gestore SLA");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","EXISTING_SAVE_CONVERTLEAD","Procedendo il contatto e l'eve");
SDK::setLanguageEntry("HelpDesk","ru_ru","SLA start date","Data partenza SLA");
SDK::setLanguageEntry("Accounts","ru_ru","External Project Nummer","Codice progetto esterno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LABEL_NO_TAX","Nessuna tassa associata a ques");
SDK::setLanguageEntry("Contacts","ru_ru","importDate","Data importazione");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","NOTVALID_SMSID","Numero di Cellulare non valido");
SDK::setLanguageEntry("Visitreport","ru_ru","WOODSTAR","Woodstar");
SDK::setLanguageEntry("Calendar","ru_ru","Visita","Visita");
SDK::setLanguageEntry("Accounts","ru_ru","Opportunita","Opportunit&agrave;");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","NOTVALID_SMSID","Numero di Cellulare non valido");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_CF","Codice Fiscale non valido !");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_CF","Codice Fiscale non valido !");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","COMBO_VISITREPORT","Report Visite");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_ACCOUNT","Selezionare l'Azienda per proc");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_ACCOUNT","Selezionare l'Azienda per proc");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_A_AT","a");
SDK::setLanguageEntry("HelpDesk","ru_ru","Area Manager No","Nr. Area Manager");
SDK::setLanguageEntry("Contacts","ru_ru","LBL_TimeCards","Interventi");
SDK::setLanguageEntry("HelpDesk","ru_ru","Reset SLA","Resetta SLA");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_EXPORT_REPORT_TO_RTF","Esporta in RTF");
SDK::setLanguageEntry("Visitreport","ru_ru","DUSS","Duss");
SDK::setLanguageEntry("Calendar","ru_ru","E-mail","E-mail");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","processor","Processor");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PRODUCT_LINES_REPORT","Report linee di prodotto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_REPORT_STAT_TITLE","Reports per ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_MODULE_MANAGER","Gestore Modulo");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_First_Name","Utente: Nome");
SDK::setLanguageEntry("HelpDesk","ru_ru","Internal Project Nummer","Numero Progetto Interno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SINGLE_Workflow","Workflow");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Rating","Lead: Rating");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Last_Name","Lead: Cognome");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_NO_F","Nessuna");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","salesorder_no","Numero Ordine:");
SDK::setLanguageEntry("Visitreport","ru_ru","SCHEPP","Scheppach - woodstar");
SDK::setLanguageEntry("Visitreport","ru_ru","TEC","Schede tecniche");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_NO_SUBJECT","(nessun-oggetto)");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Website","Azienda: Sito Web");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_MAIL_INVITATION_CONFIRM","Confermi la tua partecipazione");
SDK::setLanguageEntry("Visitreport","ru_ru","ANTICAD","Sistemi anticaduta");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","DOESNOT_HAVE_AN_SMSID"," non ha un numero di cellular");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","DOESNOT_HAVE_AN_SMSID"," non ha un numero di cellular");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TCUnits","Unità");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_HomePhone","Utente: Telefono Casa");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Internal Project Nummer","Numero Interno Progetto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","OTHER","Altro");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_SOLD_QUANTITY","Quantita` venduta");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_UTF8","Prego cambiare il file di conf");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_UTF8","Prego cambiare il file di conf");
SDK::setLanguageEntry("Calendar","ru_ru","Expired","E' scaduto");
SDK::setLanguageEntry("Accounts","ru_ru","STUDIOTEC","STUDIO TECNICO");
SDK::setLanguageEntry("HelpDesk","ru_ru","LBL_HelpDesk_Receipt","Scheda di lavorazione");
SDK::setLanguageEntry("HelpDesk","ru_ru","Projectnumber intern","Numero di Progetto interno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Workflow","Workflow");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MANDATORY_FIELDS_WF","Inserire il valore per i campi");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MANDATORY_FIELDS_WF","Inserire il valore per i campi");
SDK::setLanguageEntry("Accounts","ru_ru","Projectleader OSS","Leader interno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_UNSELECT_ALL_IDS","Deseleziona tutto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ASSIGNED_TO_ME","A Me");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_UNSELECT_ALL_IDS","Deseleziona tutto");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_SAVE","Vuoi salvare lo stesso le modi");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_SAVE","Vuoi salvare lo stesso le modi");
SDK::setLanguageEntry("Accounts","ru_ru","Tel. 1","Tel. 1");
SDK::setLanguageEntry("HelpDesk","ru_ru","choose","Seleziona");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_CREATING_NEW_Notes","Creazione Nuovo Documento");
SDK::setLanguageEntry("Visitreport","ru_ru","BULLCONTROV","Bulloneria e controventatura");
SDK::setLanguageEntry("Calendar","ru_ru","Accettazione clienti","Accettazione clienti");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_MAGG_DI","compresi tra");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SINGLE_Projects","Project");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","DELETE_PICKLIST_VALUES","Cancella i valori della PickLi");
SDK::setLanguageEntry("HelpDesk","ru_ru","SLA end date","Data fine SLA");
SDK::setLanguageEntry("Accounts","ru_ru","EILDENOTETTI","IMPRESA EDILE (no tetti)");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PREFERENCES","Preferenze");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_SHOW_ITEMS","Mostra Elementi");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","taxno","Valore aggiunto alla Tassa N.:");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","taxfree","tax free");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_EXPORT_REPORT_TO_PDF","Esporta in PDF");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_SHOWHIERARCH","Visualizza gerarchia");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_SHOWHIERARCH","Visualizza gerarchia");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","YAHOO_EMAIL_FILED_IS"," nel campo  yahoo email e` ");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_PIVA","Partita IVA non valida !");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_PIVA","Partita IVA non valida !");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Lead_Source","Lead: Fonte Lead");
SDK::setLanguageEntry("HelpDesk","ru_ru","Severity Changed to","Importanza cambiata a");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Salutation","Lead: Formula di Saluto");
SDK::setLanguageEntry("HelpDesk","ru_ru","Area Manager Name","Nome Area Manager");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Title","Utente: Titolo");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TCMoveUp","Muovi Su");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NOTFOUND","Non e' stata trovata nessuna a");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_ANSWER","ha risposto");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NOTFOUND","Non e' stata trovata nessuna a");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FAVORITES","Preferiti");
SDK::setLanguageEntry("Accounts","ru_ru","Numero dipendenti","Numero dipendenti");
SDK::setLanguageEntry("Visitreport","ru_ru","Visitreport No","Nr. Visita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Import_contact_as_new","come una nuova importazione di");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_MAIL_INVITATION_1","Clicca");
SDK::setLanguageEntry("Accounts","ru_ru","ARCHITECTURE","Architettura");
SDK::setLanguageEntry("Calendar","ru_ru","Event","Attività");
SDK::setLanguageEntry("HelpDesk","ru_ru","Out SLA Time Elapsed","Tempo trascorso fuori SLA");
SDK::setLanguageEntry("Accounts","ru_ru","Uff. tecnico interno","Uff. tecnico interno");
SDK::setLanguageEntry("HelpDesk","ru_ru","Time Elapsed","Tempo trascorso");
SDK::setLanguageEntry("HelpDesk","ru_ru","Idle Time Elapsed","Tempo trascorso in idle");
SDK::setLanguageEntry("Visitreport","ru_ru","REICH","Reich");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_HTTP_ERR4"," non e' un Simbolo Ticker vali");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SEND_SMS_BUTTON","Sms");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contacted - Never Contact Agai","Contattato - non contattarlo p");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SEND_SMS_BUTTON","Sms");
SDK::setLanguageEntry("Visitreport","ru_ru","LBL_RESULT_INFORMATION","Risultato della Visita");
SDK::setLanguageEntry("Accounts","ru_ru","SINGLE_Marketprices","Market Price");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Industry","Lead: Settore");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Import_lead_as_new","come un nuova importazione di ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Membri","Membri");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","JUMP_TO","Vai a");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_MAIL_INVITATION_2","per visitare l'evento.");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_MAIL_LBL_ANSWER","Hai risposto");
SDK::setLanguageEntry("Accounts","ru_ru","CIVIL_ENGINEERING","Ingegneria Civile");
SDK::setLanguageEntry("Visitreport","ru_ru","visitdate","Data Visita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_DELETE_FOLDERS","Elimina Cartelle...");
SDK::setLanguageEntry("Visitreport","ru_ru","MAFELL","Mafell");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_WORKFLOW_LIST","Lista Workflow");
SDK::setLanguageEntry("HelpDesk","ru_ru","Marketing","Marketing");
SDK::setLanguageEntry("Calendar","ru_ru","DAY_OF_MONTH","giorno del mese");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_ATLEAST_ONE_MERGE_C","Selezionare almeno un campo pe");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_ATLEAST_ONE_MERGE_C","Selezionare almeno un campo pe");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TOTAL_VALUE","Totale ore");
SDK::setLanguageEntry("APP_LIST_STRINGS","ru_ru","record_type_default_key","Aziende");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Invoices","Fattura");
SDK::setLanguageEntry("HelpDesk","ru_ru","ProjectPlan","Pianificazione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SUMME_SUPPLY_HOUR","Totale ore fornite");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_PLEASE_MAP_MANDATORY_FIELD","E' necessario mappare i seguen");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_PLEASE_MAP_MANDATORY_FIELD","E' necessario mappare i seguen");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Small Menu","Minimizzato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_AN_F","una");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Update_record","uscita aggiornamento dati");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","text","Descrizione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TCWorker","Utente");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Department","Utente: Dipartimento");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_STATUS_BLOCK","Gestore stati");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_RELATE","Collega");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_PostalCode","Utente: CAP");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MASS_EDIT_WITHOUT_WF_1","Hai selezionato più di ");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MASS_EDIT_WITHOUT_WF_1","Hai selezionato pi� di ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Faculty","Facolt&agrave;");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","no_valid_extension","Estensione del file non valida");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","no_valid_extension","Estensione del file non valida");
SDK::setLanguageEntry("Calendar","ru_ru","ShowHierarchy","Visualizza gerarchia");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_VALUEFILTER","Filtri valore");
SDK::setLanguageEntry("HelpDesk","ru_ru","LBL_PDF_WITH_COMMENTS","Ticket con commenti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Refresh","Aggiorna");
SDK::setLanguageEntry("Accounts","ru_ru","Rating Finance","Rating Finance");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Recycle Bin","Cestino");
SDK::setLanguageEntry("Visitreport","ru_ru","Description","Descrizione");
SDK::setLanguageEntry("Visitreport","ru_ru","Created Time","Periodo Creazione");
SDK::setLanguageEntry("Accounts","ru_ru","Mix prodotti","Mix prodotti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Sms","Sms");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Add Ddt","Crea Ddt");
SDK::setLanguageEntry("Accounts","ru_ru","IBAN","IBAN");
SDK::setLanguageEntry("HelpDesk","ru_ru","LBL_PDF_WITHOUT_COMMENTS","Ticket senza commenti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","COMBO_PROJECTS","Progetti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SELECT_ALL_IDS","Seleziona tutto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SELECT_ALL_IDS","Seleziona tutto");
SDK::setLanguageEntry("HelpDesk","ru_ru","CONVERT_SALESORDER","Converti in ordine di vendita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TO_COMPANY","Spett.le:");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_SAVING_DRAFT","Salvataggio bozza in corso");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_SAVING_DRAFT","Salvataggio bozza in corso");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SUMME_NO_INVOICE_HOURS","Totale ore non fatturate");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","invoice_no","Numero Fattura:");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_MOVE","Sposta");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","SELECT_SMSID","Prego selezionare un identific");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","SELECT_SMSID","Prego selezionare un identific");
SDK::setLanguageEntry("Visitreport","ru_ru","ATTREZZ","Attrezzatura");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_CAT","Categoria prodotto");
SDK::setLanguageEntry("HelpDesk","ru_ru","Projectnumber extern","Numero di Progetto esterno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","PLEASE_CHOOSE_COLUMN","Please choose column");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ENTER_URL","Prego inserire l'indirizzo del");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ENTER_URL","Prego inserire l'indirizzo del");
SDK::setLanguageEntry("Accounts","ru_ru","importDate","Data importazione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","External Project Nummer","Numero Esterno Progetto");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","MORE_THAN_500","Hai selezionato più di 500 re");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","MORE_THAN_500","Hai selezionato pi� di 500 r");
SDK::setLanguageEntry("Accounts","ru_ru","Tiratura","Tiratura");
SDK::setLanguageEntry("Calendar","ru_ru","Fathers","Predecessore");
SDK::setLanguageEntry("HelpDesk","ru_ru","Category Changed to","Categoria cambiata a");
SDK::setLanguageEntry("Visitreport","ru_ru","LBL_VISITREPORT_INFORMATION","Informazioni Visita");
SDK::setLanguageEntry("Accounts","ru_ru","CARTONG","POSATORI CARTONGESSO E ALUCOBO");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Select","Seleziona");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_PLEASE_SELECT","--Prego Selezionare--");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_PLEASE_SELECT","--Prego Selezionare--");
SDK::setLanguageEntry("HelpDesk","ru_ru","LBL_HELPINFO_HOURS","Quando il ticket è collegato ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_First_Name","Contatto: Nome");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FOLDER","Cartella");
SDK::setLanguageEntry("Accounts","ru_ru","Macchine e attrezzature","Macchine e attrezzature");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_LINE_NAME","Nome linea di prodotto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_BYPRODUCT_BTN","Aziende per ordini");
SDK::setLanguageEntry("Visitreport","ru_ru","accountid","Azienda");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_REPORT_PROJECT_HOURS","Report Ore Progetto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Dont_import","non importare");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","View","Visualizza");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Fiera KLIMAHOUSE 2014","Porte Aperte KLIMAHOUSE 2014");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_UPDATE_BUTTON","aggiorna record");
SDK::setLanguageEntry("Accounts","ru_ru","Fax 1","Fax 1");
SDK::setLanguageEntry("Calendar","ru_ru","HideHierarchy","Nascondi gerarchia");
SDK::setLanguageEntry("Accounts","ru_ru","Stato Importazione Semiramis","Stato Importazione Semiramis");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_EMAILID","Inserire un valido Email Id");
SDK::setLanguageEntry("Visitreport","ru_ru","CATHOUSE","Catalogo rothouse");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_EMAILID","Inserire un valido Email Id");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DONT_HAVE_FAX_PERMISSION","Non hai i permessi per il camp");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DONT_HAVE_FAX_PERMISSION","Non hai i permessi per il camp");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TO","al");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SINGLE_Fax","Fax");
SDK::setLanguageEntry("Accounts","ru_ru","agent name","Nome agente");
SDK::setLanguageEntry("Visitreport","ru_ru","spvitoall","Spese Vitto Alloggio");
SDK::setLanguageEntry("Accounts","ru_ru","Total Hour","Totale ore");
SDK::setLanguageEntry("APP_LIST_STRINGS","ru_ru","case_status_default_key","Nuova");
SDK::setLanguageEntry("HelpDesk","ru_ru","Area Manager","Nome Area Manager");
SDK::setLanguageEntry("Accounts","ru_ru","Consulenze","Consulenze");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_LIST","Elenco");
SDK::setLanguageEntry("Accounts","ru_ru","RIVEATTRED","RIVENDITORI DI ATTREZZATURE ED");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ReassignTicketTo","Assegna il Ticket a");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MASS_EDIT_WITHOUT_WF_2"," elementi, questo potrebbe sov");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_EXAMPLES","Esempi");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MASS_EDIT_WITHOUT_WF_2"," elementi, questo potrebbe sov");
SDK::setLanguageEntry("Accounts","ru_ru","Secondary Owner Permission","Permessi secondo assegnatario");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Projects","Progetti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ASSIGNED_TO_SELECTED","Selezionati");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ADD_NEW_FOLDER","Aggiungi Cartella");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","totaldiscount","Totale sconto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PRODUCT_LINES","Linee di prodotto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","ERR_INVALID_YAHOO_EMAIL_ADDRES","indirizzo yahoo non valido.");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","DOESNOT_HAVE_AN_FAXID","non ha un numero di fax");
SDK::setLanguageEntry("Accounts","ru_ru","TELAIO","TELAIO");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","DOESNOT_HAVE_AN_FAXID","non ha un numero di fax");
SDK::setLanguageEntry("Visitreport","ru_ru","03 IMPERM","03 - Impermeabilizzazione");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_PENDING_INPUT","In Attesa di input");
SDK::setLanguageEntry("Visitreport","ru_ru","LBL_ADD_EVENT","Aggiungi Evento");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_INVITED_LINK","Fallo conoscere ai tuoi amici!");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_INVITED_LINK","Fallo conoscere ai tuoi amici!");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_MANDATORY_FIELD_VALUE","Alcuni valori obbligatori sono");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_MANDATORY_FIELD_VALUE","Alcuni valori obbligatori sono");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Field","Campo");
SDK::setLanguageEntry("Accounts","ru_ru","Map","Map");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_TRANSFER_TO_CON","Deve essere selzionato un cont");
SDK::setLanguageEntry("Accounts","ru_ru","Sistemi anticaduta","Sistemi anticaduta");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_TRANSFER_TO_CON","Deve essere selzionato un cont");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_INSERT_ENTRIE","come nuovo cliente");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ACC_DCLINK_BTN","Dettaglio Doc Credit Azienda");
SDK::setLanguageEntry("Accounts","ru_ru","e-mail 1","e-mail 1");
SDK::setLanguageEntry("HelpDesk","ru_ru","Update Time","Orario di aggiornamento");
SDK::setLanguageEntry("Accounts","ru_ru","Download","Download");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_IN_PROGRESS","In Corso");
SDK::setLanguageEntry("Visitreport","ru_ru","ANCOR","Dispositivi di ancoraggio");
SDK::setLanguageEntry("HelpDesk","ru_ru","sortWO","Ordina schede di lavorazione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","PICKLIST_CANNOT_BE_EMPTY","Il valore della picklist non p");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Sorder No","Numero Ordine di Vendita");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_FIELDS_MAPPED_MORE_THAN_ON","Il seguente campo è mappato p");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_FIELDS_MAPPED_MORE_THAN_ON","Il seguente campo � mappato ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FROM","da");
SDK::setLanguageEntry("Calendar","ru_ru","Current Event","Evento Corrente");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DONT_HAVE_SMS_PERMISSION","Non hai i permessi per il camp");
SDK::setLanguageEntry("Accounts","ru_ru","FERRAMGEN","FERRAMENTA GENERICA");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DONT_HAVE_SMS_PERMISSION","Non hai i permessi per il camp");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Industry","Azienda: Settore");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_HEADED","Intestato a");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Update_contact_update_account","update person and update organ");
SDK::setLanguageEntry("HelpDesk","ru_ru","Ticket Sub Category","Sotto Categoria");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PERMISSION_DENIED","Non hai i permessi per modific");
SDK::setLanguageEntry("Contacts","ru_ru","LBL_CLOSE_POPUP","ritorna");
SDK::setLanguageEntry("Visitreport","ru_ru","Visitreport Name","Nome Visita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_APPLY_LABEL","Applica");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SELECT_FOLDER","Seleziona Cartella");
SDK::setLanguageEntry("Accounts","ru_ru","blocco avvocato","Blocco avvocato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TCDate","Data");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FROM_Q","dal");
SDK::setLanguageEntry("Visitreport","ru_ru","CONNETT","Connettori a scomparsa");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Large Menu","Massimizzato");
SDK::setLanguageEntry("Accounts","ru_ru","Internal Project Nummer","Codice progetto interno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Modify","Modifica");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_LIST_SHOW","Mostra");
SDK::setLanguageEntry("Calendar","ru_ru","All day","Tutto il giorno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Status","Lead: Stato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_NO_INVOICE","Non in fattura");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_NOT_STARTED","Non Iniziato");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","MUST_BE_CHECKED","Deve essere selezionato");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","MUST_BE_CHECKED","Deve essere selezionato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Last_Name","Contatto: Cognome");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PAY_BY","Pagamento mediante");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_NewState","Cambia lo status del Ticket a");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_MYFILTER_VALUE","Filtra valori");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_AUTO_UPDATE","Numerazione Automatica");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","NULL_SMSID","Nessun numero di Cellulare spe");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","NULL_SMSID","Nessun numero di Cellulare spe");
SDK::setLanguageEntry("Visitreport","ru_ru","descspother","Descrizione altre Spese");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ERROR_END_DATE","Inizio Progetto deve essere mi");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_NO_M","Nessun");
SDK::setLanguageEntry("Accounts","ru_ru","Corsi","Corsi");
SDK::setLanguageEntry("HelpDesk","ru_ru","External Project Nummer","Numero Progetto Esterno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","DUPLICATE_VALUES_FOUND","Trovato un valore duplicato");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","PRODUCT_LINE_NAME","Nome Prodotto");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","PRODUCT_LINE_NAME","Nome Prodotto");
SDK::setLanguageEntry("Visitreport","ru_ru","ACUSTICA","Acustica");
SDK::setLanguageEntry("Accounts","ru_ru","CLIFINALE","CLIENTE FINALE");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_MAYBE","Forse");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PIVA","PIVA");
SDK::setLanguageEntry("Accounts","ru_ru","RIVEANTICAD","RIVENDITE SISTEMI ANTICADUTA");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","ARCHITECTURE","Architettura");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Rating","Azienda: Valutazione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Update_person","aggiorna contatto esistente");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Payment Type","Tipo Pagamento");
SDK::setLanguageEntry("Visitreport","ru_ru","02 SISFISS","02 - Sistemi fissaggio");
SDK::setLanguageEntry("Accounts","ru_ru","Fonte Lead","Fonte Lead");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_MENU_MIN","Minimizza menu");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_ACTIVITY_OCCUPATION","Occupazione");
SDK::setLanguageEntry("Accounts","ru_ru","Sollecito","Sollecito");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Account_Name","Azienda: Nome Azienda");
SDK::setLanguageEntry("Calendar","ru_ru","Versamento Unicredit","Versamento Unicredit");
SDK::setLanguageEntry("Visitreport","ru_ru","kmpercorsi","Km Percorsi");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Title","Lead: Titolo");
SDK::setLanguageEntry("Calendar","ru_ru","Will expire","Scade");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_CLOSE_POPUP","ritorna");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_STARTDATE","Data Inizio");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_CHANGING","Cambia lo stato in ");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_CHANGING","Cambia lo stato in ");
SDK::setLanguageEntry("Accounts","ru_ru","NOLEGGI","NOLEGGI");
SDK::setLanguageEntry("Accounts","ru_ru","Produzione","Produzione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PLEASE_SELECT","--Prego Selezionare--");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","With a Laboratory","Con Laboratorio");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_MASSCONVERT_LIMIT","Puoi convertire al massimo 50 ");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CAL_INVITATION","Partecipazione");
SDK::setLanguageEntry("Visitreport","ru_ru","MEMBRANE","Membrane");
SDK::setLanguageEntry("Calendar","ru_ru","Task","Compito");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Support_End_Date","Contatto: Data Fine Supporto");
SDK::setLanguageEntry("Accounts","ru_ru","Lavora con enti pubblici","Lavora con enti pubblici");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_EMAIL","Email");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_EMAIL","Email");
SDK::setLanguageEntry("HelpDesk","ru_ru","Priority Changed to","Priorita` cambiata a");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_HTTP_ERR1","C'e' un problema nella richies");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_EMPTY_FOLDER","Questa cartella è vuota");
SDK::setLanguageEntry("Visitreport","ru_ru","VITIEST","Viti per esterno");
SDK::setLanguageEntry("HelpDesk","ru_ru","Time Last Status Change","Data ultimo cambio di stato");
SDK::setLanguageEntry("Accounts","ru_ru","Note Pagamenti","Note Pagamenti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ENDDATE","Data Fine");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","general","Campi Generali");
SDK::setLanguageEntry("Visitreport","ru_ru","FISS CAPPOTTO","Fissaggio per cappotto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PRINT_VIEW_PROJECT_WORKERS","Report tempi");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_EITHER","Selezionare Azienda o Contatto");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_EITHER","Selezionare Azienda o Contatto");
SDK::setLanguageEntry("HelpDesk","ru_ru","user","utente");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ELEMENTS","Elementi");
SDK::setLanguageEntry("Accounts","ru_ru","Origine Lead","Origine Contatto");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_COMMIT","Merge delle aziende avvenuto c");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_COMMIT","Merge delle aziende avvenuto c");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Import_account_as_new","come una nuova importazione di");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_OVER","su");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_PLANNED","Pianificato");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_POTENTIAL_AMOUNT","L'Ammontare deve essere un imp");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_POTENTIAL_AMOUNT","L'Ammontare deve essere un imp");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TCType","Tipo");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","EXISTING_SAVE","Vuoi salvare lo stesso?");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","EXISTING_SAVE","Vuoi salvare lo stesso?");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ACC_LISTVIEWBYPRODUCT_MAP","Visualizza in Mappa");
SDK::setLanguageEntry("HelpDesk","ru_ru","SLA Estimated Time","Tempo SLA previsto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SINGLE_Charts","Grafico");
SDK::setLanguageEntry("Accounts","ru_ru","GARDEN","GARDEN");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","site","Sito");
SDK::setLanguageEntry("Visitreport","ru_ru","SOLAI","Solai collaboranti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_VALID_TILL","Periodo di validita'");
SDK::setLanguageEntry("Accounts","ru_ru","Affiliazione","Affiliazioni");
SDK::setLanguageEntry("Accounts","ru_ru","ERP Code","Codice ERP");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","NEW_F","Nuova");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","SINGLE_Sms","Sms");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FOUND_M","Trovato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TCMoveDown","Muovi Giù");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contacted - Successful","Contattato - esito positivo");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LENGTH","la lunghezza");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LENGTH","la lunghezza");
SDK::setLanguageEntry("HelpDesk","ru_ru","LBL_HELPINFO_DAYS","Quando il ticket è collegato ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Mobile","Utente: Cellulare");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DELETED_SUCCESSFULLY","Widget cancellato con successo");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DELETED_SUCCESSFULLY","Widget cancellato con successo");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Title","Contatto: Titolo");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Visitreport","Report visite");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE","E' stato trovata una azienda c");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE","E' stato trovata una azienda c");
SDK::setLanguageEntry("Accounts","ru_ru","Fatturato anno precedente","Fatturato anno precedente");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_A_F","una");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_DCLINK_BTN","Vai a Doc Credit");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contacted - Unsuccessful","Contattato - esito negativo");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","POTENTIAL_AMOUNT_CANNOT_BE_EMP","Potential amount cannot be emp");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","POTENTIAL_AMOUNT_CANNOT_BE_EMP","Potential amount cannot be emp");
SDK::setLanguageEntry("HelpDesk","ru_ru","Rothoblaas Category","Categoria Prodotto");
SDK::setLanguageEntry("Accounts","ru_ru","Fatturato anno precedente - 1","Fatturato anno precedente - 1");
SDK::setLanguageEntry("APP_LIST_STRINGS","ru_ru","case_relationship_type_default","Contatto Principale");
SDK::setLanguageEntry("Accounts","ru_ru","Secondary Owner","Secondo assegnatario");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_City","Utente: Citta`");
SDK::setLanguageEntry("Accounts","ru_ru","Sistemi Fissaggio","Sistemi Fissaggio");
SDK::setLanguageEntry("Calendar","ru_ru","Private Event","Evento Privato");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_INSERT_INTO_TEMPLATE","Inserisci nel template");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Timecards","Interventi");
SDK::setLanguageEntry("Visitreport","ru_ru","VITI","Viti e chiodi nastrati");
SDK::setLanguageEntry("Visitreport","ru_ru","VITI","Viti strutturali");
SDK::setLanguageEntry("Accounts","ru_ru","PROGANTICAD","PROGETTISTA SPECIALIZZATO SIST");
SDK::setLanguageEntry("HelpDesk","ru_ru","group","gruppo");
SDK::setLanguageEntry("HelpDesk","ru_ru","End SLA","Fine SLA");
SDK::setLanguageEntry("Accounts","ru_ru","Faculty","Facolt&agrave;");
SDK::setLanguageEntry("HelpDesk","ru_ru","Status Changed to","Stato cambiato a");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Annual_Revenue","Lead: Fatturato");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_SELECT_DEL_FOLDER","Seleziona almeno una cartella");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_SELECT_DEL_FOLDER","Seleziona almeno una cartella");
SDK::setLanguageEntry("Contacts","ru_ru","Eng.","Ing");
SDK::setLanguageEntry("HelpDesk","ru_ru","Other Products","Altri Prodotti Collegati");
SDK::setLanguageEntry("HelpDesk","ru_ru","Ticket created. Assigned to","Ticket creato. Assegnato a");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_HTTP_ERR3"," non e' disponibile oppure ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_INVITED_TITLE","Ti piace VTE?");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_INVITED_TITLE","Ti piace VTE?");
SDK::setLanguageEntry("Visitreport","ru_ru","LBL_CUSTOM_INFORMATION","Informazioni Personalizzate");
SDK::setLanguageEntry("Accounts","ru_ru","Social Security number","Codice Fiscale");
SDK::setLanguageEntry("HelpDesk","ru_ru","LBL_SLA","Temipistiche SLA");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_EDIT_BUTTON_ADD_WORKER","Aggiungi Risorsa");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ASSIGNED_TO_ALL","Tutti");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CAL_TO_FILTER","Elenco");
SDK::setLanguageEntry("Contacts","ru_ru","LBL_INSERT_ENTRIE","come nuovo contatto");
SDK::setLanguageEntry("Visitreport","ru_ru","spother","Altre Spese");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_MAP_NAME_CANNOT_BE_EMPTY","Inserire un nome per la mappat");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ALERT_DCLINK_INFO","Tentativo di connessione a Doc");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CAL_TO_FILTER","Elenco");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_CHANGE_ANSWER","Se vuoi cambiare risposta clic");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_MAP_NAME_CANNOT_BE_EMPTY","Inserire un nome per la mappat");
SDK::setLanguageEntry("Accounts","ru_ru","GRUPPIACQ","GRUPPI D'ACQUISTO");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FILTER_OPTIONS","Opzioni filtro");
SDK::setLanguageEntry("HelpDesk","ru_ru","SLA","Gestore SLA");
SDK::setLanguageEntry("Visitreport","ru_ru","ModuleFieldLabel","ModuleFieldLabel Text");
SDK::setLanguageEntry("Accounts","ru_ru","RESPSICUR","RESPONSABILI DELLA SICUREZZA");
SDK::setLanguageEntry("HelpDesk","ru_ru","by","da");
SDK::setLanguageEntry("Accounts","ru_ru","Area espositiva","Area espositiva");
SDK::setLanguageEntry("Visitreport","ru_ru","PIASTRE","Piastre forate");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DUPLICATE_NAME","Il Webform esiste gia'");
SDK::setLanguageEntry("Calendar","ru_ru","Pratica Legale","Pratica legale");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_DUPLICATE_NAME","Il Webform esiste gi�");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SEND_FAX_BUTTON","Fax");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SEND_FAX_BUTTON","Fax");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_Email","Lead: Email");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Title Before Name","Titolo");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_BILLING_ADDRESS","Indirizzo di Fatturazione");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_CLOSE_DATE","Data Chiusura");
SDK::setLanguageEntry("Accounts","ru_ru","LBL_VALUEFROM","Valore per");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_CLOSE_DATE","Data Chiusura");
SDK::setLanguageEntry("HelpDesk","ru_ru","Time remaining","Tempo rimanente");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_NO_EMPTY_FOLDERS","Non ci sono cartelle vuote");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_NO_EMPTY_FOLDERS","Non ci sono cartelle vuote");
SDK::setLanguageEntry("Accounts","ru_ru","Centro di taglio","Centro di taglio");
SDK::setLanguageEntry("Contacts","ru_ru","Contacts Address","Indirizzi dei contatti");
SDK::setLanguageEntry("Visitreport","ru_ru","LBL_SCOPO_INFORMATION","Scopo della Visita");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_GENERATE_NOW","Genera");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_TRANSFER_TO_ACC","Deve essere selezionata un'Azi");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_TRANSFER_TO_ACC","Deve essere selezionata un'Azi");
SDK::setLanguageEntry("HelpDesk","ru_ru","on","il");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NO_PERMISSI","Esiste gia' un'azienda con lo ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_WEBFORMS_DESCRIPTION","Gestione dei Webforms");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_ALERT_EXT_CODE_NO_PERMISSI","Esiste gia' un'azienda con lo ");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_MONTH","Mese");
SDK::setLanguageEntry("Visitreport","ru_ru","DPI","Dpi ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Fax","Azienda: Fax");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_NOBODY","Nessuno");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_AA","un");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_FOLDERS","Cartelle");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_State","Utente: Provincia");
SDK::setLanguageEntry("Visitreport","ru_ru","ourproduct","Interesse per nostri prodotti");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_TimeCard","Intervento");
SDK::setLanguageEntry("Accounts","ru_ru","VAT Registration Number","Partita IVA");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Mobile","Contatto: Cellulare");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Porder No","Numero Ordine di Acquisto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_PROJECT_NAME","Progetto");
SDK::setLanguageEntry("HelpDesk","ru_ru","ProjectTask","Operazione");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","CIVIL_ENGINEERING","Ingegneria Civile");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","New_contact_old_account","import as a new person in sele");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Office_Phone","Contatto: Telefono Ufficio");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_CHANGING_MOTIVATION"," note :");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_CHANGING_MOTIVATION"," note :");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ALERT_DCLINK_ERR","Errore di connessione a Doc Cr");
SDK::setLanguageEntry("Calendar","ru_ru","Open House","Open House");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_SHIPPING_ADDRESS","Indirizzo di Spedizione");
SDK::setLanguageEntry("Accounts","ru_ru","STRUCTURAL_ENGINEERING","Ingegneria Strutturale");
SDK::setLanguageEntry("Accounts","ru_ru","ShowHierarchy","Visualizza gerarchia");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","not_equal","non uguale a");
SDK::setLanguageEntry("Accounts","ru_ru","Trade Show","Fiera");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_AND","e");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Lead_First_Name","Lead: Nome");
SDK::setLanguageEntry("Calendar","ru_ru","LBL_TO_INVITATION","all'invito");
SDK::setLanguageEntry("Accounts","ru_ru","BLOCKHOUSE","BLOCKHAUS");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Contact_Department","Contatto: Dipartimento");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","User_Street","Utente: Via");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","EventMeeting","Event/Meeting");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_BACK_TO_TOP","Torna su");
SDK::setLanguageEntry("Visitreport","ru_ru","Visitreport","Report Visite");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","PLEASE_SELECT_PRODUCT","Prego selezionare un Prodotto");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_INSCRIBED_HOUR","Ore iscritte");
SDK::setLanguageEntry("Visitreport","ru_ru","visitnote","Note Visita");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","NO_RULES_FOUND","Nessuna regola trovata per que");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_PLEASE_SELECT_A_MOD","Scegliere un modulo");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","NO_RULES_FOUND","Nessuna regola trovata per que");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","LBL_STATUS_PLEASE_SELECT_A_MOD","Scegliere un modulo");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","KLIMAHOUSE 2014 BZ","Fiera KLIMAHOUSE 2014 Bolzano");
SDK::setLanguageEntry("Accounts","ru_ru","Data Importazione Semiramis","Data Importazione Semiramis");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_MASS_UPDATE_QUESTION","Procedere con l'aggiornamento ");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_MENU_MAX","Massimizza menu");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ANN","un");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_CONTACT","Selezionare il Contatto per pr");
SDK::setLanguageEntry("ALERT_ARR","ru_ru","ERR_SELECT_CONTACT","Selezionare il Contatto per pr");
SDK::setLanguageEntry("Accounts","ru_ru","Prospect Accounts","Aziende prospect");
SDK::setLanguageEntry("Visitreport","ru_ru","CATFIX","Catalogo rothofixing");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","Account_Phone","Azienda: Telefono");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","LBL_ASSIGNED_TO_OTHERS","Agli Altri");
SDK::setLanguageEntry("Visitreport","ru_ru","CHIODIVITIGRAFFE","Chiodi viti e graffe");
SDK::setLanguageEntry("Visitreport","ru_ru","04 ANTICAD","04 - Sistemi anticaduta");
SDK::setLanguageEntry("HelpDesk","ru_ru","High Prioriy Tickets","Ticket prioritari");
SDK::setLanguageEntry("APP_STRINGS","ru_ru","ActuallDuplicate","Existing possible duplicates:");
SDK::setLanguageEntry("Accounts","ru_ru","RIVELEGNAME","RIVENDITORE LEGNAME");

?>
