<?php
include_once('../../config.inc.php');
chdir($root_directory);
require_once('include/utils/utils.php');
include_once('vtlib/Vtiger/Module.php');
$Vtiger_Utils_Log = true;
global $adb, $table_prefix;
session_start();

//Turn on debugging level
$Vtiger_Utils_Log = true;
include_once('vtlib/Vtiger/Menu.php');
include_once('vtlib/Vtiger/Module.php');
//danzi.tn@20141212 nova classificazione cf_762 sostituito con vtiger_account.account_line
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'AMMINISTRCOND' ,'Amministratori Di Condominio');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'CARPENTERIA' ,'Carpenteria');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'CARPMET' ,'Carpenteria Metallica');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'CASE IN LEGNO' ,'Case In Legno');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'CONCIATETTO' ,'Conciatetto');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'EDIFICI IN LEGNO' ,'Edifici In Legno');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'ENTEPUBB' ,'Ente Pubblico');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'FACCIATE E RIVESTIMENTI' ,'Facciate E Rivestimenti');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'FALEGNAME/SERRAMENTISTA' ,'Falegname/Serramentista');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'FERRAMENTA E ATTREZZATURE' ,'Ferramenta E Attrezzature');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'GDO' ,'GDO');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'GENERAL CONTRACTOR / IMMOBILIARE' ,'General Contractor / Immobiliare');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'GRANDI STRUTTURE' ,'Grandi Strutture');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'GROSSISTA' ,'Grossista');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'IMPERM' ,'Impermeabilizzazione Edile E Isolazione Per Edilizia');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'IMPIANTISTI' ,'Impiantisti');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'IMPEDILE' ,'Impresa Edile');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'INDEXTRALEGNO' ,'Industria Extra Legno');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'LATTONERIA' ,'Lattoneria');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'MONTANTICAD' ,'Montatore Linee Vita');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'ORDINI CATEGORIA/ASSOCIAZIONI' ,'Ordini Categoria/Associazioni');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'PICCOLE STRUTTURE' ,'Piccole Strutture');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'PRODUTTORI LAMELLARE' ,'Produttori Lamellare');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'RIVENDITA LEGNAME / SEGHERIA CHE FA LAVORI' ,'Rivendita Legname / Segheria Che Fa Lavori');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'RIVEMATED' ,'Rivendita Materiali Edili');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'RIVENDITA SPECIALIZZATA SETTORE CARPENTERIA' ,'Rivendita Specializzata Settore Carpenteria');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'RIVENDITE SISTEMI ANTICADUTA' ,'Rivendite Sistemi Anticaduta');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'RIVENDITA LEGNAME / SEGHERIA (NON FA LAVORI)' ,'Rivenditore Di Legname / Segheria (NON Fa Lavori)');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'SCUOLEPROF' ,'Scuole Professionali');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'AMIANTO' ,'Smaltimento Amianto');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'ARCH.' ,'Studio Architettura');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'GEOM.' ,'Studio Geometra');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'ING.' ,'Studio Ingegneria');
SDK::setLanguageEntry('APP_STRINGS' ,'it_it' ,'UNIVERSITA' ,'Universita E Ricerca');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'AMMINISTRCOND' ,'Asbestentsorgung');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'CARPENTERIA' ,'Zimmerei');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'CARPMET' ,'Metallbau');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'CASE IN LEGNO' ,'Holzhaeuser');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'CONCIATETTO' ,'Dachdecker');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'EDIFICI IN LEGNO' ,'Holzgebaeude');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'ENTEPUBB' ,'	Oeffentliche Einrichtung');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'FACCIATE E RIVESTIMENTI' ,'Terrassen Und Fassaden');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'FALEGNAME/SERRAMENTISTA' ,'Tischler/Bautischler');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'FERRAMENTA E ATTREZZATURE' ,'Eisenwaren/Werkzeug');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'GDO' ,'Organisierter Grossverteiler');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'GENERAL CONTRACTOR / IMMOBILIARE' ,'Immobilienagentur');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'GRANDI STRUTTURE' ,'Grosse Strukturen');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'GROSSISTA' ,'Grosshaendler');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'IMPERM' ,'Abdichtung');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'IMPIANTISTI' ,'Installateur');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'IMPEDILE' ,'Bauunternehmen');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'INDEXTRALEGNO' ,'Industrie Ausser Holz');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'LATTONERIA' ,'Spengler');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'MONTANTICAD' ,'Absturzsicherung Monteur');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'ORDINI CATEGORIA/ASSOCIAZIONI' ,'Verbaende');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'PICCOLE STRUTTURE' ,'Kleine Strukturen');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'PRODUTTORI LAMELLARE' ,'Leimholz Industrie');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'RIVENDITA LEGNAME / SEGHERIA CHE FA LAVORI' ,'Holzhaendler Mit Zimmerei');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'RIVEMATED' ,'Baustoffhaendler');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'RIVENDITA SPECIALIZZATA SETTORE CARPENTERIA' ,'Spezialisiert Auf Zimmerei');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'RIVENDITE SISTEMI ANTICADUTA' ,'Absturzsicherung');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'RIVENDITA LEGNAME / SEGHERIA (NON FA LAVORI)' ,'Holzhaendler/Saegewerkholzhaendler/Saegewerk');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'SCUOLEPROF' ,'Berufsschulen');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'AMIANTO' ,'Asbestentsorgung');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'ARCH.' ,'Architekturbüro');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'GEOM.' ,'Geometer');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'ING.' ,'Bauingenieurbüro');
SDK::setLanguageEntry('APP_STRINGS' ,'de_de' ,'UNIVERSITA' ,'Universitaet Und Forschungsinstitut');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'AMMINISTRCOND' ,'Administrateurs De Condominium');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'CARPENTERIA' ,'Charpenterie');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'CARPMET' ,'Menuiserie Metallique');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'CASE IN LEGNO' ,'Maisons');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'CONCIATETTO' ,'Couvreur');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'EDIFICI IN LEGNO' ,'Batiment Bois');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'ENTEPUBB' ,'Institution Public');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'FACCIATE E RIVESTIMENTI' ,'Facades Et Revetements');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'FALEGNAME/SERRAMENTISTA' ,'Menuiserie');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'FERRAMENTA E ATTREZZATURE' ,'Quincallerie Et Outillage');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'GDO' ,'Gsb');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'GENERAL CONTRACTOR / IMMOBILIARE' ,'Immobilier');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'GRANDI STRUTTURE' ,'Grand Structures');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'GROSSISTA' ,'Grossiste');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'IMPERM' ,'Impermeabilisation');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'IMPIANTISTI' ,'Installateurs');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'IMPEDILE' ,'Entreprise De Construction');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'INDEXTRALEGNO' ,'Industrie Extra-Bois');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'LATTONERIA' ,'Ferblanterie');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'MONTANTICAD' ,'Monteures Ligne De Vie');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'ORDINI CATEGORIA/ASSOCIAZIONI' ,'Association');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'PICCOLE STRUTTURE' ,'Structures L&egrave;g&eacute;res');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'PRODUTTORI LAMELLARE' ,'Fabricant De Lamelle Colle');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'RIVENDITA LEGNAME / SEGHERIA CHE FA LAVORI' ,'Distributeur De Bois/Scierie (AUSSI Charpente)');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'RIVEMATED' ,'Revente Mat&egrave;riaux De Construction');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'RIVENDITA SPECIALIZZATA SETTORE CARPENTERIA' ,'Distributeur Specialise En Charpenterie');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'RIVENDITE SISTEMI ANTICADUTA' ,'Distributeur Systemes Antichute');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'RIVENDITA LEGNAME / SEGHERIA (NON FA LAVORI)' ,'Distributeur De Bois/Scierie (NO Charpente)');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'SCUOLEPROF' ,'&Egrave;coles Professionnelles');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'AMIANTO' ,'Elimination De L\'amiante');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'ARCH.' ,'Architecture');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'GEOM.' ,'G&egrave;om&eacute;tre');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'ING.' ,'Ing&egrave;nierie');
SDK::setLanguageEntry('APP_STRINGS' ,'fr_fr' ,'UNIVERSITA' ,'Universit&egrave; Et Recherche');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'AMMINISTRCOND' ,'Condominium Administrator');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'CARPENTERIA' ,'Carpentry');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'CARPMET' ,'Metal Carpentry');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'CASE IN LEGNO' ,'Wooden Houses');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'CONCIATETTO' ,'Roofer');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'EDIFICI IN LEGNO' ,'Wooden Buildings');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'ENTEPUBB' ,'Public Institution');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'FACCIATE E RIVESTIMENTI' ,'Terraces Facades');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'FALEGNAME/SERRAMENTISTA' ,'Joiner');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'FERRAMENTA E ATTREZZATURE' ,'Hardware And Equipment');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'GDO' ,'Diy');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'GENERAL CONTRACTOR / IMMOBILIARE' ,'General Contractor/Real Estate');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'GRANDI STRUTTURE' ,'Big Structures');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'GROSSISTA' ,'Wholesaler');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'IMPERM' ,'Waterproofing');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'IMPIANTISTI' ,'Installer');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'IMPEDILE' ,'Building Firm');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'INDEXTRALEGNO' ,'Industry Extra Wood');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'LATTONERIA' ,'Tinsmith Industry');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'MONTANTICAD' ,'Fall Protection Assembler');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'ORDINI CATEGORIA/ASSOCIAZIONI' ,'Associations');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'PICCOLE STRUTTURE' ,'Small Structures');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'PRODUTTORI LAMELLARE' ,'Clt Producer');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'RIVENDITA LEGNAME / SEGHERIA CHE FA LAVORI' ,'Timber Dealer With Carpentry');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'RIVEMATED' ,'Building Material Retailer');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'RIVENDITA SPECIALIZZATA SETTORE CARPENTERIA' ,'Specialized Carpentry Retailer');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'RIVENDITE SISTEMI ANTICADUTA' ,'Fall Protection Retailer');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'RIVENDITA LEGNAME / SEGHERIA (NON FA LAVORI)' ,'Timber Dealer/Sawmill');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'SCUOLEPROF' ,'Professional Schools');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'AMIANTO' ,'Disposalof Asbetos');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'ARCH.' ,'Architecture Bureau');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'GEOM.' ,'Building Surveyor');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'ING.' ,'Engineering Bureau');
SDK::setLanguageEntry('APP_STRINGS' ,'en_us' ,'UNIVERSITA' ,'Universities And Research');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'AMMINISTRCOND' ,'Administradores De Condominio');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'CARPENTERIA' ,'Carpinteria');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'CARPMET' ,'Carpenteria Metalica');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'CASE IN LEGNO' ,'Casas De Madera');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'CONCIATETTO' ,'Techador');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'EDIFICI IN LEGNO' ,'Edificios De Madera');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'ENTEPUBB' ,'Ente Publico');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'FACCIATE E RIVESTIMENTI' ,'Terrazas Y Fachadas');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'FALEGNAME/SERRAMENTISTA' ,'Ebanista');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'FERRAMENTA E ATTREZZATURE' ,'Ferreteria Y Equipo');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'GDO' ,'GDO');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'GENERAL CONTRACTOR / IMMOBILIARE' ,'General Contractor/Inmobiliaria');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'GRANDI STRUTTURE' ,'Estructuras Grandes');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'GROSSISTA' ,'Mayorista');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'IMPERM' ,'Impermeabilizacion Y Aislamiento');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'IMPIANTISTI' ,'Instaladores');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'IMPEDILE' ,'Empresa De Construccion');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'INDEXTRALEGNO' ,'Industria Extra Madera');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'LATTONERIA' ,'Hojalateria');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'MONTANTICAD' ,'Montadores Lineas De Vida');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'ORDINI CATEGORIA/ASSOCIAZIONI' ,'Asociacion');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'PICCOLE STRUTTURE' ,'Estructuras Pequenas');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'PRODUTTORI LAMELLARE' ,'Productor De Madera');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'RIVENDITA LEGNAME / SEGHERIA CHE FA LAVORI' ,'Distribuidor De Madera/Carpinteria');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'RIVEMATED' ,'Reventa Materiales De Construccion');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'RIVENDITA SPECIALIZZATA SETTORE CARPENTERIA' ,'Distribuidor Especializado En Carpinteria');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'RIVENDITE SISTEMI ANTICADUTA' ,'Reventa Sistemas Anticaidas');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'RIVENDITA LEGNAME / SEGHERIA (NON FA LAVORI)' ,'Distribuidor De Madera/Serreria');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'SCUOLEPROF' ,'Escuelas Profesionales');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'AMIANTO' ,'Eliminacion Amianto');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'ARCH.' ,'Estudio Arquitectura');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'GEOM.' ,'Estudio Aparejador');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'ING.' ,'Estudio Ingenieria');
SDK::setLanguageEntry('APP_STRINGS' ,'es_es' ,'UNIVERSITA' ,'Universidad Y  Investigacion');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'AMMINISTRCOND' ,'Administradores De Condominio');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'CARPENTERIA' ,'Carpintaria');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'CARPMET' ,'Carpintaria Metmet&aacute;lica');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'CASE IN LEGNO' ,'Casas De Madeira');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'CONCIATETTO' ,'Telhador');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'EDIFICI IN LEGNO' ,'Imoveis Em Madeira');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'ENTEPUBB' ,'Entidade Publica');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'FACCIATE E RIVESTIMENTI' ,'Faces E Tarracos');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'FALEGNAME/SERRAMENTISTA' ,'Ebanista');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'FERRAMENTA E ATTREZZATURE' ,'Ferragens E Equipamentos');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'GDO' ,'GDO');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'GENERAL CONTRACTOR / IMMOBILIARE' ,'Imobili&aacute;ria/Empreitero General');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'GRANDI STRUTTURE' ,'Grande Estruturas');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'GROSSISTA' ,'Atacado');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'IMPERM' ,'Impermeabilizacao E Isolamento');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'IMPIANTISTI' ,'Instalador');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'IMPEDILE' ,'Empresa De Construcao');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'INDEXTRALEGNO' ,'Industria Extra Madeira');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'LATTONERIA' ,'Latoaria');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'MONTANTICAD' ,'Instalador Linha De Vida');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'ORDINI CATEGORIA/ASSOCIAZIONI' ,'Associacao');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'PICCOLE STRUTTURE' ,'Pequenas Estruturas');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'PRODUTTORI LAMELLARE' ,'Produtores De Madeira');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'RIVENDITA LEGNAME / SEGHERIA CHE FA LAVORI' ,'Revenda De Madeira/Carpintaria');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'RIVEMATED' ,'Revenda De Materiais De Construcao');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'RIVENDITA SPECIALIZZATA SETTORE CARPENTERIA' ,'Distribuidor Especializado Em Carpintaria');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'RIVENDITE SISTEMI ANTICADUTA' ,'Revenda Sistemas De Proteccao');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'RIVENDITA LEGNAME / SEGHERIA (NON FA LAVORI)' ,'Revenda De Madeira/Serracao');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'SCUOLEPROF' ,'Escuelas Profesionales');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'AMIANTO' ,'Eliminacao Do Amianto');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'ARCH.' ,'Estudo De Arquitetura');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'GEOM.' ,'Estudo De Aparelhador');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'ING.' ,'Estudo De Engenharia');
SDK::setLanguageEntry('APP_STRINGS' ,'pt_pt' ,'UNIVERSITA' ,'Universidad Y Investigacion');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'AMMINISTRCOND' ,'Кондоминиум Администратора');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'CARPENTERIA' ,'Покрытия');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'CARPMET' ,'Металлоконструкции');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'CASE IN LEGNO' ,'Деревянные Дома');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'CONCIATETTO' ,'Кро́вельщик');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'EDIFICI IN LEGNO' ,'Imoveis Em Madeira');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'ENTEPUBB' ,'Государственное Учреждение');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'FACCIATE E RIVESTIMENTI' ,'Террасы Фасады');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'FALEGNAME/SERRAMENTISTA' ,'Столя́р');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'FERRAMENTA E ATTREZZATURE' ,'Скобяны́е Изде́лия Е Инструменты');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'GDO' ,'Diy');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'GENERAL CONTRACTOR / IMMOBILIARE' ,'Генеральный Подрядчик');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'GRANDI STRUTTURE' ,'Большой Структуры');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'GROSSISTA' ,'Оптовиков');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'IMPERM' ,'Гидроизоляционные');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'IMPIANTISTI' ,'Установки');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'IMPEDILE' ,'Строительная Фирма');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'INDEXTRALEGNO' ,'Промышленность Не Лес');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'LATTONERIA' ,'Жестя́ник');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'MONTANTICAD' ,'Сборщиков Линии Жизни');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'ORDINI CATEGORIA/ASSOCIAZIONI' ,'Ассоциация');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'PICCOLE STRUTTURE' ,'Маленькие Структуры');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'PRODUTTORI LAMELLARE' ,'Изготови́тель Лес');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'RIVENDITA LEGNAME / SEGHERIA CHE FA LAVORI' ,'Продаве́ц Древеси́на/Покрытия');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'RIVEMATED' ,'Продажи Строительные Материалы');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'RIVENDITA SPECIALIZZATA SETTORE CARPENTERIA' ,'Специалист По Железу');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'RIVENDITE SISTEMI ANTICADUTA' ,'Падение Продажи Системы Защиты');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'RIVENDITA LEGNAME / SEGHERIA (NON FA LAVORI)' ,'Продаве́ц Древеси́на/Лесопи́льный Заво́д');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'SCUOLEPROF' ,'Профессиональные Школы');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'AMIANTO' ,'Удаление Асбест');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'ARCH.' ,'Студия Архитектуры');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'GEOM.' ,'Студия Инспектор');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'ING.' ,'Исследование Техники');
SDK::setLanguageEntry('APP_STRINGS' ,'ru_ru' ,'UNIVERSITA' ,'Университетами И Исследовательскими');


?>