//crmv@17001
// danzi.tn@20151125 traduzioni JS
var i18n = jQuery.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dim",
            "mon": "Mon",
            "tue": "Mar",
            "wed": "Mer",
            "thu": "Jeu",
            "fri": "Ven",
            "sat": "Sam",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Avr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Aou",
            "sep": "Sep",
            "oct": "Oct",
            "nov": "Nov",
            "dec": "Dec"
        },
        "no_implemented": "No implemented yet",
        "to_date_view": "Click to the view of current date",
        "i_undefined": "Undefined",
        "allday_event": "All day event",
        "repeat_event": "Repeat event",
        "time": "Time",
        "event": "Évènement",
        "location": "Location",
        "participant": "Participant",
        "get_data_exception": "Exception when getting data",
        "new_event": "Nouvel évènement",
        "confirm_delete_event": "Do you confirm to delete this event? ",
        "confrim_delete_event_or_all": "Do you want to all repeat events or only this event? \r\nClick [OK] to delete only this event, click [Cancel] delete all events",
        "data_format_error": "Data format error! ",
        "invalid_title": "Event title can not be blank or contains ($<>)",
        "view_no_ready": "View is not ready",
        "example": "",
        "content": "Nom/Sujet",
        "event_type": "Type &eacute;v&egrave;nement",	
        "event_description": "Description",
        "event_location": "Lieu",
        "event_related_to": "Connecter &agrave;",
        "create_event": "Nouvel &eacute;v&egrave;nement",
        "update_detail": "Modifier &eacute;v&egrave;nement",
        "click_to_detail": "Voir &eacute;v&egrave;nement",
        "i_delete": "Delete",
        "day_plural": "days",
        "others": "Others",
        "item": "",
        "Ok": "Ok",
        "Cancel": "Cancel",
        "save": "Sauvegarder",
        "relate": "Connecter à",
        "invite": "Inviter qqn",
        "LBL_EDIT": "Modifier",
        "LBL_CREATEVISTREPORT_BTN": "Nouvel rapporte de visite",
        "LBL_CREATEVISTREPORT_ERROR": "Pas de rapporte de visite est disponible pour ce type d'événement",
        "i_close": "Conclure activité", //crmv@22577
        //crmv@vte10usersFix
        "buttonTaskShow" : "Mostra Compiti Completati",
        "buttonTaskHide" : "Nascondi Compiti Completati",
        //crmv@vte10usersFix
        //crmv@26030m
        "task": "Tâche",
        "create_task": "Nouvel Tâche",
        "task_content": "Nom de la tâche",
        //crmv@26030me
        'LBL_ASSIGNED_TO': 'attribu&eacute; &agrave;'	//crmv@24270
    }
});
//crmv@17001e