//crmv@17001
var i18n = jQuery.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "d L yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W d/M",
            "Md3": "d L",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "Dom",
            "mon": "Seg",
            "tue": "Ter",
            "wed": "Qua",
            "thu": "Qui",
            "fri": "Sex",
            "sat": "Sab",
            "jan": "Jan",
            "feb": "Fev",
            "mar": "Mar",
            "apr": "Abr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Ago",
            "sep": "Set",
            "oct": "Out",
            "nov": "Nov",
            "dec": "Dez"
        },
        "no_implemented": "Não foi ainda instalado",
        "to_date_view": "Clicar para visualizar a data atual",
        "i_undefined": "Não definido",
        "allday_event": " Todo o dia",
        "repeat_event": "Repetir evento",
        "time": "Data",
        "event": "Evento",
        "location": "Lugar",
        "participant": "Participante",
        "get_data_exception": "Exception when getting data",
        "new_event": "Novo evento",
        "confirm_delete_event": "Você tem certeza que deseja excluir este evento?",
        "confrim_delete_event_or_all": "Você tem certeza que deseja apagar todos os eventos repetidos ou somente este? \r\nClicar [OK] para cancelar somente este evento, clicar [Cancel] para apagar todos os eventos",
        "data_format_error": "Formato data errado! ",
        "invalid_title": "Omitido o nome do evento",
        "view_no_ready": "View is not ready",
        "example": "",
        "content": "Nome Evento",
        "event_type": "Tipo Evento",
        "event_description": "Descrição",
        "event_location": "Lugar",
        "event_related_to": "Relacionado a",
        "create_event": "Criar evento",
        "click_to_detail": "Visualizar detalhes",
        "i_delete": "Apagar",
        "day_plural": "dias",
        "others": "Outros",
        "item": "",
        "Ok": "Ok",
        "Cancel": "Cancel",
        //crmv@vte10usersFix
        "buttonTaskShow" : "Mostrar Tarefas Concluídas",
        "buttonTaskHide" : "Ocultar Tarefas Concluídas",
        //crmv@vte10usersFix
        "i_close": "Fechar atividade;",	//crmv@22577
		//crmv@26807
		"update_detail": "Detalhe",
		"save": "Salvar",
		"relate": "Relacionado",
		"invite": "Convidar",
		"LBL_EDIT": "Editar",
        "LBL_CREATEVISTREPORT_BTN": "New Visit Report",
        "LBL_CREATEVISTREPORT_ERROR": "No visit report available for this type of event",
		//crmv@26807e
		//crmv@26030m
		"task": "Tarefa",
		"task_content": "Nome Tarefa",
		"create_task": "Criar tarefa",
		//crmv@26030me
		'LBL_ASSIGNED_TO': 'Atribuído a'	//crmv@24270
    }
});
//crmv@17001e