//crmv@17001
var i18n = jQuery.extend({}, i18n || {}, {
    xgcalendar: {
        dateformat: {
            "fulldaykey": "MMddyyyy",
            "fulldayshow": "L d yyyy",
            "fulldayvalue": "M/d/yyyy",
            "Md": "W M/d",
            "Md3": "L d",
            "separator": "/",
            "year_index": 2,
            "month_index": 0,
            "day_index": 1,
            "day": "d",
            "sun": "So",
            "mon": "Mo",
            "tue": "Di",
            "wed": "Mi",
            "thu": "Do",
            "fri": "Fr",
            "sat": "Sa",
            "jan": "Jan",
            "feb": "Feb",
            "mar": "Mär",
            "apr": "Apr",
            "may": "Mai",
            "jun": "Jun",
            "jul": "Jul",
            "aug": "Aug",
            "sep": "Sep",
            "oct": "Okt",
            "nov": "Nov",
            "dec": "Dez"
        },
        "no_implemented": "noch nicht verfügbar",
        "to_date_view": "Klicke um das Datum einzusehen",
        "i_undefined": "Nicht definiert",
        "allday_event": "Ganztags Ereignis",
        "repeat_event": "Ereignis Wiederholung",
        "time": "Zeit",
        "event": "Ereignis",
        "location": "Ort",
        "participant": "Teilnehmer",
        "get_data_exception": "Ausnahme bei Datenübertragung",
        "new_event": "Neues Ereignis",
        "confirm_delete_event": "Bestätigen Sie die Löschung dieses Ereignisses",
        "confrim_delete_event_or_all": "Möchten Sie alle Ereignisse wiederholen oder ausschließlich dieses? \r\n Klicken Sie [OK], um ausschließlich dieses ereignis zu löschen , Klicken Sie [Cancel], um alle Ereignisse zu löschen",
        "data_format_error": "Fehler beim Datenformat",
        "invalid_title": "Ereignistitel kann nicht lehr sein oder enthalten ($<>)",
        "view_no_ready": "Einblick nicht bereit",
        "example": "",
        "content": "Ereignisname",
        "event_type": "EreignisTyp",
        "event_description": "Beschreibung",
        "event_location": "Ort",
        "event_related_to": "Verbunden mit",
        "create_event": "Ereignis erstellen",
    	//crmv@26807
        "update_detail": "Detail",
        "save": "Speichern",
        "relate": "Verbinden mit",
        "invite": "Einladung schicken",
        "LBL_EDIT": "Bearbeiten",
        "LBL_CREATEVISTREPORT_BTN": "New Visit Report",
        "LBL_CREATEVISTREPORT_ERROR": "No visit report available for this type of event",
        //crmv@26807e
        "click_to_detail": "Details einsehen",
        "i_delete": "Löschen",
        "day_plural": "Tage",
        "others": "Andere",
        "item": "",
        "Ok": "Ok",
        "Cancel": "Löschen",
        //crmv@vte10usersFix
        "buttonTaskShow" : "Abgeschlossene Aufgabe einblenden",
        "buttonTaskHide" : "Abgeschlossene Aufgabe ausblenden",
        //crmv@vte10usersFix
        //crmv@26030m
        "task": "Aufgabe",
        "task_content": "Aufgabenname",
        "create_task": "Aufgabe erstellen",
        //crmv@26030me
        "i_close": "Tätigkeit schliessen", //crmv@22577
        'LBL_ASSIGNED_TO': "Zugewiesen zu"	//crmv@24270
    }
});
//crmv@17001e