
DECLARE @DTMIN VARCHAR(8);
DECLARE @DTMAX VARCHAR(8);

SET @DTMIN = CONVERT(VARCHAR(8),DATEADD(month,-1,GETDATE()), 112);
SET @DTMAX = CONVERT(VARCHAR(8), GETDATE(), 112);

SELECT A.[MESE]
      ,A.[CLIENTE_DESTINAZIONE_NUMERO]
      ,A.[CLIENTE_FATTURAZIONE_NUMERO]
      ,A.[ARTICOLO_CODE]
      ,A.[ORDINE_DATA]
      ,A.[ORDINE_TIPO]
      ,B.[DESCRIZIONE]
      ,A.[ORDINE_NUMERO]
      ,A.[ORDINE_RIGA]
      ,A.[FATTURATO_NETTO]
      ,A.[FATTURATO_LORDO]
      ,A.[QUANTITA]
      ,A.[DATA_NOTA]
      ,A.[NUMERO_QUERY],
      CASE 
		WHEN A.SCONTO1_TYPE = 3 THEN (cast(FLOOR(SCONTO1_VALUE) AS varchar(10)) + '%')
		WHEN A.SCONTO1_TYPE = 2 THEN (cast(SCONTO1_VALUE AS varchar(10)))
		ELSE ''
	  END AS SCONTO1,
	  CASE 
		WHEN A.SCONTO2_TYPE = 3 THEN (cast(FLOOR(SCONTO2_VALUE) AS varchar(6)) + '%')
		WHEN A.SCONTO2_TYPE = 2 THEN (cast(SCONTO2_VALUE AS varchar(6)))
		ELSE ''
	  END AS SCONTO2,
	   CASE WHEN A.QUANTITA=0 THEN NULL
			WHEN A.QUANTITA IS NULL THEN NULL
		    ELSE A.FATTURATO_NETTO/A.QUANTITA 
	   END AS PREZZO_UNITARIO,
	A.[ORDINE_UPDATEDATE]
  FROM [ROTHOBLAAS01].[dbo].[ROTHO_QV_A001] A
  inner join [ROTHOBLAAS01].[dbo].[ROTHO_QV_B026] B
  on A.[ORDINE_TIPO] = B.CODICE
  WHERE
  A.ORDINE_UPDATEDATE BETWEEN @DTMIN AND @DTMAX 
  ORDER BY ORDINE_NUMERO, ORDINE_RIGA;