
CREATE TABLE tmp_type_from_subcat (
	account_main_activity VARCHAR(50) NULL DEFAULT NULL,
	subcat VARCHAR(50) NOT NULL DEFAULT NULL,
	subname VARCHAR(50) NULL DEFAULT NULL,
	account_client_type VARCHAR(50) NULL DEFAULT NULL,
	subfield VARCHAR(50) NULL DEFAULT NULL,
	oldcat VARCHAR(50) NULL DEFAULT NULL
);