/***********************************************************
*  Module       : JavaScript
*  Language     : ES Spanish
*  Version      : vt5.4.0
*  Created Date : 2008-01-18 17:46:07
*  Author       : JPL TSolucio, S.L.  -  rasomu
*  Last change  : 2012-03-15
*  Author       : Joe Bordes JPL TSolucio, S.L.
***********************************************************/

var alert_arr = {
      'DELETE':'¿Borrar los ',
      'RECORDS':' registros?',
      'SELECT':'Introduzca, al menos, una entidad',
      'DELETE_ACCOUNT':'Borrar esta cuenta eliminará las Oportunidades y Presupuestos que tenga asociadas. ¿Continuar borrando los ',
      'DELETE_VENDOR':'Borrar este proveedor eliminará las Ordenes de Compra que tenga Asociadas. ¿Continuar borrando los ',
      'SELECT_MAILID':'Seleccione un Email Id',
      'OVERWRITE_EXISTING_ACCOUNT1':'¿Sobreescribir la dirección existente con la dirección de la cuenta seleccionada (',
      'OVERWRITE_EXISTING_ACCOUNT2':')?',
      'OVERWRITE_EXISTING_CONTACT1':'¿Sobreescribir la dirección existente con la dirección del contacto seleccionado (',
      'OVERWRITE_EXISTING_CONTACT2':')?',
      'MISSING_FIELDS':'Faltan Campos Obligatorios:',
      'NOT_ALLOWED_TO_EDIT':'no está autorizado a editar este campo',
      'NOT_ALLOWED_TO_EDIT_FIELDS':'no está autorizado a editar los campos',
      'COLUMNS_CANNOT_BE_EMPTY':'Las Columnas seleccionadas no pueden estar vacias',
      'CANNOT_BE_EMPTY':' no puede estar vacia',
      'CANNOT_BE_NONE':' no puede ser ninguno',
      'ENTER_VALID':'Seleccione un válido ',
      'SHOULDBE_LESS':' debe ser menor que ',
      'SHOULDBE_LESS_EQUAL':' debe ser menor o igual a',
      'SHOULDBE_EQUAL':' debe ser igual a ',
      'SHOULDBE_GREATER':' debe ser mayor que ',
      'SHOULDBE_GREATER_EQUAL':' debe ser mayor o igual a ',
      'INVALID':'Inválido ',
	'VISITREPORTNOTHINGFOUND':'Invalid calendar entry',
	'VISITREPORTWRONGTYPE':'Invalid Event Type or Account', 
      'EXCEEDS_MAX':' Supera el límite máximo ',
      'OUT_OF_RANGE':' está fuera de rango',
      'SHOULDNOTBE_EQUAL':' no debe ser igual a ',
      'PORTAL_PROVIDE_EMAILID':'Usuario del portal debe tener un email válido',
      'ADD_CONFIRMATION':'¿Añadir los seleccionados ',
      'ACCOUNTNAME_CANNOT_EMPTY':'El nombre de cuenta no puede estar vacío',
      'CANT_SELECT_CONTACTS':'No puede seleccionar contactos relacionados desde un Pre-Contacto',
      'LBL_THIS':'Este ',
      'DOESNOT_HAVE_MAILIDS':' no tiene email',
      'ARE_YOU_SURE':'¿Seguro?',
      'DOESNOT_HAVE_AN_MAILID':'" no tiene email',
      'MISSING_REQUIRED_FIELDS':'Faltan Campos Obligatorios: ',
      'READONLY':'Es de solo lectura',
      'SELECT_ATLEAST_ONE_USER':'Seleccione un usuario, al menos',
      'DISABLE_SHARING_CONFIRMATION':'Desactivar compartidos para los usuarios seleccionados ',
      'USERS':' ?',
      'ENDTIME_GREATER_THAN_STARTTIME':'La hora de finalización debe ser posterior a la de inicio ',
      'FOLLOWUPTIME_GREATER_THAN_STARTTIME':'La hora de repetición debe ser posterior a la de finalización ',
      'MISSING_EVENT_NAME':'Falta nombre del Evento',
      'EVENT_TYPE_NOT_SELECTED':'No ha seleccionado Tipo de Evento',
      'CLOSEDATE_CANNOT_BE_EMPTY':'La Fecha de Cierre no puede estar vacía',
      'SITEURL_CANNOT_BE_EMPTY':'La Dirección Web no puede estar vacía',
      'SITENAME_CANNOT_BE_EMPTY':'La Página Web no puede estar vacía',
      'LISTPRICE_CANNOT_BE_EMPTY':'La Tarifa no puede estar vacía',
      'INVALID_LIST_PRICE':'Tarifa Inválida',
      'PROBLEM_ACCESSSING_URL':'Problema accediendo a la URL: ',
      'CODE':' Código: ',
      'WISH_TO_QUALIFY_MAIL_AS_CONTACT':'¿Quiere calificar este email como contacto?',
      'SELECT_ATLEAST_ONEMSG_TO_DEL':'Seleccione, al menos, un email para borrar',
      'ERROR':'Error',
      'FIELD_TYPE_NOT_SELECTED':'Tipo de Campo no seleccionado',
      'SPECIAL_CHARACTERS_NOT_ALLOWED':'No se admiten caracteres especiales en el campo Etiqueta',
      'SPECIAL_CHARACTERS':'Caracteres especiales',
      'NOT_ALLOWED':'no estan permitidos. Intenta con otros valores.',
      'PICKLIST_CANNOT_BE_EMPTY':'El Valor del Desplegable no puede estar vacío',
      'DUPLICATE_VALUES_FOUND':'Encontrados Valores Duplicados',
      'DUPLICATE_MAPPING_ACCOUNTS':'¡Asignación Duplicada en Cuentas!',
      'DUPLICATE_MAPPING_CONTACTS':'¡Asignación Duplicada en Contactos!',
      'DUPLICATE_MAPPING_POTENTIAL':'¡Asignación Duplicada en Oportunidades!',
      'ERROR_WHILE_EDITING':'Error Editando',
      'CURRENCY_CHANGE_INFO':'Cambio de Moneda Realizado correctamente',
      'CURRENCY_CONVERSION_INFO':'¿Está usando el Dolar como moneda? \n Pulse OK para mantener $, Cancelar para cambiar el ratio de conversión.',
      'THE_EMAILID':'El email id \\\'',
      'EMAIL_FIELD_INVALID':'\\\' en el campo email es inválido',
      'MISSING_REPORT_NAME':'Falta el Nombre del Informe',
      'REPORT_NAME_EXISTS':'El nombre del informe existe, use otro...',
      'WANT_TO_CHANGE_CONTACT_ADDR':'¿Cambiar las direcciones de los Contactos relacionados con esta Cuenta?',
      'SURE_TO_DELETE':'¿Borrar?',
      'NO_PRODUCT_SELECTED':'No hay productos seleccionados, Elija uno.',
      'VALID_FINAL_PERCENT':'Introduzca un Porcentaje de Descuento válido',
      'VALID_FINAL_AMOUNT':'Introduzca un Importe Final válido',
      'VALID_SHIPPING_CHARGE':'Introduzca un Cargo por Manipulado y Transporte válido',
      'VALID_ADJUSTMENT':'Introduzca un ajuste válido',
      'WANT_TO_CONTINUE':'¿Quiere continuar?',
      'ENTER_VALID_TAX':'Introduzca un Valor de Impuesto válido',
      'VALID_TAX_NAME':'Introduzca un Nombre de Impuesto válido',
      'CORRECT_TAX_VALUE':'Introduzca un Valor de Impuesto correcto',
      'ENTER_POSITIVE_VALUE':'Introduzca un Valor positivo',
      'LABEL_SHOULDNOT_EMPTY':'El nombre del Impuesto no puede estar vacío',
      'NOT_VALID_ENTRY':'no es una entrada válida. Introduzca un valor correcto.',
      'VALID_DISCOUNT_PERCENT':'Introduzca un Porcentaje de Descuento válido',
      'VALID_DISCOUNT_AMOUNT':'Introduzca un Importe de Descuento válido',
      'SELECT_TEMPLATE_TO_MERGE':'Seleccione una plantilla para combinar',
      'SELECTED_MORE_THAN_ONCE':'Ha seleccionado este elemento más de una vez.',
      'YES':'si',
      'NO':'no',
      'MAIL':'mail',
      'EQUALS':'igual',
      'NOT_EQUALS_TO':'no igual a',
      'STARTS_WITH':'empieza con',
      'CONTAINS':'contiene',
      'DOES_NOT_CONTAINS':'no contiene',
      'LESS_THAN':'menor que',
      'GREATER_THAN':'mayor que',
      'LESS_OR_EQUALS':'menor o igual',
      'GREATER_OR_EQUALS':'mayor o igual',
      'NO_SPECIAL_CHARS':'No se admiten caracteres especiales en la cadena de la factura',
      'PLS_SELECT_VALID_FILE':'Seleccione un archivo con las siguientes extensiones:\n',
      'NO_SPECIAL':'Caracteres especiales no permitidos',
      'NO_QUOTES':'Comillas (\' ") y el símbolo de sumar (+) no permitidos ',
      'IN_PROFILENAME':' en Nombre de Perfil',
      'IN_GROUPNAME':' en Nombre de Grupo',
      'IN_ROLENAME':' en Nombre de Rol',
      'VALID_TAX_PERCENT':'Introduzca un Porcentaje de Impuesto válido',
      'VALID_SH_TAX':'Introduzca un Impuesto válido para Manipulación y Transportes',
      'ROLE_DRAG_ERR_MSG':'No puede mover un Nodo Padre bajo un Nodo Hijo',
      'LBL_DEL':'Supr',
      'VALID_DATA':' Introduzca una fecha válida. ',
      'STDFILTER':'Filtros Estandar',
      'STARTDATE':'Fecha de Inicio',
      'ENDDATE':'Fecha de Fin',
      'START_DATE_TIME':'Fecha y Hora de Inicio',
      'START_TIME':'Hora de Inicio',
      'DATE_SHOULDNOT_PAST':'Fecha y Hora para Actividades con Estatus Planeada',
      'TIME_SHOULDNOT_PAST':'Hora para Actividades con Estatus Planeada',
      'LBL_AND':'y',
      'LBL_ENTER_VALID_PORT':'Introduzca un Nº de puerto válido',
      'IN_USERNAME':' en Usuario ',
      'LBL_ENTER_VALID_NO':'Introduzca un número',
      'LBL_PROVIDE_YES_NO':' Valor incorrecto.\n introduzca SI o NO',
      'LBL_SELECT_CRITERIA':'Criterio Invalido.\n Elija otro criterio',
      'OPPORTUNITYNAME_CANNOT_BE_EMPTY':'El nombre de la Oportunidad no puede estar vacío',
      'OVERWRITE_EXISTING_ACCOUNT1':'¿Sobreescribir la dirección existente con la de la cuenta (',
      'NAME_DESC':' para Nombre de Carpeta y Descripción',
      'ENDS_WITH':'termina con',
      'SHARED_EVENT_DEL_MSG':'El usuario no está autorizado a eliminar el registro.',
      'LBL_WRONG_IMAGE_TYPE':'Los tipos de archivo permitidos son: jpeg, png, jpg, pjpeg, x-png or gif',
      'SELECT_MAIL_MOVE':'Seleccionar correo y mover',
      'LBL_NOTSEARCH_WITHSEARCH_ALL':'No ha usado la búsqueda. Todos los registros serán exportados desde ',
      'LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE':'No ha buscado nada. Pero ha seleccionado con una búsqueda y <br> página actual. Los registros de la página actual se<br> exportarán desde ',
      'LBL_NO_DATA_SELECTED':'No hay registros seleccionados. Seleccione, al menos, un registro a exportar',
      'LBL_SEARCH_WITHOUTSEARCH_ALL':'You have used search option but you have not selected without search & all options.\n You can click [ok] to export all data or  You can click [cancel] and try again with other export criteria',
      'STOCK_IS_NOT_ENOUGH':'No hay suficiente Stock',
      'INVALID_QTY':'Cantidad Inválida',
      'LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE':'You have used search option but you have not selected without search & currentpage options.\n You can click [ok]to export  current page data or You can click [cancel] and try again with some other export criteria.',
      'LBL_SELECT_COLUMN':'Columna inválida.\nSelecciona columna.',
      'LBL_NOT_ACCESSIBLE':'No Accesible',
      'LBL_FILENAME_LENGTH_EXCEED_ERR':'El nombre del fichero no puede contener más de 255 caracteres.',
      'LBL_DONT_HAVE_EMAIL_PERMISSION':'No tienes permiso para acceder al campo de email.',
      'LBL_NO_FEEDS_SELECTED':'No se ha seleccionado una difusión',
      'LBL_SELECT_PICKLIST':'Por favor selecciona al menos un valor para borrar',
      'LBL_CANT_REMOVE':'No se pueden eliminar todos los valores',

      // Added after 5.0.4 GA
      /*For global add/delete in picklist*/
      'LBL_GIVE_PICKLIST_VALUE':'Añade algún valor a la lista de selección',
      'LBL_SELECT_ROLE':'Selecciona al menos un rol que verá los nuevos valores',
      'LBL_ADD_PICKLIST_VALUE':'Añade al menos un nuevo valor',
      'LBL_NO_VALUES_TO_DELETE': 'no hay valores para eliminar',

      /* For Duplicate merging feature */
      'SAME_GROUPS': 'Tienes que seleccionar los registros en el mismo grupo para combinar',
      'ATLEAST_TWO': 'Selecciona al menos dos registros para combinar',
      'MAX_THREE': 'Está permitido seleccionar un máximo de tres registros',
      //PARENT_RECORD: 'Selecciona un registro como registro paterno',  MergeFields.tpl Line:59
      'MAX_RECORDS': 'Está permitido seleccionar un máximo de cuatro registros',
      'CON_MANDATORY': 'Selecciona el campo obligatorio Apellido',
      'LE_MANDATORY': 'Selecciona el campo obligatorio Apellido y Compañía',
      'ACC_MANDATORY': 'Selecciona el campo obligatorio Nombre Cuenta',
      'PRO_MANDATORY': 'Selecciona el campo obligatorio Nombre Producto',
      'TIC_MANDATORY': 'Selecciona el campo obligatorio Título Incidencia',
      'POTEN_MANDATORY': 'Selecciona el campo obligatorio Nombre Potencial',
      'VEN_MANDATORY': 'Selecciona el campo obligatorio Nombre Proveedor',
      'DEL_MANDATORY': 'No está permitido eliminar el campo obligatorio',

      /* For Multi-Currency Support */
      'MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE': 'El precio unitario de todas las monedas se actualizará basándose en la moneda seleccionada. ¿Estás seguro?',

      'Select_one_record_as_parent_record' : 'Selecciona un registro como entidad superior',
      'RECURRING_FREQUENCY_NOT_PROVIDED' : 'Frecuencia de recurrencia no establecida',
      'RECURRING_FREQNECY_NOT_ENABLED' : 'Frecuencia de recurrencia establecida, pero recursión no activada',
      /* Added for Documents module */
      'NO_SPECIAL_CHARS_DOCS':'Caracteres especiales como comillas, barra invertida, suma +, porcentaje % e interrogante ? no están permitidos',
      'FOLDER_NAME_TOO_LONG':'Nombre de carpeta demasiado largo. Inténtalo de nuevo!',
      'FOLDERNAME_EMPTY':'Nombre de carpeta vacío.',
      'DUPLICATE_FOLDER_NAME':'Nombre de carpeta ya existe. Inténtalo de nuevo!',
      'FOLDER_DESCRIPTION_TOO_LONG':'Descripción de carpeta demasiada larga. Inténtalo de nuevo!',
      'NOT_PERMITTED':'No tienes permiso para ejecutar esta operación.',

      'ALL_FILTER_CREATION_DENIED':'No se puede crear un filtro de nombre "All"/"Todo", utiliza un nombre diferente',
      'OPERATION_DENIED':'No tiene permiso para realizar esta operación',
      'EMAIL_CHECK_MSG': 'Deshabilita el acceso al portal para poder dejar vacío el campo de cuenta de correo',
      'IS_PARENT' : 'Este producto tiene sub-productos, no está permitido asignarle un producto superior o paterno',

      /*global actions on picklist*/
      'PICKLIST_CANNOT_BE_EMPTY': 'Valor de la lista no puede quedar vacío',
      'DUPLICATE_VALUES_FOUND': 'Se han encontrado valores duplicados',
      'LBL_NO_ROLES_SELECTED': 'No se ha seleccionado ningún rol. ¿Quieres continuar?',
      'LBL_DUPLICATE_FOUND': 'Entrada duplicada encontrada para el valor ',
      'LBL_CANNOT_HAVE_EMPTY_VALUE': 'No se puede tener valor nulo. Para eliminar, retrocede y pulsa el botón de eliminar',
      'LBL_DUPLICATE_VALUE_EXISTS': 'Valores duplicados existen',
      'LBL_WANT_TO_DELETE': 'Esto eliminará los valores de selección marcados para todos los roles. ¿Estás seguro de continuar? ',
      'LBL_DELETE_ALL_WARNING': 'Has marcado para eliminar todos los valores de selección. ¿Estás seguro de continuar?',
      'LBL_PLEASE_CHANGE_REPLACEMENT': "por favor cambia el valor de sustitución; también está seleccionado para eliminación",

      /*layout Editor changes*/
      'BLOCK_NAME_CANNOT_BE_BLANK' : 'El nombre del bloque no puede quedar vacío',
      'ARE_YOU_SURE_YOU_WANT_TO_DELETE' : '¿Estás seguro que quieres eliminar?',
      'PLEASE_MOVE_THE_FIELDS_TO_ANOTHER_BLOCK' : 'Por favor mueve los campos a otro bloque',
      'ARE_YOU_SURE_YOU_WANT_TO_DELETE_BLOCK' : '¿Estás seguro que quieres eliminar el bloque?',
      'LABEL_CANNOT_NOT_EMPTY' : 'La etiqueta no puede quedar vacía',
      'LBL_TYPEALERT_1' : 'No se puede vincular',
      'LBL_WITH' : 'con el tipo de dato',
      'LBL_TYPEALERT_2' : '. Vincula siempre tipos de datos equivalentes.',
      'LBL_LENGTHALERT' : 'No está permitido vincular campos con diferente número de caracteres. Trate de vincular los datos con igual o más número de caracteres.',
      'LBL_DECIMALALERT' : 'No está permitido vincular campos con diferente número de decimales. Trate de vincular los datos con igual o más número de decimales.',
      'FIELD_IS_MANDATORY' : 'Campo obligatorio',
      'FIELD_IS_ACTIVE' : 'Campo disponible',
      'FIELD_IN_QCREATE' : 'Disponible en Creación Rápida',
      'FIELD_IS_MASSEDITABLE' : 'Disponible para Edición Masiva',

      'IS_MANDATORY_FIELD' : 'es Campo Obligatorio',
      'CLOSEDATE_CANNOT_BE_EMPTY' : 'Fecha Cierre no puede quedar vacío',
      'AMOUNT_CANNOT_BE_EMPTY' : 'Cantidad no puede quedar vacío',
      'ARE_YOU_SURE' : '¿Estás seguro que quieres eliminar?',
      'LABEL_ALREADY_EXISTS' : 'Etiqueta ya existe. Por favor introduce una etiqueta diferente',
      'LENGTH_OUT_OF_RANGE' : 'La longitud del Bloque debe ser inferior a los 50 caracteres',
      'LBL_SELECT_ONE_FILE' : 'Por favor selecciona al menos un fichero',
      'LBL_UNABLE_TO_ADD_FOLDER' : 'No se ha podido añadir la Carpeta. Por favor intentalo otra vez.',
      'LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE_FOLDER' : '¿Estas seguro que quieres eliminar la carpeta?',
      'LBL_ERROR_WHILE_DELETING_FOLDER' : 'Error eliminando la carpeta. Por favor intentalo otra vez.',
      'LBL_FILE_CAN_BE_DOWNLOAD' : 'Fichero disponible para descarga',
      'LBL_DOCUMENT_LOST_INTEGRITY':'Documento no disponible. Se marcará como Inactivo',
      'LBL_DOCUMENT_NOT_AVAILABLE' : 'Fichero no disponible para descarga',
      'LBL_FOLDER_SHOULD_BE_EMPTY' : 'La carpeta ha de estar vacía para eliminarla!',

      'LBL_PLEASE_SELECT_FILE_TO_UPLOAD' : 'Por favor selecciona el fichero a cargar.',
      'LBL_ARE_YOU_SURE_TO_MOVE_TO' : '¿Estás seguro que quieres mover los ficheros a la carpeta ',
      'LBL_FOLDER' : '',
      'LBL_UNABLE_TO_UPDATE' : 'No se ha podido actualizar! Por favor intentalo otra vez.',
      'LBL_BLANK_REPLACEMENT': 'No se puede seleccionar un valor vacío como sustitución',

      'LBL_IMAGE_DELETED' : 'Imagen Eliminada',

      /* Tooltip management */
      'ERR_FIELD_SELECTION' : 'Errores en la selección de campos',

      /* Inventory validation strings */
      'NO_LINE_ITEM_SELECTED' : 'No hay ninguna línea seleccionada. Por favor selecciona al menos una línea.',
      'LINE_ITEM' : 'Línea',
      'LIST_PRICE': 'Precio Lista',
      
      /* Webmails */
      'LBL_PRINT_EMAIL' : 'Imprimir',
      'LBL_DELETE_EMAIL' : 'Borrar',
      'LBL_DOWNLOAD_ATTACHMENTS' : 'Descargar Adjuntos',
      'LBL_QUALIFY_EMAIL' : 'Clasificar',
      'LBL_FORWARD_EMAIL' : 'Reenviar',
      'LBL_REPLY_TO_SENDER' : 'Responder',
      'LBL_REPLY_TO_ALL' : 'Responder a todos',

      'LBL_WIDGET_HIDDEN' : 'Elemento escondido',
      'LBL_RESTORE_FROM_PREFERENCES' : 'Se puede habilitar en tus preferencias o con el botón de crear en la portada',
      'ERR_HIDING' : 'Error al esconder',
      'MSG_TRY_AGAIN' : 'Por favor intentalo otra vez',

      'MSG_ENABLE_SINGLEPANE_VIEW' : 'Vista sin Pestañas Habilitada',
      'MSG_DISABLE_SINGLEPANE_VIEW' : 'Vista sin Pestañas Deshabilitada',

      'MSG_FTP_BACKUP_DISABLED' : 'Copia FTP Deshabilitada',
      'MSG_LOCAL_BACKUP_DISABLED' : 'Copia Local Deshabilitada',
      'MSG_FTP_BACKUP_ENABLED' : 'Copia FTP Habilitada',
      'MSG_LOCAL_BACKUP_ENABLED' : 'Copia Local Habilitada',
      'MSG_CONFIRM_PATH' : 'confirma detalles Directorio',
      'MSG_CONFIRM_FTP_DETAILS' : 'confirma detalles FTP',

      'START_PERIOD_END_PERIOD_CANNOT_BE_EMPTY' : 'Periodo inicial o final no pueden quedar vacíos',

      /* added to fix i18n issues with home page*/
      'LBL_ADD': 'Añadir ',
      'Module': 'Módulo',
      'DashBoard': 'Cuadro Mando',
      'RSS': 'RSS',
      'Default': 'Defecto',
      'Notebook': 'Bloc Notas',
      'SPECIAL_CHARS':'\\ / < > + \' " ',

      'BETWEEN': 'entre',
      'BEFORE': 'antes',
      'AFTER': 'después',
      'ERROR_DELETING_TRY_AGAIN': 'Error eliminando. Por favor inténtalo otra vez.',
      'LBL_ENTER_WINDOW_TITLE': 'Introduce el título de la ventana.',
      'LBL_SELECT_ONLY_FIELDS': 'Selecciona solo dos campos.',
      'LBL_ENTER_RSS_URL':'Introduce la URL del RSS',
      'LBL_ADD_HOME_WIDGET': 'No se ha podido añadir elementos a la portada! Por favor inténtalo otra vez.',

      'LBL_DEFAULT_VALUE_FOR_THIS_FIELD' : 'Valor por defecto de este campo',

      'RECIPIENTS_CANNOT_BE_EMPTY' : 'Los destinatarios no puede quedar vacío',
      'VALID_SCANNER_NAME' : 'Introduce un nombre de clasificador válido (Solo Caracteres y Números)',
      'ERR_SAME_SOURCE_AND_TARGET' : 'El campo origen y destino no pueden ser el mismo',
      'ERR_ATLEAST_ONE_VALUE_FOR' : 'Has de seleccionar al menos un valor para',
      'ERR_SELECT_MODULE_FOR_DEPENDENCY' : 'Selecciona un módulo para añadir Dependencia',

	'LBL_SIZE_SHOULDNOTBE_GREATER':'El tamaño del fichero no debe ser superior a ', //added for upload error message
	'LBL_MAX_SIZE':'Tamaño máximo de fichero aceptado es', //added for display file size limit
	'LBL_FILESIZEIN_MB':'MB', // added to show filesize limit in MB
	'LBL_FILESIZEIN_KB':'KB', // added to show filesize limit in KB
	'LBL_FILESIZEIN_B':'B', // added to show filesize limit in B
	//Contexual help page
	'LBL_HELP_TITLE' : 'Ayuda',
	'LBL_WIKI_TITLE' : 'Manuales',
	'LBL_FAQ_TITLE'   : 'FAQ',
	'LBL_VIDEO_TITLE' : 'Vídeo',
	'LBL_CLOSE_TITLE' : 'Cerrar',
	'LBL_SELECT':'Selecciona los widgets por defecto a mostrar',
	
	'ERR_SELECT_ATLEAST_ONE_MERGE_CRITERIA_FIELD' : 'Selecciona al menos un campo para la combinación',
	'ERR_PLEASE_MAP_MANDATORY_FIELDS' : 'Por favor, vincula los siguientes campos obligatorios',
	'ERR_MAP_NAME_ALREADY_EXISTS' : 'Nombre de vinculación ya existe. Introduce un nombre distinto',
	'ERR_MAP_NAME_CANNOT_BE_EMPTY' : 'Nombre de vinculación no puede quedar vacío',
	'ERR_FIELDS_MAPPED_MORE_THAN_ONCE' : 'El siguiente campo se ha vinculado más de una vez. Verifica la vinculación.',
	
	//arror messages for lead conversion
	'ERR_SELECT_EITHER':'Selecciona Cuenta o Contacto para convertir el PreContacto',
	'ERR_SELECT_ACCOUNT':'Selecciona Cuenta para seguir',
	'ERR_SELECT_CONTACT':'Selecciona Contacto para seguir',
	'ERR_MANDATORY_FIELD_VALUE':'Faltan valores de campos obligatorios',
	'ERR_POTENTIAL_AMOUNT':'Cantidad de la oportunidad debe ser numérico',
	'ERR_EMAILID':'Introduce un email válido',
	'ERR_TRANSFER_TO_ACC':'Debes seleccionar una cuenta a la que transferir los elementos relacionados',
	'ERR_TRANSFER_TO_CON':'Debes seleccionar un contacto al que transferir los elementos relacionados',
	'SURE_TO_DELETE_CUSTOM_MAP':'¿Seguro que quieres eliminar la vinculación de campos?',
	'LBL_CLOSE_DATE':'Fecha Cierre',
	'LBL_EMAIL':'Email',
	'MORE_THAN_500' : 'Has seleccionado más de 500 registros. Esto puede tardar bastante tiempo. ¿Seguro que quieres continuar?',
	'LBL_MAPPEDALERT':'Esta campo ya está vinculado',
	'DELETE':'¿Está seguro que desea eliminar los seleccionados',
'RECORDS':' registros?',
'SELECT':'Por favor, seleccione al menos una entidad',
'DELETE_ACCOUNT':'La eliminación de esta cuenta (s) eliminará sus potenciales relacionados y Cotizaciones. ¿Está seguro que desea eliminar el seleccionado',
'DELETE_VENDOR':'La supresión de este proveedor (s) eliminará sus órdenes de compra correspondientes. ¿Está seguro que desea eliminar el seleccionado',
'SELECT_MAILID':'Por favor elija un mailid',
'OVERWRITE_EXISTING_ACCOUNT2':') Detalles de la dirección? Si hace clic en Cancelar el tema todavía está vinculado manteniendo direcciones independientes .',
'MISSING_FIELDS':'Faltan campos obligatorios:',
'NOT_ALLOWED_TO_EDIT':'usted no está autorizado a editar este campo',
'NOT_ALLOWED_TO_EDIT_FIELDS':'no se le permite editar el campo (s)',
'COLUMNS_CANNOT_BE_EMPTY':'Columnas seleccionadas no puede estar vacías',
'CANNOT_BE_EMPTY':' no puede estar vacía',
'CANNOT_BE_NONE':' no puede ser ninguno',
'ENTER_VALID':'Por favor, introduzca una dirección válida',
'SHOULDBE_LESS':' debe ser inferior a',
'SHOULDBE_LESS_EQUAL':' debe ser menor que o igual a',
'SHOULDBE_EQUAL':' debe ser igual a',
'SHOULDBE_GREATER':' debe ser mayor que',
'SHOULDBE_GREATER_EQUAL':' debe ser mayor que o igual a',
'INVALID':'Inválido',
'EXCEEDS_MAX':' supera el límite máximo',
'OUT_OF_RANGE':' está fuera del rango',
'SHOULDNOTBE_EQUAL':' no debe ser igual a',
'PORTAL_PROVIDE_EMAILID':'Usuario del Portal deberá proporcionar correo electrónico de identificación para el acceso portal',
'ADD_CONFIRMATION':'¿Está seguro que desea agregar el seleccionado',
'ACCOUNTNAME_CANNOT_EMPTY':'AccountName no puede estar vacío',
'CANT_SELECT_CONTACTS':'No se puede seleccionar contactos relacionados de Lead',
'LBL_THIS':'Esta',
'DOESNOT_HAVE_MAILIDS':' no tiene ningún código de correo',
'ARE_YOU_SURE':'¿Está seguro que desea eliminar?',
'DOESNOT_HAVE_AN_MAILID':'\ No tiene un ID de correo electrónico "',
'MISSING_REQUIRED_FIELDS':'Faltan campos obligatorios:',
'READONLY':'es de sólo lectura',
'SELECT_ATLEAST_ONE_USER':'Por favor, seleccione al menos un usuario',
'DISABLE_SHARING_CONFIRMATION':'¿Seguro que desea desactivar el uso compartido para seleccionar',
'USERS':' usuario (s)?',
'ENDTIME_GREATER_THAN_STARTTIME':'Hora de finalización debe ser mayor que la hora de inicio',
'FOLLOWUPTIME_GREATER_THAN_STARTTIME':'Tiempo de seguimiento debe ser mayor que Hora de finalización',
'MISSING_EVENT_NAME':'Falta el nombre del evento',
'EVENT_TYPE_NOT_SELECTED':'Tipo de evento no se ha seleccionado',
'CLOSEDATE_CANNOT_BE_EMPTY':'Fecha de cierre no puede estar vacío',
'SITEURL_CANNOT_BE_EMPTY':'Url del sitio no puede estar vacío',
'SITENAME_CANNOT_BE_EMPTY':'Nombre del sitio no puede estar vacío',
'LISTPRICE_CANNOT_BE_EMPTY':'Precio de lista no puede estar vacío',
'INVALID_LIST_PRICE':'Precio de lista inválido',
'PROBLEM_ACCESSSING_URL':'Problema para acceder url:',
'CODE':' Código:',
'WISH_TO_QUALIFY_MAIL_AS_CONTACT':'¿Está seguro de querer calificar este correo como contacto?',
'SELECT_ATLEAST_ONEMSG_TO_DEL':'Por favor, seleccione al menos un mensaje para borrar',
'ERROR':'Error',
'FIELD_TYPE_NOT_SELECTED':'Tipo de campo no se ha seleccionado',
'SPECIAL_CHARACTERS_NOT_ALLOWED':'Los caracteres especiales no están permitidos en el campo Etiqueta',
'SPECIAL_CHARACTERS':'Los caracteres especiales',
'NOT_ALLOWED':'no se admiten. Por favor, intente con otros valores',
'PICKLIST_CANNOT_BE_EMPTY':'Lista de selección el valor no puede estar vacío',
'DUPLICATE_VALUES_FOUND':'Valores duplicados encontrados',
'DUPLICATE_MAPPING_ACCOUNTS':'Duplicar asignación para cuentas!',
'DUPLICATE_MAPPING_CONTACTS':'Duplicar asignación para contactos!',
'DUPLICATE_MAPPING_POTENTIAL':'Duplicar el mapeo para el potencial!',
'ERROR_WHILE_EDITING':'Error durante la edición',
'CURRENCY_CHANGE_INFO':'Cambios de moneda se ha realizado con éxito',
'CURRENCY_CONVERSION_INFO':'¿Está utilizando Dolar $ como moneda? Haga clic en Aceptar para permanecer como $, Cancelar para cambiar la tasa de conversión de moneda. ',
'THE_EMAILID':'El correo electrónico de identificación ',
'EMAIL_FIELD_INVALID':'En el campo email no es válida',
'MISSING_REPORT_NAME':'Falta el nombre de Informe',
'REPORT_NAME_EXISTS':'Nombre del informe ya existe, intente otra vez ...',
'WANT_TO_CHANGE_CONTACT_ADDR':'¿Quieres cambiar las direcciones de los contactos relacionados con esta cuenta?',
'SURE_TO_DELETE':'¿Está seguro que desea eliminar?',
'NO_PRODUCT_SELECTED':'Ningún producto sleccionado. Seleccione al menos un producto',
'VALID_FINAL_PERCENT':'Ingrese Porcentaje descuento final válido',
'VALID_FINAL_AMOUNT':'Ingresar el importe de descuento final válido',
'VALID_SHIPPING_CHARGE':'Ingrese un valor de envío y manipulación válido',
'VALID_ADJUSTMENT':'Introduzca un ajuste válido',
'WANT_TO_CONTINUE':'¿Desea continuar?',
'ENTER_VALID_TAX':'Por favor, introduzca el valor fiscal válido',
'VALID_TAX_NAME':'Introduzca el nombre de Impuesto válido',
'CORRECT_TAX_VALUE':'Introduzca el valor del impuesto correcto',
'ENTER_POSITIVE_VALUE':'Por favor, introduzca un valor positivo',
'LABEL_SHOULDNOT_EMPTY':'El nombre de etiqueta de impuestos no debe estar vacío',
'NOT_VALID_ENTRY':'no es una entrada válida. Por favor, introduzca el valor correcto',
'VALID_DISCOUNT_PERCENT':'Introduzca un porcentaje de descuento válido',
'VALID_DISCOUNT_AMOUNT':'Introduzca un Importe de descuento válido',
'SELECT_TEMPLATE_TO_MERGE':'Por favor, seleccione una plantilla para combinar',
'SELECTED_MORE_THAN_ONCE':'Ha seleccionado el siguiente producto (s) más de una vez.',
'YES':'sí',
'NO':'no',
'MAIL':'correo',
'EQUALS':'es igual a',
'NOT_EQUALS_TO':'no es igual a',
'STARTS_WITH':'comienza con',
'CONTAINS':'contiene',
'DOES_NOT_CONTAINS':'no contiene',
'LESS_THAN':'menos que',
'GREATER_THAN':'más que',
'LESS_OR_EQUALS':'menor o igual',
'GREATER_OR_EQUALS':'mayor o igual',
'NO_SPECIAL_CHARS':'Los caracteres especiales no están permitidos en Cadena de Factura',
'PLS_SELECT_VALID_FILE':'Por favor, seleccione un archivo con la extensión siguiente:',
'NO_SPECIAL':'Los caracteres especiales no están permitidos',
'IN_PROFILENAME':' en nombre de perfil',
'IN_GROUPNAME':' en nombre del grupo',
'IN_ROLENAME':' en nombre de función',
'VALID_TAX_PERCENT':'Introduzca un porcentaje de impuestos válido',
'VALID_SH_TAX':'Ingrese Impuestos válidos para el transporte y la manipulación',
'ROLE_DRAG_ERR_MSG':'No se puede mover un nodo padre bajo un nodo secundario',
'LBL_DEL':'del',
'VALID_DATA':' Introducir datos válidos, por favor intente nuevamente...',
'STDFILTER':'Filtros estándar',
'STARTDATE':'Fecha de inicio',
'ENDDATE':'Fecha de finalización',
'START_DATE_TIME':'Fecha de inicio y hora',
'START_TIME':'Hora de inicio',
'DATE_SHOULDNOT_PAST':'Fecha y hora actual y hora de Actividades con el estado como estaba previsto',
'TIME_SHOULDNOT_PAST':'Hora actual de Actividades con el estado como estaba previsto',
'LBL_AND':'Y',
'LBL_ENTER_VALID_PORT':'Por favor, introduzca el número de puerto válido',
'IN_USERNAME':' Nombre de usuario',
'LBL_ENTER_VALID_NO':'Por favor, introduzca un número válido',
'LBL_PROVIDE_YES_NO':'Valor no válido. Indique Sí o No ',
 'LBL_SELECT_CRITERIA':'Criterios válidos. Por favor, seleccione criterios ',
'OPPORTUNITYNAME_CANNOT_BE_EMPTY':'el campo Nombre potencial no puede estar vacío',
'OVERWRITE_EXISTING_ACCOUNT1':'¿Desea sobreescribir la dirección existente con la cuenta seleccionada (',
'NAME_DESC':' para nombres de carpetas y Descripción',
'LBL_NONE':'Ninguno',
'ENDS_WITH':'extremos con',
'SHARED_EVENT_DEL_MSG':'El usuario no tiene permiso para editar / borrar eventos compartidos.',
'LBL_WRONG_IMAGE_TYPE':'Tipos de archivo permitidos para Contactos - jpeg, png, jpg, jpeg, x-png o gif',
'SELECT_MAIL_MOVE':'Seleccione un correo y luego pasar ..',
'LBL_NOTSEARCH_WITHSEARCH_ALL':'No ha utilizado la búsqueda. Todos los registros serán exportados desde',
'LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE':'No ha buscado ningun dato. Pero ha seleccionado con opciones de la página de búsqueda y actual. De modo que los registros de la página actual serán exportados desde',
'LBL_NO_DATA_SELECTED':'No hay ningún registro seleccionado. Seleccione al menos un registro para exportar',
'LBL_SEARCH_WITHOUTSEARCH_ALL':'Usted ha utilizado la opción de búsqueda, pero no ha seleccionado sin búsqueda y todas las opciones. Puede hacer clic en [Aceptar] para exportar todos los datos o puede hacer clic en [Cancelar] y volver a intentarlo con otros criterios de exportación ',
'STOCK_IS_NOT_ENOUGH':'Stock insuficiente',
'INVALID_QTY':'Cantidad inválida',
'LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE':'Usted ha utilizado la opción de búsqueda, pero no ha seleccionado sin opciones de búsqueda y CurrentPage. Puede hacer clic en [Aceptar] para exportar los datos de la página actual o puede hacer clic en [Cancelar] y vuelva a intentarlo con otros criterios de exportación. ',
'LBL_SELECT_COLUMN':'columna inválida Por favor, seleccione la columna ',
'LBL_NOT_ACCESSIBLE':'No Accesible',
'LBL_FILENAME_LENGTH_EXCEED_ERR':'Nombre de archivo no puede superar los 255 caracteres',
'LBL_DONT_HAVE_EMAIL_PERMISSION':'Usted no tiene permiso para el campo Correo electrónico por lo tanto no puede elegir el id de correo electrónico',
'LBL_NO_FEEDS_SELECTED':'No Feeds Seleccionados',
'LBL_SELECT_PICKLIST':'Por favor, seleccione al menos un valor para borrar',
'LBL_CANT_REMOVE':'No es posible eliminar todos los valores',
'LBL_CHECKIN_OVERWRITE':'Este registro existe desde su ultima apertura. ¿Igualmente  desea salvarlo?',
'POTENTIAL_AMOUNT_CANNOT_BE_EMPTY':'Cantidad potencial no puede estar vacío',
'LBL_CHECKIN_RELOAD':'La página se cargará nuevamente con datos actualizados.',
'LBL_ALERT_EXT_CODE':'Hay una cuenta con el mismo código externo, ¿desea fusionar estos clientes?',
'LBL_ALERT_EXT_CODE_NOTFOUND':'No se ha encontrado cuentas con ese código externo. Operación anulada',
'LBL_ALERT_EXT_CODE_COMMIT':'Las cuentas se combinaron con éxito, usted será redireccionado a la página de la cuenta combinada',
'LBL_ALERT_EXT_CODE_FAIL':'Error en la operación',
'LBL_ALERT_EXT_CODE_DUPLICATE':'Combinacion existente con ese código o el código está siendo utilizado también por una cuenta eliminada, operación abortada. Vaciar la papelera de reciclaje y volver a intentarlo.',
'LBL_ALERT_EXT_CODE_SAVE':'¿Desea guardar los cambios de todas maneras?',
'LBL_ALERT_EXT_CODE_NOTFOUND_SAVE':'No hay cuentas con ese código. Desea de todos modos guardar el código externo ?',
'LBL_ALERT_EXT_CODE_NOTFOUND_SAVE2':'No hay cuentas con ese código.Desea guardarla de todos modos?',
'LBL_ALERT_EXT_CODE_NO_PERMISSION':'Ya existe una cuenta con el mismo código asignado a otros usuarios. No se puede combinar.',
'DOESNOT_HAVE_AN_FAXID':'\ No tiene un Número de Identificación de fax "',
'LBL_DONT_HAVE_FAX_PERMISSION':'Usted no tiene permiso para  Fax por lo tanto no puede elegir el id de fax',
'DOESNOT_HAVE_AN_SMSID':'\ No tiene un Número de Identificación Sms "',
'LBL_DONT_HAVE_SMS_PERMISSION':'Usted no tiene permiso para el campo móvil por lo que no se puede elegir el id sms',
'NO_RULES_FOUND':'No hay reglas para este módulo, será redireccionado  al formulario de creación de reglas',
'SAME_GROUPS':'Usted tiene que seleccionar los registros en los mismos grupos para la combinación',
'ATLEAST_TWO':'Seleccione al menos dos registros para la combinación',
'MAX_THREE':'Se le permite seleccionar un máximo de tres registros',
'MAX_RECORDS':'Se le permite seleccionar un máximo de cuatro registros',
'CON_MANDATORY':'Seleccione el campo obligatorio Apellido',
'LE_MANDATORY':'Seleccione los campos obligatorios Apellido y Empresa',
'ACC_MANDATORY':'Seleccione el campo obligatorio Nombre de cuenta',
'PRO_MANDATORY':'Seleccione el campo obligatorio Nombre de Producto',
'TIC_MANDATORY':'Seleccione el campo obligatorio  Título Ticket',
'POTEN_MANDATORY':'Seleccione el nombre del campo obligatorio potencial',
'VEN_MANDATORY':'Seleccione el nombre del campo obligatorio Proveedor',
'DEL_MANDATORY':'Usted no tiene permiso para borrar el campo obligatorio',
'LBL_HIDEHIERARCH':'Ocultar jerarquía',
'LBL_SHOWHIERARCH':'Mostrar jerarquía',
'LBL_NO_ROLES_SELECTED':'No hay reglas seleccionadas, ¿desea continuar?',
'LBL_DUPLICATE_FOUND':'Encontradas entradas duplicadas  para el valor',
'LBL_CANNOT_HAVE_EMPTY_VALUE':'No se puede reemplazar con valor en blanco, para eliminar el uso de valor utilice la función  Eliminar.',
'LBL_DUPLICATE_VALUE_EXISTS':'Valor duplicado existente',
'LBL_WANT_TO_DELETE':'Esto eliminará el valor de lista desplegable seleccionado (s) para todas las funciones. ¿Estás seguro que desea continuar?',
'LBL_DELETE_ALL_WARNING':'Debe tener por lo menos un valor de la lista de selección',
'LBL_PLEASE_CHANGE_REPLACEMENT':'por favor, cambie el valor de reemplazo, ya que también está seleccionado para borrar',
'LBL_BLANK_REPLACEMENT':'No se puede seleccionar un valor en blanco para el reemplazo',
'LBL_PLEASE_SELECT':'- Por favor seleccione -',
'MUST_BE_CHECKED':'Debe ser revisado',
'CHARACTER':'caracteres',
'LENGTH':'longitud de',
'MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE':'Precio por unidad de todas las monedas será revisada en base a la moneda seleccionada. ¿Está seguro?',
'Select_one_record_as_parent_record':'Seleccione un registro como registro primario',
'RECURRING_FREQUENCY_NOT_PROVIDED':'Frecuencia recurrente no proporcionada',
'RECURRING_FREQNECY_NOT_ENABLED':'Frecuencia recurrente se proporciona, pero recurrente no está habilitado',
'NO_SPECIAL_CHARS_DOCS':'Los caracteres especiales como comillas, barra invertida, símbolo +,% y? no se admiten',
'FOLDER_NAME_TOO_LONG':'Nombre de la carpeta es demasiado largo. Inténtaeo de nuevo!',
'FOLDERNAME_EMPTY':'El nombre de la carpeta no puede estar vacío',
'DUPLICATE_FOLDER_NAME':'Tratando de duplicar un nombre de carpeta existente. Por favor, inténtelo de nuevo!',
'FOLDER_DESCRIPTION_TOO_LONG':'Descripción de la carpeta es demasiado largo. Inténtelo de nuevo!',
'NOT_PERMITTED':'No se permite la ejecución de esta operación.',
'ALL_FILTER_CREATION_DENIED':'No se puede crear el nombre CustomView usando \ All \ ", pruebe a utilizar ViewName diferente"',
'OPERATION_DENIED':'No esta autorizado a realizar esta operación',
'EMAIL_CHECK_MSG':'Deshabilitar el acceso portal para guardar el campo email en blanco',
'IS_PARENT':'Este producto tiene subproductos, usted no puedeelegir un Padre para este producto',
'BLOCK_NAME_CANNOT_BE_BLANK':'Nombre del bloque no puede estar en blanco',
'ARE_YOU_SURE_YOU_WANT_TO_DELETE':'¿Está seguro que desea eliminar?',
'PLEASE_MOVE_THE_FIELDS_TO_ANOTHER_BLOCK':'Por favor, mueva los campos a otro bloque',
'ARE_YOU_SURE_YOU_WANT_TO_DELETE_BLOCK':'¿Está seguro que desea eliminar bloque?',
'LABEL_CANNOT_NOT_EMPTY':'La etiqueta no puede estar vacía',
'LBL_TYPEALERT_1':'Lo sentimos, no se puede asignar la',
'LBL_WITH':'con',
'LBL_TYPEALERT_2':'tipo de datos. Sírvase asignar los mismos tipos de datos.',
'LBL_LENGTHALERT':'Lo sentimos, no puede asignar campos de tamaño de carácter diferente. Por favor mapear los datos con un tamaño de carácter igual o mayor.',
'LBL_DECIMALALERT':'Lo sentimos, no puedes asignar campos con diferentes posiciones decimales. Sírvase asignar los datos con los mismos lugares decimales o más.',
'FIELD_IS_MANDATORY':'Campo Obligatorio',
'FIELD_IS_ACTIVE':'Campo está disponible para uso',
'FIELD_IN_QCREATE':'Presente en Creación rápida',
'FIELD_IS_MASSEDITABLE':'Disponible para editar en masa',
'IS_MANDATORY_FIELD':'es campo obligatorio',
'AMOUNT_CANNOT_BE_EMPTY':'La cantidad no puede estar vacía',
'LABEL_ALREADY_EXISTS':'Etiqueta ya existe. Por favor, especifique una etiqueta diferente',
'LENGTH_OUT_OF_RANGE':'Longitud del bloque debe ser inferior a 50 caracteres',
'LBL_SELECT_ONE_FILE':'Por favor, seleccione por lo menos un archivo',
'LBL_UNABLE_TO_ADD_FOLDER':'No se pueden  añadir carpetas. Por favor, inténtelo de nuevo.',
'LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE_FOLDER':'¿Está seguro que desea eliminar la carpeta?',
'LBL_ERROR_WHILE_DELETING_FOLDER':'Error al eliminar la carpeta. Por favor inténtelo de nuevo más tarde.',
'LBL_FILE_CAN_BE_DOWNLOAD':'El archivo está disponible para su descarga',
'LBL_DOCUMENT_LOST_INTEGRITY':'Este documento no está disponible. Se marca como inactivo',
'LBL_DOCUMENT_NOT_AVAILABLE':'Este documento no está disponible para su descarga',
'LBL_FOLDER_SHOULD_BE_EMPTY':'Carpeta debe estar vacía para poder eliminarla!',
'LBL_PLEASE_SELECT_FILE_TO_UPLOAD':'Por favor, seleccione el archivo que desea cargar.',
'LBL_ARE_YOU_SURE_TO_MOVE_TO':'¿Está seguro que desea mover el archivo (s) a',
'LBL_FOLDER':' carpeta',
'LBL_UNABLE_TO_UPDATE':'No se puede actualizar! Por favor, inténtelo de nuevo.',
'LBL_IMAGE_DELETED':'Imagen eliminada',
'ERR_FIELD_SELECTION':'Algún error en la selección del campo',
'NO_LINE_ITEM_SELECTED':'No ha seleccionado ningún ítem. Por favor, seleccione al menos un elemento de línea.',
'LINE_ITEM':'La línea de pedido',
'LIST_PRICE':'Lista de precios',
'LBL_PRINT_EMAIL':'Imprimir',
'LBL_DELETE_EMAIL':'Borrar',
'LBL_DOWNLOAD_ATTACHMENTS':'Descargar archivos adjuntos',
'LBL_QUALIFY_EMAIL':'Calificar',
'LBL_FORWARD_EMAIL':'Adelante',
'LBL_REPLY_TO_SENDER':'Responder al remitente',
'LBL_REPLY_TO_ALL':'Responder a todos',
'LBL_WIDGET_HIDDEN':'Widget Ocultos',
'LBL_RESTORE_FROM_PREFERENCES':'Se puede restaurar a partir de sus preferencias',
'ERR_HIDING':'Error mientras se escondía',
'MSG_TRY_AGAIN':'Por favor, inténtelo de nuevo',
'MSG_ENABLE_SINGLEPANE_VIEW':'vista Singlepane Activada',
'MSG_DISABLE_SINGLEPANE_VIEW':'vista Singlepane desactivada',
'MSG_FTP_BACKUP_DISABLED':'Backup FTP desactivado',
'MSG_LOCAL_BACKUP_DISABLED':'Copia de seguridad local desactivada',
'MSG_FTP_BACKUP_ENABLED':'Backup FTP habilitado',
'MSG_LOCAL_BACKUP_ENABLED':'Copia de seguridad local activado',
'MSG_CONFIRM_PATH':'confirmar con los datos del recorrido',
'MSG_CONFIRM_FTP_DETAILS':'confirmar los detalles de FTP',
'START_PERIOD_END_PERIOD_CANNOT_BE_EMPTY':'período inicial o período final no pueden estar vacío',
'LBL_ADD':'Añadir',
'Module':'Módulo',
'DashBoard':'Tablero',
'RSS':'RSS',
'Default':'Defecto',
'Notebook':'ordenador portátil',
'SPECIAL_CHARS':'\\ / &lt; &gt; + \' \ "',
'no_valid_extension':'Extensión de archiovo inválida. Extensiones de archivo válidas son PDF, PS y TIFF',
'PRODUCT_LINE_NAME':'Nombre del producto',
'BUDGET_VALUE':'Presupuesto Valor',
'BETWEEN':'entre',
'BEFORE':'antes',
'AFTER':'después',
'ERROR_DELETING_TRY_AGAIN':'Error durante borrado. Por favor inténtelo de nuevo.',
'LBL_ENTER_WINDOW_TITLE':'Por favor, introduzca título de la ventana.',
'LBL_SELECT_ONLY_FIELDS':'Por favor, seleccione sólo dos campos.',
'LBL_ENTER_RSS_URL':'Por favor, introduzca la URL RSS',
'LBL_ENTER_URL':'Por favor, introduzca la URL',
'LBL_DELETED_SUCCESSFULLY':'Widget eliminado con éxito.',
'LBL_ADD_HOME_WIDGET':'No se puede agregar HomeStuff! Por favor, inténtelo de nuevo',
'LBL_STATUS_CHANGING':'Cambiar el estado en',
'LBL_STATUS_CHANGING_MOTIVATION':' nota:',
'LBL_STATUS_PLEASE_SELECT_A_MODULE':'Elija un módulo',
'LBL_STATUS_PLEASE_SELECT_A_ROLE':'Elegir un papel',
'OVERWRITE_EXISTING_CONTACT1':'¿Desea sobreescribir la dirección existente con el contacto seleccionado (',
'OVERWRITE_EXISTING_CONTACT2':') Detalles de la dirección? Si hace clic en Cancelar el tema todavía está vinculado manteniendo direcciones independientes .',
'SELECT_SMSID':'Por favor elija un mail id',
'NOTVALID_SMSID':'Sms número inválido',
'NULL_SMSID':'No hay un número definido Sms',
'LBL_MASS_EDIT_WITHOUT_WF_1':'Ha seleccionado más de',
'LBL_MASS_EDIT_WITHOUT_WF_2':' artículos, esto puede sobrecargar el servidor. Procede a actualizar excluyendo el flujo de trabajo?',
'EXISTING_RECORD':'Registro ya existe con estas fechas:',
'EXISTING_SAVE':'¿Quiere salvar más?',
'EXISTING_SAVE_CONVERTLEAD':'Si hace clic en Aceptar para el contacto y el potencial se vinculará a la cuenta existente.',
'LBL_MANDATORY_FIELDS_WF':'Introduzca un valor para los campos obligatorios',
'LBL_DELETE_MSG':'¿Está seguro de eliminar el formulario web?',
'LBL_DUPLICATE_NAME':'Webform ya existe',
'ERR_SELECT_EITHER':'Seleccione la organización o Contacto para convertir el Lead',
'ERR_SELECT_ACCOUNT':'Selecciona la Organización para proceder',
'ERR_SELECT_CONTACT':'Seleccione Contacto para proceder',
'ERR_MANDATORY_FIELD_VALUE':'Los valores de los campos obligatorios que faltan',
'ERR_POTENTIAL_AMOUNT':'Cantidad potencial debe ser un número',
'ERR_EMAILID':'Introduzca la ID de correo electrónico válida',
'ERR_TRANSFER_TO_ACC':'Organización debería ser seleccionada para transferir los registros relacionados',
'ERR_TRANSFER_TO_CON':'El contacto debería ser seleccionado para transferir registros relacionados',
'SURE_TO_DELETE_CUSTOM_MAP':'¿Está seguro que desea eliminar la asignación de campos?',
'LBL_CLOSE_DATE':'Cierre Fecha',
'LBL_EMAIL':'Email',
'MORE_THAN_500':'Ha seleccionado más de 500 registros. Para esta acción puede tardar más tiempo. ¿desea continuar?',
'LBL_MAPPEDALERT':'El campo ya  ha sido mapeado'


};
