var alert_arr = {    
	DELETE:'Êtes-vous sur de vouloir supprimer l\'élément sélectionné ?',
	RECORDS:'enregistrement',
	SELECT:'veuillez au moins sélectionner une entité',
	DELETE_ACCOUNT:'La suppression de cette (ces) entreprise (s) supprimera également  les opportunités et les estimations associées. Etes-vous sûr de vouloir supprimer ?',
	DELETE_VENDOR:'supprimer le fourbisseur amènera aussi la suppression des bons de commande en rapport. Etes-vous sur de vouloir supprimer ces éléments ?',
	SELECT_MAILID:'Veuillez sélectionner un identifiant d\'e-mail valide',
	OVERWRITE_EXISTING_ACCOUNT1:'Ecraser l\'adresse existante avec l\'adresse de l\'entreprise',
	OVERWRITE_EXISTING_ACCOUNT2:'sélectionné(e) ? En cliquant sur annuler l\'élément, les adresses indépendantes seront quand même maintenues.',
	MISSING_FIELDS:'nombre de champs pas spécifié',
	NOT_ALLOWED_TO_EDIT:'vous n\'êtes pas habilité pour modifier ce champ',
	NOT_ALLOWED_TO_EDIT_FIELDS:'vous n\'êtes pas habilité pour modifié ces champs',
	COLUMNS_CANNOT_BE_EMPTY:'les colonnes sélectionnées ne peuvent pas être vides',
	CANNOT_BE_EMPTY:'ne peut être vide',
	CANNOT_BE_NONE:'ne peut être nul',
	ENTER_VALID:'veuillez insérer un valide',
	SHOULDBE_LESS:'doit être inférieur à',
	SHOULDBE_LESS_EQUAL:'doit être inférieur ou égal à',
	SHOULDBE_EQUAL:'doit être égal à',
	SHOULDBE_GREATER:'doit être supérieur à',
	SHOULDBE_GREATER_EQUAL:'doit être supérieur ou égal à',
	VISITREPORTNOTHINGFOUND:'Invalid calendar entry',
	VISITREPORTWRONGTYPE:'Invalid Event Type or Account', 
	INVALID:'non valide',
	EXCEEDS_MAX:'sorti des limites maximum',
	OUT_OF_RANGE:'en dehors des limites maximum',
	SHOULDNOTBE_EQUAL:'ne doit pas être égal à',
	PORTAL_PROVIDE_EMAILID:'L\'utilisateur du portail doit spécifier un identifiant email pour entrer',
	ADD_CONFIRMATION:'Etes-vous sur de vouloir ajouter ?',
	ACCOUNTNAME_CANNOT_EMPTY:'le nom de l\'entreprise ne peut être ide',
	CANT_SELECT_CONTACTS:'il n\'est pas possible de sélectionner le contact lié par le lead',
	LBL_THIS:'ceci',
	DOESNOT_HAVE_MAILIDS:'n\'a pas d\'identifiant d\'email',
	ARE_YOU_SURE:'sur ?',
	DOESNOT_HAVE_AN_MAILID:'n\'a pas d\'identifiant d\'email',
	MISSING_REQUIRED_FIELDS:'ils manquent des champs obligatoires',
	READONLY:'en lecture seule',
	SELECT_ATLEAST_ONE_USER:'veuillez sélectionner au moins un utilisateur',
	DISABLE_SHARING_CONFIRMATION:'Êtes-vous sûr de vouloir désactiver les partages sélectionnés ?',
	USERS:'utilisateur(s)',
	ENDTIME_GREATER_THAN_STARTTIME:'La date de fin doit être supérieure à la date de début',
	FOLLOWUPTIME_GREATER_THAN_STARTTIME:'L\'heure de followup doit être supérieur à la date du début',
	MISSING_EVENT_NAME:'oubli du nom de l\'événement',
	EVENT_TYPE_NOT_SELECTED:'le type d\'événement n\'a pas été choisi',
	OPPORTUNITYNAME_CANNOT_BE_EMPTY:'le nom de l\'opportunité ne peut être vide',
	CLOSEDATE_CANNOT_BE_EMPTY:'la date de fermeture ne peut être vide',
	SITEURL_CANNOT_BE_EMPTY:'l\'URL du site ne peut être vide',
	SITENAME_CANNOT_BE_EMPTY:'le nom du site ne peut être vide',
	LISTPRICE_CANNOT_BE_EMPTY:'Le prix du catalogue ne peut être vide',
	INVALID_LIST_PRICE:'prix du catalogue non valide',
	PROBLEM_ACCESSSING_URL:'problèmes d\'accès à l\'URL',
	CODE:'code :',
	WISH_TO_QUALIFY_MAIL_AS_CONTACT:'Êtes-vous sûr de vouloir qualifier cet e-mail comme contact?',
	SELECT_ATLEAST_ONEMSG_TO_DEL:'Veuillez sélectionner au moins un message à supprimer',
	ERROR:'erreur',
	FIELD_TYPE_NOT_SELECTED:'type de champ non sélectionné',
	SPECIAL_CHARACTERS_NOT_ALLOWED:'Les caractères spéciaux ne sont pas autorisés dans l\'étiquette de champ',
	PICKLIST_CANNOT_BE_EMPTY:'la valeur de la picklist ne peut être vide',
	DUPLICATE_VALUES_FOUND:'valeur dupliquée non trouvée',
	DUPLICATE_MAPPING_ACCOUNTS:'dupliquer le mappage pour les entreprises',
	DUPLICATE_MAPPING_CONTACTS:'dupliquer le mappage pour les contacts',
	DUPLICATE_MAPPING_POTENTIAL:'dupliquer le mappage pour les occasions',
	ERROR_WHILE_EDITING:'erreur de modification',
	CURRENCY_CHANGE_INFO:'le changement de monnaie a été effectué avec succès',
	CURRENCY_CONVERSION_INFO:'Etes vous sur de vouloir utiliser le dollar comme monnaie?Cliquez sur OK pour rester sur le dollar,, ou annuler pour modifier le taux de change.',
	THE_EMAILID:'l\'identifiant de messagerie',
	EMAIL_FIELD_INVALID:'dans le champ de l\'email n\'est pas valide',
	MISSING_REPORT_NAME:'nom du rapport non spécifié',
	REPORT_NAME_EXISTS:'nom du rapport déjà existant,, essayer de nouveau',
	WANT_TO_CHANGE_CONTACT_ADDR:'Voulez-vous modifier les adresses du contact relié à cette entreprise?',
	SURE_TO_DELETE:'Êtes vous sur de vouloir éliminer ?',
	NO_PRODUCT_SELECTED:'aucun produit sélectionner. Sélectionnez au moins un produit',
	VALID_FINAL_PERCENT:'Entrer une valeur valide pour le pourcentage de remise',
	VALID_FINAL_AMOUNT:'Entrez une valeur valide pour le montant de la remise',
	VALID_SHIPPING_CHARGE:'entrer une valeur valide pour les dépenses d\'expédition',
	VALID_ADJUSTMENT:'Entrez une valeur valide pour arrondir',
	WANT_TO_CONTINUE:'Voulez-vous continuer?',
	ENTER_VALID_TAX:'veuillez insérer une valeur valide pour les taxes',
	VALID_TAX_NAME:'veuillez insérer un nom de taxe valide',
	CORRECT_TAX_VALUE:'veuillez insérer une valeur correcte pour les taxes',
	ENTER_POSITIVE_VALUE:'veuillez insérer une valeur positive',
	LABEL_SHOULDNOT_EMPTY:'L\'étiquette de la taxe ne peut être vide',
	NOT_VALID_ENTRY:'Ceci n\'est pas une valeur valide. Veuillez insérer une valeur valide.',
	VALID_DISCOUNT_PERCENT:'veuillez insérer une valeur valide pour le pourcentage de remise',
	VALID_DISCOUNT_AMOUNT:'Veuillez entrez une valeur valide pour le montant de la remise',
	SELECT_TEMPLATE_TO_MERGE:'veuillez sélectionner un modèle pour la fusion',
	SELECTED_MORE_THAN_ONCE:'vous avez sélectionné les produits suivants plus d\'une fois',
	YES:'oui',
	NO:'non  ',
	MAIL:'mail  ',
	EQUALS:'égal',
	NOT_EQUALS_TO:'différent',
	STARTS_WITH:'commence par',
	CONTAINS:'contient',
	DOES_NOT_CONTAINS:'ne contient pas',
	LESS_THAN:'inférieur à/moins que',
	GREATER_THAN:'supérieur à / plus que',
	LESS_OR_EQUALS:'inférieur ou égal',
	GREATER_OR_EQUALS:'supérieur ou égal',
	NO_SPECIAL_CHARS:'Les caractères spéciaux ne sont pas autorisés dans la chaîne de facture',
	SHARED_EVENT_DEL_MSG:'l\'utilisateur ne peut pas supprimer l\'enregistrement',
	PLS_SELECT_VALID_FILE:'Veuillez sélectionner un fichier avec l\'une des extensions suivantes:',
	NO_SPECIAL:'les caractères spéciaux ne sont pas autorisés',
	NO_QUOTES:'Les apostrophes (\'),, les guillemets () et les somme symboliques de (+) ne sont pas autorisés "',
	IN_PROFILENAME:'dans le nom du profil',
	IN_GROUPNAME:'dans le nom du groupe',
	IN_ROLENAME:'dans le nom du rôle',
	VALID_TAX_PERCENT:'veuillez insérer une valeur valide pour le pourcentage des taxes',
	VALID_SH_TAX:'veuillez insérer une valeur valide pour le pourcentage des taxes d\'expédition',
	ROLE_DRAG_ERR_MSG:'Impossible de supprimer un rôle supérieur par un inférieur',
	LBL_DEL:'Supp.',
	VALID_DATA:'veuillez insérer une date valide',
	STDFILTER:'filtres standard',
	STARTDATE:'date de début',
	ENDDATE:'date de fin',
	START_DATE_TIME:'date et heure du début',
	START_TIME:'horaire du début',
	DATE_SHOULDNOT_PAST:'Date et heure prévue pour les activités planifiées',
	TIME_SHOULDNOT_PAST:'heure courante pour les activités planifiées',
	LBL_AND:'et',
	LBL_ENTER_VALID_PORT:'Veuillez entrer un numéro de port valide',
	IN_USERNAME:'dans le nom de l\'utilisateur',
	LBL_ENTER_VALID_NO:'veuillez insérer un numéro valide',
	LBL_PROVIDE_YES_NO:'valeur non valide. Veuillez insérer oui ou non',
	LBL_SELECT_CRITERIA:'Critère non valide. Veuillez sélectionner un critère',
	LBL_WRONG_IMAGE_TYPE:'Type de fichier image pour les contacts - jpeg,, png,, jpg,, jpeg,, png ou gif x-',
	SELECT_MAIL_MOVE:'veuillez sélectionner un email et envoyez',
	LBL_NOTSEARCH_WITHSEARCH_ALL:'Vous n\'avez pas utilisé la fonction de recherche. Tous les documents seront exportés vers',
	LBL_NOTSEARCH_WITHSEARCH_CURRENTPAGE:'Vous n\'avez pas utilisé la fonction de recherche. Mais vous avez sélectionné l\'option recherche de la page en cours,, pour lesquels les enregistrements de la page en cours seront exportés vers',
	LBL_NO_DATA_SELECTED:'Aucun dossier sélectionné. Sélectionnez au moins un enregistrement à exporter.',
	LBL_SEARCH_WITHOUTSEARCH_ALL:'Vous avez utilisé l\'option de recherche mais vous n\'avez pas sélectionné sans recherche e toutes les options. Cliquez sur (OK) pour exporter toutes les dates ou cliquez sur (annuler) et réessayez avec d\'autres critères d\'exportation',
	STOCK_IS_NOT_ENOUGH:'le stock en magasin n\'est pas suffisant',
	INVALID_QTY:'quantité non valide',
	LBL_SEARCH_WITHOUTSEARCH_CURRENTPAGE:'Vous avez utilisé l\'option de recherche,, mais vous n\'avez pas sélectionné sans recherche et les options de la page en cours.  Cliquez (ok) pour exporter les données de la page en cours ou cliquez (annuler) et réessayez avec d\'autres critères d\'exportation.',
	LBL_SELECT_COLUMN:'Colonne non valide. Veuillez sélectionner une colonne valide',
	LBL_NOT_ACCESSIBLE:'non accessible',
	LBL_FILENAME_LENGTH_EXCEED_ERR:'le nom du fichier ne peut pas dépasser 255 caractères de longueur',
	LBL_DONT_HAVE_EMAIL_PERMISSION:'Vous n\'avez pas les autorisations pour le champ de l\'email donc vous ne pouvez pas sélectionner l\'id de l\'email',
	LBL_NO_FEEDS_SELECTED:'aucun feed sélectionné',
	LBL_SELECT_PICKLIST:'Veuillez sélectionner au moins une valeur à éliminer',
	LBL_CANT_REMOVE:'vous ne pouvez pas supprimer toutes les valeurs',
	LBL_UTF8:'Veuillez modifier le fichier de configuration (qui se trouve à la racine de vtiger avec le nom config-inc.php) pour soutenir l\'ensemble des caractères UTF-8,, puis actualiser la page',
	SPECIAL_CHARACTERS:'les caractères spéciaux  ',
	NOT_ALLOWED:'ne sont pas autorisés dans le champ étiquette. Veuillez essayer avec d\'autres valeurs',
	LBL_NONE:'aucun  ',
	ENDS_WITH:'se termine par',
	POTENTIAL_AMOUNT_CANNOT_BE_EMPTY:'le montant potentiel ne peut être vide',
	LBL_ALERT_EXT_CODE:'Il a été trouvé une entreprise avec le même code externe,, vous voulez fusionner les deux sociétés?',
	LBL_ALERT_EXT_CODE_NOTFOUND:'aucune société n\'a été trouvé avec le même code externe ,, opération annulée ',
	LBL_ALERT_EXT_CODE_COMMIT:'fusion des entreprises effectuée avec succès,, la page de l\'entreprise importée va être chargée',
	LBL_ALERT_EXT_CODE_FAIL:'l\'opération a échouée',
	LBL_ALERT_EXT_CODE_DUPLICATE:'Vous essayez de refaire la fusion avec ce code ou d\'utiliser le code de la société effacé,, opération annulée. Videz la corbeille et essayez à nouveau.',
	LBL_ALERT_EXT_CODE_SAVE:'Voulez vous quand même sauver les modifications ?',
	LBL_ALERT_EXT_CODE_NOTFOUND_SAVE:'Aucune société importée n\'a été trouvée avec ce code externe,, sauver quand même le code externe ?',
	LBL_ALERT_EXT_CODE_NOTFOUND_SAVE2:'Aucune société importée n\'a été trouvée avec ce code externe,, sauver quand même les modifications apportées à l\'entreprise ?',
	LBL_ALERT_EXT_CODE_NO_PERMISSION:'Il est existe déjà une entreprise avec le même code attribué à un autre utilisateur,, vous n\'avez donc pas la permission d\'effectuer la fusion.',
	DOESNOT_HAVE_AN_FAXID:'n\'a pas un numéro de fax',
	LBL_DONT_HAVE_FAX_PERMISSION:'vous n\'avez pas la permission pour le champ de fax donc vous ne pouvez pas sélectionner l\'identifiant du fax',
	DOESNOT_HAVE_AN_SMSID:'n\'a pas de numéro de mobile',
	LBL_DONT_HAVE_SMS_PERMISSION:'Vous n\'avez pas l\'autorisation pour les champs du mobile,, vous ne pouvez pas sélectionner l\'Identifiant sms',
	NO_RULES_FOUND:'Aucune règle trouvée pour ce module,, vous serez renvoyé au forum pour créer une nouvelle règle',
	SAME_GROUPS:'Vous devez sélectionner les enregistrements qui sont dans le même groupe d\'union',
	ATLEAST_TWO:'sélectionnez au moins deux enregistrement',
	MAX_THREE:'il est permis de sélectionner un maximum de trois enregistrements',
	MAX_RECORDS:'il est permis de sélectionner un maximum de quatre enregistrements',
	CON_MANDATORY:'sélectionnez le champ obligatoire / nom de famille/',
	LE_MANDATORY:'sélectionnez le champ obligatoire / nom de famille/ et / société /',
	ACC_MANDATORY:'sélectionnez le champ obligatoire / nom de l\'entreprise /',
	PRO_MANDATORY:'sélectionnez le champ obligatoire / nom du produit //',
	TIC_MANDATORY:'sélectionnez le champ obligatoire / titre du ticket /',
	POTEN_MANDATORY:'sélectionnez le champ obligatoire / nom de l’occasion /',
	VEN_MANDATORY:'sélectionnez le champ obligatoire / nom du fournisseur /',
	DEL_MANDATORY:'vous n\'avez pas la permission pour supprimer un champ obligatoire',
	LBL_HIDEHIERARCH:'masquer la hiérarchie',
	LBL_SHOWHIERARCH:'montrer la hiérarchie',
	LBL_NO_ROLES_SELECTED:'aucun rôle n\'a été sélectionné,, continuer quand même ?',
	LBL_DUPLICATE_FOUND:'Entréen dupliquée trouvée pour cette valeur',
	LBL_CANNOT_HAVE_EMPTY_VALUE:'Impossible de remplace par une valeur vide,, pour supprimer la valeur,, utilisez l\'option Supprimer.',
	LBL_DUPLICATE_VALUE_EXISTS:'valeur dupliquée existante',
	LBL_WANT_TO_DELETE:'Cela permettra éliminera les valeurs sélectionnées de la liste de sélection pour tous les rôles. Êtes-vous sûr de vouloir continuer?',
	LBL_DELETE_ALL_WARNING:'Doit avoir au moins une valeur pour la liste de sélection',
	LBL_PLEASE_CHANGE_REPLACEMENT:'Veuillez changer la valeur de substitution,, il a été sélectionne pour la suppression',
	LBL_BLANK_REPLACEMENT:'impossible de sélectionner une valeur vide pour la substitution',
	LBL_PLEASE_SELECT:'Veuillez sélectionner  ',
	MUST_BE_CHECKED:'doit être sélectionné',
	CHARACTER:'caractères',
	LENGTH:'la longueur',
	MSG_CHANGE_CURRENCY_REVISE_UNIT_PRICE:'Le prix ​​unitaire pour toutes les devises sera révisé sur la base de la monnaie choisie. Etes-vous sûr?',
	Select_one_record_as_parent_record:'Choisir un enregistrement comme enregistrement de relation',
	RECURRING_FREQUENCY_NOT_PROVIDED:'Taux périodique non inclus',
	RECURRING_FREQNECY_NOT_ENABLED:'Taux périodique fourni,, mais pas activé',
	NO_SPECIAL_CHARS_DOCS:'Les caractères spéciaux tels que les guillemets,, les antislashs,, +,,%,, et?  Sont interdits',
	FOLDER_NAME_TOO_LONG:'Le nom du dossier est trop long. Essayez à nouveau!',
	FOLDERNAME_EMPTY:'le nom du dossier ne peut être vide',
	DUPLICATE_FOLDER_NAME:'Vous avez essayé de dupliquer un nom de dossier déjà existant. S\'il vous plaît essayez de nouveau!',
	FOLDER_DESCRIPTION_TOO_LONG:'Description du dossier trop longue,, essayez encore !',
	NOT_PERMITTED:'Opération non permise.',
	ALL_FILTER_CREATION_DENIED:'Impossible de créer un CustomView utilisant le nom  	out  ",, essayez d\'utiliser un autre nom différent"',
	OPERATION_DENIED:'opération non exécutable',
	EMAIL_CHECK_MSG:'Désactiver l\'accès au portail pour sauver de l\'e-mail comme champ vide.',
	IS_PARENT:'Ce produit a des sous-produits,, il n\'est pas autorisé à choisir un rapport pour ce produit',
	BLOCK_NAME_CANNOT_BE_BLANK:'Le nom du bloc ne peut être vide',
	ARE_YOU_SURE_YOU_WANT_TO_DELETE:'sur de vouloir éliminer ?',
	PLEASE_MOVE_THE_FIELDS_TO_ANOTHER_BLOCK:'Veuillez déplacer le champ dans un autre bloc',
	ARE_YOU_SURE_YOU_WANT_TO_DELETE_BLOCK:'Sur de vouloir éliminer le bloc ?',
	LABEL_CANNOT_NOT_EMPTY:'L\'étiquette ne peut être vide',
	LBL_TYPEALERT_1:'Désolé,, vous ne pouvez pas mapper',
	LBL_WITH:'avec',
	LBL_TYPEALERT_2:'type de donnée. S\'il vous plaît cartographier les mêmes types de donnée.',
	LBL_LENGTHALERT:'Désolé,, vous ne pouvez mapper les champs avec des caractères différents. S\'il vous plaît mappez les données avec les mêmes ou plus de caractères.',
	LBL_DECIMALALERT:'Désolé,, vous ne pouvez mapper les champs avec des décimales différents. S\'il vous plaît mapper des données avec les mêmes ou plus de décimales.',
	FIELD_IS_MANDATORY:'Champ obligatoire',
	FIELD_IS_ACTIVE:'champ disponible pour l\'utilisation.',
	FIELD_IN_QCREATE:'Présent dans la Création rapide',
	FIELD_IS_MASSEDITABLE:'disponible pour le mass edit',
	IS_MANDATORY_FIELD:'est un champ obligatoire',
	AMOUNT_CANNOT_BE_EMPTY:'la quantité ne peut être vide',
	LABEL_ALREADY_EXISTS:'étiquette déjà présente. Veuillez insérer  un autre nom',
	LENGTH_OUT_OF_RANGE:'la longueur du bloc doit être inférieur à 50 caractères.',
	LBL_SELECT_ONE_FILE:'Veuillez sélectionner au moins un fichier ',
	LBL_UNABLE_TO_ADD_FOLDER:'Impossible d\'ajouter un dossier. Veuillez essayer à nouveau',
	LBL_ARE_YOU_SURE_YOU_WANT_TO_DELETE_FOLDER:'Sur de vouloir éliminer le dossier ?',
	LBL_ERROR_WHILE_DELETING_FOLDER:'erreur durant la suppression du dossier. Veuillez essayer encore.',
	LBL_FILE_CAN_BE_DOWNLOAD:'le fichier est disponible en téléchargement',
	LBL_DOCUMENT_LOST_INTEGRITY:'Ces documents ne sont pas disponibles. Ils seront marqués comme envoyés.',
	LBL_DOCUMENT_NOT_AVAILABLE:'Ce document n\'est pas disponible en téléchargement.',
	LBL_FOLDER_SHOULD_BE_EMPTY:'le dossier devrait être vide pour être déplacé !',
	LBL_PLEASE_SELECT_FILE_TO_UPLOAD:'Veuillez sélectionner le fichier  à télécharger',
	LBL_ARE_YOU_SURE_TO_MOVE_TO:'Sur de vouloir déplacer le fichier  dans',
	LBL_FOLDER:'dossier',
	LBL_UNABLE_TO_UPDATE:'impossible de mettre en jour. Veuillez essayer encore',
	LBL_IMAGE_DELETED:'image supprimée',
	ERR_FIELD_SELECTION:'quelques erreurs dans le champ sélectionné',
	NO_LINE_ITEM_SELECTED:'aucune ligne n\'a été sélectionnée. Veuillez sélectionner au moins une ligne.',
	LINE_ITEM:'ligne',
	LIST_PRICE:'catalogue',
	LBL_PRINT_EMAIL:'imprimer',
	LBL_DELETE_EMAIL:'supprimer',
	LBL_DOWNLOAD_ATTACHMENTS:'téléchargement pièce jointe  ',
	LBL_QUALIFY_EMAIL:'qualifié',
	LBL_FORWARD_EMAIL:'expédier',
	LBL_REPLY_TO_SENDER:'répondre à l\'expéditeur',
	LBL_REPLY_TO_ALL:'répondre à tous',
	LBL_WIDGET_HIDDEN:'widget caché',
	LBL_RESTORE_FROM_PREFERENCES:'Vous pouvez le restaurer à partir de vos préférences',
	ERR_HIDING:'erreur durant le masquage  du widget',
	MSG_TRY_AGAIN:'Veuillez essayer de nouveau',
	MSG_ENABLE_SINGLEPANE_VIEW:'panneau simple activé',
	MSG_DISABLE_SINGLEPANE_VIEW:'panneau simple désactivé',
	MSG_FTP_BACKUP_DISABLED:'ftp backup désactivé',
	MSG_LOCAL_BACKUP_DISABLED:'backup local désactivé',
	MSG_FTP_BACKUP_ENABLED:'ftp backup activé',
	MSG_LOCAL_BACKUP_ENABLED:'backup local activé',
	MSG_CONFIRM_PATH:'itinéraire mis à jour',
	MSG_CONFIRM_FTP_DETAILS:'confirmer avec les détails FTP',
	START_PERIOD_END_PERIOD_CANNOT_BE_EMPTY:'Durée initiale ou finale ne peut pas être vide',
	LBL_ADD:'ajouter',
	Module:'module',
	DashBoard:'tableau de bord',
	RSS:'RSS',
	Default:'défaut',
	Notebook:'notes',
	SPECIAL_CHARS:' / &lt; &gt; + \'  "',
	ERR_PIVA:'Numéro SIRET invalide',
	ERR_CF:'Code fiscal non valide',
	EXISTING_RECORD:'enregistrement déjà existent dans le système daté',
	EXISTING_SAVE:'voulez vous sauvegarder quand même ?',
	EXISTING_SAVE_CONVERTLEAD:'le contact et les éventuelles opportunités  se verront liés à l\'entreprise déjà existante',
	no_valid_extension:'extension du fichier  non valide. Les extensions permises sont pdf,, ps et tiff',
	PRODUCT_LINE_NAME:'nom du produit',
	BUDGET_VALUE:'valeur du budget',
	BETWEEN:'Entre',
	BEFORE:'avant',
	AFTER:'après',
	ERROR_DELETING_TRY_AGAIN:'erreur durant la suppression. Veuillez essayer encore.',
	LBL_ENTER_WINDOW_TITLE:'Veuillez insérer le titre de la fenêtre',
	LBL_SELECT_ONLY_FIELDS:'Veuillez sélectionner seulement deux champs',
	LBL_ENTER_RSS_URL:'Veuillez insérer l\'adresse du RSS',
	LBL_ENTER_URL:'Veuillez insérer l\'adresse du site web.',
	LBL_DELETED_SUCCESSFULLY:'Widget supprimé avec succès.',
	LBL_ADD_HOME_WIDGET:'Impossible d\'ajouter le widget. Veuillez réessayer.',
	LBL_STATUS_CHANGING:'changement de statut dans',
	LBL_STATUS_CHANGING_MOTIVATION:'note :',
	LBL_STATUS_PLEASE_SELECT_A_MODULE:'choisir un module',
	LBL_STATUS_PLEASE_SELECT_A_ROLE:'choisir un rôle',
	OVERWRITE_EXISTING_CONTACT1:'Ecraser l\'adresse existante avec l\'adresse du contact',
	OVERWRITE_EXISTING_CONTACT2:'(sélectionné(e) ? En cliquant sur annulé,, l\'élément sera toujours lié en gardant adresses indépendantes',
	LBL_MASS_EDIT_WITHOUT_WF_1:'vous avez sélectionné plus de',
	LBL_MASS_EDIT_WITHOUT_WF_2:'éléments,, ceci pourrait surcharger le serveur. Procéder à la mise à jour en excluant flux de travail?',
	SELECT_SMSID:'Veuillez sélectionner un identifiant de sms valide',
	NOTVALID_SMSID:'numéro de mobile non valide',
	NULL_SMSID:'aucun numéro de mobile spécifié'
};